// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/supportClasses/SectionLayoutManager","dojo/_base/declare dojo/dom-style ./SectionContentFitModes ../../grid/coreUtils/GridDataUtil ../../infographics/InfographicTypes esri/dijit/geoenrichment/utils/FitUtil".split(" "),function(g,d,e,l,n,p){g=g(null,{section:null,constructor:function(a){this.section=a},getWidth:function(){return d.get(this.section.domNode,"width")},_widthInitializedFlag:!1,setWidth:function(a,b){b=b||{};var c=this._widthInitializedFlag?
d.get(this.section.domNode,"width"):0;b&&b.previousDim&&(c=b.previousDim.w,this._widthInitializedFlag=!0);d.set(this.section.domNode,"width",a+"px");this._widthInitializedFlag=this._widthInitializedFlag||1<a;this.section.hasFixedLayout?this.section.getTables().forEach(function(c){(c.getMaxWidth()!==a||b.forceResize)&&c.setMaxWidth(a,{resizeToFitAllowedWidth:b.resizeContentToFit,preserveRightOffset:b.preserveRightOffset})}):this._widthInitializedFlag&&b&&b.resizeContentProportionally&&c&&a&&c!==a&&
this.scaleFloatingContentProportionally({xScale:a/c,yScale:1})},getHeight:function(a){if(!this.section.hasFixedLayout)return 0;var b=0;this.section._stackElements.forEach(function(c){switch(c.stackId){case "table":b+=c.getHeight(a);c.isLocatorTable&&c.isLocatorTable()&&(b+=c.getLocatorTablePreviewExtraHeight());break;case "hr":b+=d.get(c,"height");break;case "pageBreak":b+=d.get(c,"height")}});return b},getResizedHeight:function(){return this.section.hasFixedLayout?this.getHeight(!0):d.get(this.section.domNode,
"height")},_resizedHeightInitializedFlag:!1,_setResizedHeight:function(a,b){if(this.section.hasFixedLayout){var c=this.section.getLastTable();c&&c.setSpaceAfter(a-this.getHeight())}c=this._resizedHeightInitializedFlag?d.get(this.section.domNode,"height"):0;b&&b.previousDim&&(c=b.previousDim.h,this._resizedHeightInitializedFlag=!0);d.set(this.section.domNode,"height",a+"px");this._resizedHeightInitializedFlag=this._resizedHeightInitializedFlag||1<a;!this.section.hasFixedLayout&&b&&b.resizeContentProportionally&&
c&&a&&c!==a&&this.scaleFloatingContentProportionally({xScale:1,yScale:a/c})},setResizedHeight:function(a,b){this._setResizedHeight(a,b);if(this.section.hasFixedLayout){var c=this;this.section.getTables().forEach(function(a){a.needScaleToFitHeight()&&c._scaleFixedTableToFitHeight(a)})}},updateHeightAfterContentChange:function(){this.section.hasFixedLayout&&this._setResizedHeight(this.getResizedHeight())},scaleFloatingContentProportionally:function(a){this.section.hasFixedLayout||1===a.xScale&&1===
a.yScale||this.section._stackElements.forEach(function(b){switch(b.stackId){case "table":b.scaleProportionallyWithinParent(a);break;case "img":b.scaleProportionallyWithinParent(a)}})},getFloatingContentBox:function(){var a,b,c,d;function e(f){a=Math.min(a,f.l);b=Math.min(b,f.t);c=Math.max(c,f.l+f.w);d=Math.max(d,f.t+f.h)}b=a=Infinity;d=c=0;this.section._stackElements.forEach(function(a){switch(a.stackId){case "table":e(a.getTableBox());break;case "img":e(a.getImageBox(!1))}});return{l:a,t:b,w:c-a,
h:d-b}},fitContentNicely:function(a,b){a=a||{};this.section.hasFixedLayout?this._fitFixedTablesNicely(a,b):this._fitFloatingContentNicely(a,b)},_fitFixedTablesNicely:function(a,b){if(a.fitMode!==e.NONE){a.fitMode===e.ALL&&delete a.fitMode;var c=this;(b||this.section.getTables()).forEach(function(b){"table"===b.stackId&&(a.fitMode!==e.WIDTH&&a.fitMode||b.resizeToFitAllowedWidth(),a.fitMode!==e.HEIGHT&&a.fitMode||c._scaleFixedTableToFitHeight(b))});this.section._notifyContentChanged()}},_scaleFixedTableToFitHeight:function(a){a.resizeToFitHeight(this.section.getResizedHeight());
a.setSpaceAfter(0)},_fitFloatingContentNicely:function(a,b){var c=a.fitMode;if(c!==e.NONE&&(a=this.getFloatingContentBox(),b=b||this.section._stackElements,b.length)){var g,k;if(1!==b.length||"img"!==b[0].stackId||b[0].isMapImage()){c===e.SINGLE_ALL_COMPLEX_WIDTH&&(c=1<b.length?e.WIDTH:e.ALL);var f=this._getContentFitOffset(b),l=this.section.getWidth()-2*f,m=d.get(this.section.domNode,"height")-2*f;1<b.length&&a.h>m&&(c=e.ALL);var h={xScale:c===e.HEIGHT?1:l/a.w,yScale:c===e.WIDTH?1:m/a.h};g=f-a.l*
h.xScale;k=f-a.t*h.yScale}else c=p.fitBox(a,{w:this.section.getWidth()-0,h:d.get(this.section.domNode,"height")-0},{hAlign:"center",vAlign:"middle"}),h={xScale:c.ratio,yScale:c.ratio},g=0+c.x-a.l*h.xScale,k=0+c.y-a.t*h.yScale;b.forEach(function(a){switch(a.stackId){case "table":a.scaleProportionallyWithinParent(h);a.setGridPosition(g+a.getLeft(),k+a.getTop());break;case "img":a.scaleProportionallyWithinParent(h),d.set(a.domNode,{left:g+d.get(a.domNode,"left")+"px",top:k+d.get(a.domNode,"top")+"px"})}})}},
_getContentFitOffset:function(a){var b=this.section.getTables()[0],c=b&&b.isSingleCelledTable()&&l.getFieldInfo(b.getFieldCells()[0]);return this.section.noContentOffset?0:1<a.length?5:this.section.hasInfographic(n.LOCATOR_TABLE)?this.section.viewModel.getCurrentTheme(this.section.theme).table.dataTablePadding||0:this.section.hasInfographic()?this.section.viewModel.getStaticInfographicDefaultStyles(this.section.theme).padding||0:b&&(this.section.isImageTable(b)||c&&c.isShape)?0:this.section.hasChart()?
0:this.section.viewModel.getCurrentTheme(this.section.theme).table.dataTablePadding||0},getPreferredHeight:function(){var a=this.section.getInfographicWithTable();if(!a||!a.infographic.getPreferredHeight)return 0;var b=a.table.getTableBox(),c=b.t,b=this.getResizedHeight()-b.t-b.h,a=a.infographic.getPreferredHeight()||0;return c+b+a}});g.IMAGE_FIT_PRETTY_OFFSET=0;return g});