// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/_DDZoomAnimationSupport","dojo/_base/declare dojo/on dojo/keys dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style ./SimpleInfographicViewModes esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/animation/AnimationUtil esri/dijit/geoenrichment/utils/DelayUtil ../../../ReportPlayerState".split(" "),function(p,f,q,g,m,r,k,h,n,t,e,u,v){return p(null,
{_ddZoomScreen:null,_ddZoomScreenClass:null,_currentTriggerButtonBox:null,_closeZoomedDDWhenClickedOutside:!0,_showZoomTransition:function(c,d,a){function f(a){a?(n.show(b.dataDrillingViewDiv),b.dataDrillingViewDiv.parentNode!==document.body&&document.body.appendChild(b.dataDrillingViewDiv),b._getDDZoomViewZIndex()&&k.set(b.dataDrillingViewDiv,"zIndex",b._getDDZoomViewZIndex())):(b.dataDrillingViewDiv.parentNode===document.body&&document.body.removeChild(b.dataDrillingViewDiv),n.hide(b.dataDrillingViewDiv))}
function l(){var a=c!==h.VIEW_MAIN;f(a);b._setZoomScreen(a,!1);b._setCloseHandlers(a);v.isViewingDataDrillingZoom=a;b._mode=c;g[c===h.VIEW_DATA_DRILLING?"add":"remove"](b.domNode,"isDrillingData");g.remove(b.domNode,"isShowingAnimation");b.onViewModeChanged(c)}var b=this;if(this._mode!==c){this._currentTriggerButtonBox=a?r.position(a):this._currentTriggerButtonBox;g.add(this.domNode,"isShowingAnimation");g.add(this.dataDrillingViewDiv,"isZoomAnimation");if(d)return f(!0),d=c===h.VIEW_DATA_DRILLING,
a=this._getDataDrillingPanelDimensions(),k.set(this.dataDrillingViewDiv,{width:a.w+"px",height:a.h+"px"}),this._setZoomScreen(d,!0),d?(d=e.animateResize({duration:200,domNode:this.dataDrillingViewDiv,fromBox:this._currentTriggerButtonBox,startScaleX:.7,startScaleY:.7,fromOffset:{x:"c",y:"c"},toBox:{x:(document.body.clientWidth-a.w)/2,y:(document.body.clientHeight-a.h)/2,w:a.w,h:a.h},onEnd:l}),e.animateFadeIn({domNode:this.dataDrillingViewDiv,duration:100})):(d=e.animateResize({duration:200,domNode:this.dataDrillingViewDiv,
toBox:this._currentTriggerButtonBox,endScaleX:.7,endScaleY:.7,toOffset:{x:"c",y:"c"},onEnd:l}),e.animateFadeOut({domNode:this.dataDrillingViewDiv,duration:100})),d.then(function(){return u.delay(100)});l()}},_setZoomScreen:function(c,d){var a=this;c!==!!this._ddZoomScreen&&(c?(this._ddZoomScreen=m.create("div",{"class":"esriGEAbsoluteStretched simpleInfographic_dataDrillingViewDivScreen"},this.dataDrillingViewDiv,"before"),this._getDDZoomViewZIndex()&&k.set(this._ddZoomScreen,"zIndex",this._getDDZoomViewZIndex()),
this._ddZoomScreenClass&&g.add(this._ddZoomScreen,this._ddZoomScreenClass),d&&e.animateFadeIn({domNode:this._ddZoomScreen,duration:100})):(c=function(){a._ddZoomScreen&&m.destroy(a._ddZoomScreen);a._ddZoomScreen=null},d?e.animateFadeOut({domNode:this._ddZoomScreen,duration:100,onEnd:c}):c()))},_clickOutsideHandler:null,_keyboardHandler:null,_setCloseHandlers:function(c){var d=this;this._clickOutsideHandler&&this._clickOutsideHandler.remove();this._clickOutsideHandler=null;this._keyboardHandler&&this._keyboardHandler.remove();
this._keyboardHandler=null;c&&(this._closeZoomedDDWhenClickedOutside&&(this._clickOutsideHandler=f(document.body,"click",function(){t.isMouseOver(d.dataDrillingViewDiv,{checkAllChildren:!0})||d._setViewMode(h.VIEW_MAIN,!0)})),this._keyboardHandler=f(document.body,"keyup",function(a){a.keyCode===q.ESCAPE&&d._setViewMode(h.VIEW_MAIN,!0)}))},_getDDZoomViewZIndex:function(){return null}})});