// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/SimpleInfographic.html":'\x3cdiv class\x3d"esriGESimpleInfographic"\x3e\r\n    \r\n    \x3cdiv data-dojo-attach-point\x3d"mainViewDiv" class\x3d"esriGEAbsoluteStretched"\x3e\x3c/div\x3e\r\n\r\n    \x3cdiv data-dojo-attach-point\x3d"dataDrillingViewDiv" class\x3d"simpleInfographic_dataDrillingViewDiv"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"drilledDataViewDiv" class\x3d"esriGEAbsoluteStretched"\x3e\x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"topToolbar" class\x3d"simpleInfographic_topToolbar"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"drillingOptionsButton" class\x3d"dijitInline simpleInfographic_drillingOptionsButton"\x3e\x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"exportButton" class\x3d"dijitInline simpleInfographic_exportButton"\x3e\x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"printButton" class\x3d"dijitInline simpleInfographic_printButton"\x3e\x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"backToMainViewButton" class\x3d"dijitInline simpleInfographic_backToMainViewButton"\x3e\x3c/div\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\r\n\x3c/div\x3e\r\n\r\n\r\n'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/SimpleInfographic","dojo/_base/declare dojo/_base/lang dojo/dom-construct dojo/dom-style dijit/_WidgetBase dijit/_TemplatedMixin ./_DataDrillingSupport ./_DDSlideAnimationSupport ./_DDZoomAnimationSupport ./SimpleInfographicViewModes esri/dijit/geoenrichment/_Invoke ../utils/InfographicLayoutResizer ../utils/InfographicJsonConversionUtil ../utils/InfographicThemeUtil ../../supportClasses/TableUtil ../../sections/supportClasses/InfographicValueController ../dataDrilling/DataDrillingAnimationTypes esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes dojo/text!../../templates/SimpleInfographic.html".split(" "),
function(r,l,t,k,u,v,w,x,y,g,z,A,B,C,m,D,e,E,n,F){function p(a){return a&&a.shape&&a.shape.shapeJson.showAsBar}function q(a,b,c){return void 0===c?a===b:Number(Number(a).toFixed(c))===Number(Number(b).toFixed(c))}return r([u,v,z,w,x,y],{templateString:F,viewModel:null,theme:null,parentWidget:null,isEditMode:!1,adjustElementsWhenResized:!1,dataDrillingAnimationType:e.ZOOM,_sections:null,_currentInfographicJson:null,postCreate:function(){this.inherited(arguments);this._setViewMode(g.VIEW_MAIN)},_destroySections:function(){this._destroyDrillingSections();
this._destroyDrillingSectionsButtons();this._sections=this._sections||[];this._sections.forEach(function(a){a.destroy()});this._sections.length=0;this.domNode&&t.empty(this.mainViewDiv)},updateInfographic:function(a){this.domNode&&(this._currentInfographicJson=this._applyThemeToJson(a),this._doUpdateInfographic())},refresh:function(){this.updateInfographic(this._currentInfographicJson)},_doUpdateInfographic:function(){var a=this;if(this.domNode){this._destroySections();var b=this._currentInfographicJson;
this._syncJsonDimensions();var c=this.viewModel.getStaticInfographicDefaultStyles(this.theme);k.set(this.domNode,"backgroundColor",b.style.backgroundColor||c&&c.backgroundColor);k.set(this.domNode,{width:b.style.width+"px",height:b.style.height+"px"});this._preRender();this._renderHeader();this._renderVariableTables();this._sections.forEach(function(b){b.setViewMode(a.isEditMode?n.EDIT:n.PREVIEW_VALUES)});this._postRender()}},_syncJsonDimensions:function(){!(this._currentInfographicJson&&this.width&&
this.height)||q(this._currentInfographicJson.style.width,this.width,1)&&q(this._currentInfographicJson.style.height,this.height,1)||A.resizeLayout(this._currentInfographicJson,this.width,this.height,{preserveContentSizes:!this.adjustElementsWhenResized,usePrettyBox:!this.adjustElementsWhenResized,updateFontSize:this.adjustElementsWhenResized})},_infographicViewController:null,_preRender:function(){this._infographicViewController=new D;var a=this._currentInfographicJson.variableTables.filter(p);this._infographicViewController.setVariableTables(a)},
_renderHeader:function(){if(this._currentInfographicJson.header){var a=this._currentInfographicJson.header;this._createSection(m.getTableWidth(a),m.getTableHeight(a),[a],a.style,null,-1,null)}},_renderVariableTables:function(){var a=this;this._currentInfographicJson.variableTables.forEach(function(b,c){var f=B.variableTableToNormalTables(b);a._createSection(b.style.width,b.style.height,f.tableJsons,b.style,b,c,f)})},_prepareSectionCreationParams:function(a,b){return null},_createSection:function(a,
b,c,f,e,h,g){h=-1===h;var d={"class":"infographicContainer_Section"};d.initialWidth=a;d.json={type:E.DETAILS,stack:c};d.viewModel=this.viewModel;d.theme=this.theme;d.parentWidget=this;d.tableClass="infographicContainerTable";d.hasFixedLayout=!1;d.isInfographicSection=!0;d.isInfographicHeaderSection=h;d.infographicViewController=p(e)&&this._infographicViewController;l.mixin(d,this._prepareSectionCreationParams(e,h));a=this.viewModel.layoutBuilder.createElement("section",d,this.mainViewDiv);a.setResizedHeight(b);
k.set(a.domNode,{position:"absolute",left:(f.left||0)+"px",top:(f.spaceBefore||f.top||0)+"px"});this._sections.push(a);this.viewModel.dynamicReportInfo&&this.viewModel.enableDataDrilling&&g&&this._addDataDrillingHandlers(a,a.getTables()[g.variableIndex]);return a},_postRender:function(){},_mode:null,_setViewMode:function(a,b,c){switch(this.dataDrillingAnimationType){case e.SLIDE:return this._showSlideTransition(a,b);case e.ZOOM:return this._showZoomTransition(a,b,c)}},getVisualState:function(){return{dataDrilling:this._mode===
g.VIEW_DATA_DRILLING?this._getDataDrillingState():null}},setVisualState:function(a){a&&a.dataDrilling&&this._setDataDrillingState(a.dataDrilling)},_applyThemeToJson:function(a){var b=this.viewModel.getStaticInfographicDefaultStyles(this.theme);return C.applyThemeSettingsToJson(a,b)},notifyShown:function(){this._sections.forEach(function(a){a.notifyShown()})},width:null,height:null,resize:function(a,b){this.width&&this.height&&this._currentInfographicJson&&this._currentInfographicJson.style.width===
a&&this._currentInfographicJson.style.height===b||(this.width=a,this.height=b,this._syncJsonDimensions(),this.invoke("_doResize",50))},_doResize:function(){this._doUpdateInfographic()},toJson:function(){return l.clone(this._currentInfographicJson)},onViewModeChanged:function(a){},destroy:function(){this._destroySections();this.inherited(arguments)}})});