// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/DomUtil","dojo/_base/lang dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/string dojo/domReady!".split(" "),function(p,n,l,h,m,g,r){function q(){k||(k=h.create("div",{"class":"esriGEOffscreen"},document.body));return k}var f={isHidden:function(a){return a&&l.contains(a,"esriGEHidden")},hasVisibleChildren:function(a){if(!a||!a.children.length)return!1;for(var b=0;b<a.children.length;b++)if(!f.isHidden(a.children[b]))return!0;
return!1},hide:function(a){return f.addTag(a,"esriGEHidden")},show:function(a){return f.removeTag(a,"esriGEHidden")},addTag:function(a,b){return f.applyCallback(a,function(a){a&&l.add(a,b)})},removeTag:function(a,b){return f.applyCallback(a,function(a){a&&l.remove(a,b)})},applyCallback:function(a,b,c){c&&(b=p.hitch(c,b));Array.isArray(a)?a.forEach(b):b(a);return a},getChildIndex:function(a,b){if(!a||!a.children||!b)return-1;for(var c=0;c<a.children.length;c++)if(a.children[c]===b)return c;return-1},
getChildren:function(a){if(!a||!a.children)return null;for(var b=[],c=0;c<a.children.length;c++)b.push(a.children[c]);return b},getChildNodes:function(a){if(!a||!a.childNodes)return null;for(var b=[],c=0;c<a.childNodes.length;c++)b.push(a.childNodes[c]);return b},isChildOf:function(a,b,c){var d=!1,e=function(a){if(c&&!c(a))return!1;a.parentNode===b?d=!0:a.parentNode&&e(a.parentNode)};a&&e(a);return d},isNodeInLayout:function(a){return f.isChildOf(a,document.body,function(a){return!f.isHidden(a)&&
"none"!=g.get(a,"display")})},enableContent:function(a,b,c){if(a){c=c||{};var d=a.children.length-1;if(!(0>d)){d=a.children[d];l.contains(d,"esriGEDisabledContent")||(d=null);if(b)d&&a.removeChild(d);else if(d=d||h.create("div",{"class":"esriGEDisabledContent"+(c.overlayClass?" "+c.overlayClass:"")},a),!1!==c.fitParent&&(a=m[c.marginBox?"getMarginBox":"getContentBox"](a).h))a=a.toString()+"px",g.set(d,{height:a,marginTop:"-"+a});return d}}},enableContentAbsolute:function(a,b,c){if(a){c=c||{};var d=
g.get(a,"position");"relative"!==d&&"absolute"!==d&&g.set(a,"position","relative");return f.enableContent(a,b,{overlayClass:"esriGEAbsoluteStretched "+(c.overlayClass||"")+(c.isTransparent?" esriGEDisabledContentTransparent ":""),fitParent:!1})}}},k;f.hideNodeInBackground=function(a,b){if(a){if(a._hideNodeInBackgroundUndoController)return a._hideNodeInBackgroundUndoController;var c=h.create("div",null,a,"after"),d=h.create("div",{style:"position: absolute; left: 0px; top: 0px;"},q());h.place(a,d);
b="DomUtil.hideNodeInBackground"+(b?"."+b:"");n.set(c,"_bg_memo_node",b);n.set(d,"_bg_temp_node",b);b={undo:function(){c&&(c.parentNode&&h.place(a,c,"replace"),h.destroy(c),h.destroy(d),k.children.length||(h.destroy(k),k=null),c=null,delete a._hideNodeInBackgroundUndoController)},remove:function(){this.undo()}};return a._hideNodeInBackgroundUndoController=b}};f.showNodeFromBackground=function(a){a&&a._hideNodeInBackgroundUndoController&&a._hideNodeInBackgroundUndoController.undo()};f.position=function(a){function b(a){for(var b=
{x:0,y:0};a.offsetParent;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent,b.x+=g.get(a,"borderLeftWidth"),b.y+=g.get(a,"borderTopWidth");return b}function c(a){return g.get(a,"width")+g.get(a,"paddingLeft")+g.get(a,"paddingRight")+g.get(a,"borderLeftWidth")+g.get(a,"borderRightWidth")}function d(a){return g.get(a,"height")+g.get(a,"paddingTop")+g.get(a,"paddingBottom")+g.get(a,"borderTopWidth")+g.get(a,"borderBottomWidth")}if(a){var e;if(a instanceof SVGElement&&a.getBBox)return e=(e=a.ownerSVGElement&&
a.ownerSVGElement.parentNode)&&b(e),a=a.getBBox(),{x:(a.x||0)+e.x,y:(a.y||0)+e.y,w:a.width||0,h:a.height||0};e=b(a);return{x:e.x,y:e.y,w:c(a),h:d(a)}}};f.intersectNodeBoxes=function(a,b){var c=1E6,d=1E6,e=-1E6,g=-1E6;a.forEach(function(a){a=f.position(a);c=Math.min(c,a.x);d=Math.min(d,a.y);e=Math.max(e,a.x+a.w);g=Math.max(g,a.y+a.h)});a={x:c,y:d,w:e-c,h:g-d};b&&(b=f.position(b),a.x-=b.x,a.y-=b.y);return a};f.getNodesBox=function(a){var b=1E6,c=-1E6,d=1E6,e=-1E6;a.forEach(function(a){a=m.position(a);
b=Math.min(b,a.x);d=Math.min(d,a.y);c=Math.max(c,a.x+a.w);e=Math.max(e,a.y+a.h)});return{x:b,y:d,w:c-b,h:e-d}};f.traverseChildren=function(a,b){function c(a){if(a&&a.children)for(var d=0;d<a.children.length;d++){var f=a.children[d];if(b(f))break;c(f)}}c(a)};f.scrollToListNode=function(a,b,c){var d=b.offsetTop+b.clientHeight,e=d-(a.scrollTop+a.clientHeight);0<e&&(a.scrollTop+=e);c&&(d-=b.clientHeight-c.offsetTop,e=a.scrollTop-d,0<e&&(a.scrollTop-=e))};f.getMeasureContext=function(a){a=a||{};a.style=
a.style?a.style+" ":"";a.style+="display: inline-block; position: absolute; left: 0; top: 0;";return{div:h.create("div",a,document.body),measureText:function(a){this.div.innerHTML=a;a=m.getMarginBox(this.div);delete a.l;delete a.t;return a},destroy:function(){h.destroy(this.div)}}};f.getTextBox=function(a,b){b=f.getMeasureContext(b);a=b.measureText(a);b.destroy();return a};return f});