// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/ShapeUtil",["dojo/dom-style","dojo/_base/lang","esri/dijit/geoenrichment/utils/ColorUtil"],function(k,l,h){var e={createSVGNode:function(a,c){var b=document.createElementNS("http://www.w3.org/2000/svg","svg");c&&k.set(b,c);a=[a.xmin||0,a.ymin||0,a.width,a.height].join(" ");b.setAttribute("viewBox",a);b.setAttribute("xmlns","http://www.w3.org/2000/svg");return b},createPathNode:function(a,c){var b=document.createElementNS("http://www.w3.org/2000/svg","path");
b.setAttribute("d",a);e._setSettingsToNode(b,c);return b},createEllipseNode:function(a,c,b,f,g){var d=document.createElementNS("http://www.w3.org/2000/svg","ellipse");d.setAttribute("cx",a||0);d.setAttribute("cy",c||0);d.setAttribute("rx",b);d.setAttribute("ry",f);e._setSettingsToNode(d,g);return d},createCircleNode:function(a,c,b,f){var g=document.createElementNS("http://www.w3.org/2000/svg","circle");g.setAttribute("cx",a||0);g.setAttribute("cy",c||0);g.setAttribute("r",b);e._setSettingsToNode(g,
f);return g},createRectNode:function(a,c,b,f,g){var d=document.createElementNS("http://www.w3.org/2000/svg","rect");d.setAttribute("x",a||0);d.setAttribute("y",c||0);d.setAttribute("width",b);d.setAttribute("height",f);e._setSettingsToNode(d,g);return d},createLineNode:function(a,c,b,f,g){var d=document.createElementNS("http://www.w3.org/2000/svg","line");d.setAttribute("x1",a||0);d.setAttribute("y1",c||0);d.setAttribute("x2",b||0);d.setAttribute("y2",f||0);e._setSettingsToNode(d,g);return d},createPolygonNode:function(a,
c){var b=document.createElementNS("http://www.w3.org/2000/svg","polygon");b.setAttribute("points",a);e._setSettingsToNode(b,c);return b},createNodeByAttributes:function(a,c){var b=null;switch(a.name){case "path":b=e.createPathNode(a.d,c);break;case "ellipse":b=e.createEllipseNode(a.cx,a.cy,a.rx,a.ry,c);break;case "circle":b=e.createCircleNode(a.cx,a.cy,a.r,c);break;case "rect":b=e.createRectNode(a.x,a.y,a.width,a.height,c);break;case "line":b=e.createLineNode(a.x1,a.y1,a.x2,a.y2,c);break;case "polygon":b=
e.createPolygonNode(a.points,c)}b&&(a=a["fill-opacity"],void 0!==a&&(b.hasAttribute("fill-opacity")&&(a*=b.getAttribute("fill-opacity")),b.setAttribute("fill-opacity",a)));return b},_setSettingsToNode:function(a,c){if(c.borderWidth){var b=e.toColor(c,"border","#000000");a.setAttribute("stroke",h.toCSSColor(b,!0));a.setAttribute("stroke-width",c.borderWidth);a.setAttribute("stroke-opacity",b.a);c.borderDashArray&&a.setAttribute("stroke-dasharray",Array.isArray(c.borderDashArray)?c.borderDashArray.join(","):
c.borderDashArray);c.strokeMiterLimit&&a.setAttribute("stroke-miterlimit",c.strokeMiterLimit);c.borderScale||a.setAttribute("vector-effect","non-scaling-stroke")}c.fillColor&&(b=e.toColor(c,"fill","#FFFFFF"),a.setAttribute("fill",h.toCSSColor(b,!0)),a.setAttribute("fill-opacity",b.a))},toColor:function(a,c,b,e){b=h.toColor(a[c+"Color"],b);1===b.a&&(a=a[c+"Alpha"],isNaN(a)&&(a=e),isNaN(a)||(b.a=a));return b},createSVGfromJson:function(a,c,b,f){f=l.mixin({},m,f);void 0===f.borderColor&&(f.borderColor=
f.fillColor);var g=e.createSVGNode(a.viewBox,{width:c+"px",height:b+"px",overflow:"visible"});a.g.forEach(function(a){g.appendChild(e.createNodeByAttributes(a,f))});return g}},m={fillColor:"#FFFFFF",fillAlpha:1,borderAlpha:0,borderWidth:1};return e});