// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/TooltipUtil","dojo/dom-class dojo/dom-geometry dojo/aspect dojo/on dojo/mouse dojo/sniff dijit/Tooltip ./DomUtil ./MouseUtil dojo/domReady!".split(" "),function(n,k,u,l,p,q,m,t,r){var f={};m.show("",document.body);m.hide(document.body);var b=dijit.byId("dijit__MasterTooltip_0");b.addCustomClasses=function(a){b.removeCustomClasses();a&&(n.add(b.domNode,a),b._customClasses=a)};b.removeCustomClasses=function(){b._customClasses&&n.remove(b.domNode,b._customClasses);
delete b._customClasses};b.orient=function(a,e,d,h,f){b.connectorNode.style.top="";var c=h.h;h=h.w;a.className="dijitTooltip "+{"MR-ML":"dijitTooltipRight","ML-MR":"dijitTooltipLeft","TM-BM":"dijitTooltipAbove","BM-TM":"dijitTooltipBelow","BL-TL":"dijitTooltipBelow dijitTooltipABLeft","TL-BL":"dijitTooltipAbove dijitTooltipABLeft","BR-TR":"dijitTooltipBelow dijitTooltipABRight","TR-BR":"dijitTooltipAbove dijitTooltipABRight","BR-BL":"dijitTooltipRight","BL-BR":"dijitTooltipLeft"}[e+"-"+d];b.addCustomClasses(b._customClasses);
b.domNode.style.width="auto";var g=k.position(b.domNode);if(q("ie")||q("trident"))g.w+=2;k.setMarginBox(b.domNode,{w:Math.min(Math.max(h,1),g.w)});"B"==d.charAt(0)&&"B"==e.charAt(0)?(a=k.position(a),e=b.connectorNode.offsetHeight,a.h>c?(b.connectorNode.style.top=c-(f.h+e>>1)+"px",b.connectorNode.style.bottom=""):(b.connectorNode.style.bottom=Math.min(Math.max(f.h/2-e/2,0),a.h-e)+"px",b.connectorNode.style.top="")):(b.connectorNode.style.top="",b.connectorNode.style.bottom="");return Math.max(0,g.w-
h)};f.hideTooltipForNode=function(a){a&&(a.__setTooltipToNodeMouseLeaveHandle&&a.__setTooltipToNodeMouseLeaveHandle.remove(),clearInterval(a.__setTooltipToNodeInLayoutHandle),clearInterval(a.__setTooltipToNodeMouseOverHandle),a.__setTooltipToNodeClickHandle&&a.__setTooltipToNodeClickHandle.remove(),a.__setTooltipToNodeMouseLeaveMasterHandle&&a.__setTooltipToNodeMouseLeaveMasterHandle.remove(),n.remove(a,"esriMapsAnalystSimpleTextTooltip"),m.hide(a))};f.setTooltipToNode=function(a,e,d){if(a){d=d||
{};var c=Array.isArray(d.classes)?d.classes.join(" "):d.classes,c=(c||"")+" esriGETooltip";a.__setTooltipToNodeClasses=c;f.hideTooltipForNode(a);delete a.title;a.__setTooltipToNodeMouseEnterHandle&&a.__setTooltipToNodeMouseEnterHandle.remove();if(e)return a.__setTooltipToNodeMouseEnterHandle=l(a,p.enter,function(){function h(){b.addCustomClasses(c);m.show(k,a,d.position||["after","before"])}a.__setTooltipToNodeMouseLeaveHandle&&a.__setTooltipToNodeMouseLeaveHandle.remove();clearInterval(a.__setTooltipToNodeInLayoutHandle);
clearInterval(a.__setTooltipToNodeMouseOverHandle);a.__setTooltipToNodeClickHandle&&a.__setTooltipToNodeClickHandle.remove();a.__setTooltipToNodeMouseLeaveMasterHandle&&a.__setTooltipToNodeMouseLeaveMasterHandle.remove();n.add(a,"esriMapsAnalystSimpleTextTooltip");var k="function"==typeof e?e():e;if(k){h();var g=f.hideTooltipForNode.bind(f,a);a.__setTooltipToNodeMouseLeaveHandle=l.once(a,p.leave,function(){!d.stayOnHover&&g()});d.ignoreNodeRemoval||(a.__setTooltipToNodeInLayoutHandle=setInterval(function(){!t.isNodeInLayout(a)&&
g()},300));a.__setTooltipToNodeMouseOverHandle=setInterval(function(){d.stayOnHover&&r.isMouseOver(b.domNode)||r.isMouseOver(a)||g()},300);a.__setTooltipToNodeClickHandle=l(a,"click",function(a){a.stopPropagation();d.hideOnClick?g():h()});d.stayOnHover&&(a.__setTooltipToNodeMouseLeaveMasterHandle=l(b.domNode,p.leave,g))}}),{remove:function(){e=null;f.hideTooltipForNode(a)}}}};var c=null;f.autoTooltip=function(a){l(a,".TrimWithEllipses:mouseover",function(){this!==c&&this.offsetWidth<this.scrollWidth&&
(c=this,m.show(c.textContent,c,["above","below"]),l.once(c,"mouseout, mousedown, touchstart",function(){m.hide(c);c=null}))})};return f});