// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/templates/NumericalSlider.html":'\x3cdiv class\x3d"esriGENumericalSlider"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"divLabel" class\x3d"esriGENumericalSliderLabel"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"divChartContainer" class\x3d"esriGENumericalSliderContent"\x3e\r\n        \x3cdiv class\x3d"esriGENumericalSliderMinValueTextBox" data-dojo-attach-point\x3d"divMinValue"\x3e\x3c/div\x3e\r\n        \x3cdiv  class\x3d"esriGENumericalSliderContainer"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"divSliderContainer"\x3e\x3c/div\x3e\r\n        \x3c/div\x3e \r\n        \x3cdiv class\x3d"esriGENumericalSliderMaxValueTextBox" data-dojo-attach-point\x3d"divMaxValue"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/NumericalSlider","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/on dojox/timing dojo/Evented dijit/_WidgetBase dijit/_TemplatedMixin dojox/form/HorizontalRangeSlider dijit/form/TextBox esri/dijit/geoenrichment/utils/DomUtil dojo/text!./templates/NumericalSlider.html".split(" "),function(e,g,h,d,k,l,m,n,p,f,q,r){return e([m,n,l],{templateString:r,lowerValue:3,upperValue:7,decimals:0,minValue:null,maxValue:null,timeIntervalLength:null,_timer:null,_root:null,
constructor:function(a){a&&this.setData(a)},buildRendering:function(){var a=this;this.inherited(arguments);this._rangeSlider=new (e(this._getSliderClass(),{postMixInProperties:function(){var a=this.value.slice();this.inherited(arguments);this.value=a.map(function(a){return parseFloat(a)})}}))({name:"rangeSlider",value:["rtl"===document.dir?this.upperValue:this.lowerValue,"rtl"===document.dir?this.lowerValue:this.upperValue],minimum:parseFloat(this.minValue),maximum:parseFloat(this.maxValue),showButtons:!1,
intermediateChanges:!0,onChange:this._onChangeValue.bind(this)},this.divSliderContainer);this.own(this._rangeSlider);h.add(this._rangeSlider.sliderHandle,"esriGENumericalSliderMinThumb");this.label?this.divLabel.innerHTML=this.label:q.hide(this.divLabel);this._createMinTextBox();this._createMaxTextBox();this._setMinValue(this.numberToText(this._rangeSlider.value["rtl"===document.dir?1:0]));this._setMaxValue(this.numberToText(this._rangeSlider.value["rtl"===document.dir?0:1]));d(this.tbxMinValue,"mouseup, click",
function(b){a.tbxMinValue.textbox.select()});d(this.tbxMaxValue,"mouseup, click",function(b){a.tbxMaxValue.textbox.select()})},_getSliderClass:function(){return p},_createMinTextBox:function(){var a=this;this.tbxMinValue=(new f).placeAt(this.divMinValue);d(this.tbxMinValue.textbox,"keyup",function(b){13===b.keyCode&&a._onChangeMinValue()});this.own(this.tbxMinValue)},_createMaxTextBox:function(){var a=this;this.tbxMaxValue=(new f).placeAt(this.divMaxValue);d(this.tbxMaxValue.textbox,"keyup",function(b){13===
b.keyCode&&a._onChangeMaxValue()});this.own(this.tbxMaxValue)},setData:function(a){a.timeIntervalLength&&(a.timeIntervalLength=parseInt(a.timeIntervalLength),this._timer=new k.Timer,this._timer.onTick=this._onTick.bind(this));a.minValue?a.minValue=parseFloat(a.minValue):a.dataArray&&(a.minValue=Math.min.apply(null,a.dataArray));a.maxValue?a.maxValue=parseFloat(a.maxValue):a.dataArray&&(a.maxValue=Math.max.apply(null,a.dataArray));parseFloat(a.lowerValue)&&0!==a.lowerValue||(a.lowerValue=a.minValue);
parseFloat(a.upperValue)&&0!==a.upperValue||(a.upperValue=a.maxValue);g.mixin(this,a)},setValue:function(a){var b="rtl"===document.dir?1:0,c="rtl"===document.dir?0:1;this.lowerValue=a[b];this.upperValue=a[c];this._setMinValue(this.numberToText(a[b]));this._setMaxValue(this.numberToText(a[c]));this._rangeSlider.value=a;this._rangeSlider._printSliderBar(!0,!1)},_setMinValue:function(a){this.tbxMinValue.set("value",a);this.tbxMinValue.textbox.title=a},_setMaxValue:function(a){this.tbxMaxValue.set("value",
a);this.tbxMaxValue.textbox.title=a},_emitChangeEvent:function(){this._timer?(this._timer.stop(),this._timer.setInterval(this.timeIntervalLength),this._timer.start()):this._onTick()},_onTick:function(){var a={lowerValue:this.lowerValue,upperValue:this.upperValue};this._timer&&this._timer.stop();this.onChange(a)},_onChangeValue:function(a){var b="rtl"===document.dir?1:0,c="rtl"===document.dir?0:1;this._setMinValue(this.numberToText(a[b]));this._setMaxValue(this.numberToText(a[c]));this.lowerValue=
a[b];this.upperValue=a[c];this._emitChangeEvent()},_onChangeMinValue:function(a){a=this.tbxMinValue.get("value");a=this.textToNumber?this.textToNumber(a):parseFloat(a);a=Math.min(this.maxValue,Math.max(this.minValue,a));isNaN(a)||(this.lowerValue=a,this.upperValue=a<=this.upperValue?this.upperValue:a,this.setValue([this.lowerValue,this.upperValue]),this._emitChangeEvent(),this._setMaxValue(this.numberToText(this.upperValue)));this._setMinValue(this.numberToText(this.lowerValue))},_onChangeMaxValue:function(a){a=
this.tbxMaxValue.get("value");a=this.textToNumber?this.textToNumber(a):parseFloat(a);a=Math.min(this.maxValue,Math.max(this.minValue,a));isNaN(a)||(this.lowerValue=a>=this.lowerValue?this.lowerValue:a,this.upperValue=a,this.setValue([this.lowerValue,this.upperValue]),this.upperValue=a,this._emitChangeEvent(),this._setMinValue(this.numberToText(this.lowerValue)));this._setMaxValue(this.numberToText(this.upperValue))},numberToText:function(a){return a.toFixed(this.decimals)},textToNumber:function(a){return parseFloat(a)},
round:function(a){return this.textToNumber(this.numberToText(a))},onChange:function(a){}})});