// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/utils/InfographicLayoutResizer",["dojo/_base/lang","../../supportClasses/TableUtil","esri/dijit/geoenrichment/utils/ObjectUtil"],function(v,w,x){function r(a){var b={l:1E6,t:1E6,w:0,h:0};a.forEach(function(a){b.l=Math.min(b.l,a.left);b.t=Math.min(b.t,a.top);b.w=Math.max(b.w,a.left+a.width);b.h=Math.max(b.h,a.top+a.height)});b.w-=b.l;b.h-=b.t;return b}function t(a){var b=[];u.forEach(function(c){a[c]&&b.push(a[c].style)});return b}function y(a,
b,c,g){g=g||{};u.forEach(function(f){var e=a[f]&&a[f].style;if(e)if(g.preserveContentSizes){var h=e.left+e.width/2,l=e.top+e.height/2,h=h*b,l=l*c;e.left=h-e.width/2;e.top=l-e.height/2}else h=function(){var b=a[f].themeStyle;return e.fontSize||b&&b.fontSize},l=h()?h()/e.height:1,e.left*=b,e.width*=b,e.top*=c,e.height*=c,g.updateFontSize&&("description"===f||"variable"===f)&&h()&&(e.fontSize=x.roundNumber(l*e.height,2))})}var k={getContentDim:function(a){var b=a.header?w.getTableHeight(a.header)+(a.header.style.spaceBefore||
0):5,c={w:a.style.width,h:a.style.height-b,t:b,l:0},g={minW:"number"===typeof a.style.minWidth?a.style.minWidth:50,maxW:"number"===typeof a.style.maxWidth?a.style.maxWidth:1E6,minH:"number"===typeof a.style.minHeight?a.style.minHeight:50,maxH:"number"===typeof a.style.maxHeight?a.style.maxHeight:1E6},f={};f.w=Math.max(g.minW,Math.min(g.maxW,c.w));f.h=Math.max(g.minH,Math.min(g.maxH,c.h));f.l=Math.max(0,(c.w-f.w)/2);f.t=b+Math.max(0,(c.h-f.h)/2);c.prettyfiedBox=f;c.prettyBoxConstraints=g;c.hasHeader=
!!a.header;if(a.variableTables){var e=[];a.variableTables.forEach(function(a){t(a).forEach(function(b){b=v.mixin({},b);b.left+=a.style.left;b.top+=a.style.top;e.push(b)})});c.innerBox=r(e)}return c},resizeLayout:function(a,b,c,g){var f=k.getContentDim(a);a.style.width=b;a.style.height=c;a.header&&(a.header.style.width=a.style.width,a.header.data.columns[0].style.width="100%");a.variableTables&&a.variableTables.length&&k._resizeVariableTables(a,f,g)},_resizeVariableTables:function(a,b,c){function g(b,
c){a.variableTables.forEach(function(a){a.style.left*=b;a.style.top=(a.style.top-r)*c+r;k.resizeVariableTable(a,a.style.width*b,a.style.height*c,{preserveContentSizes:e,updateFontSize:l})})}function f(b,c){a.variableTables.forEach(function(a){a.style.left+=b;a.style.top+=c})}c=c||{};var e=void 0!==c.preserveContentSizes?c.preserveContentSizes:!0,h=void 0!==c.usePrettyBox?c.usePrettyBox:!0,l=c.updateFontSize,d=k.getContentDim(a),r=d.t,m,n,p,q;n=m=1;q=p=0;h&&d.w>d.prettyBoxConstraints.maxW?p=(d.w-b.w)/
2:m=d.w/b.w;h&&d.h>d.prettyBoxConstraints.maxH?q=(d.h-b.h)/2:n=d.h/b.h;g(m,n);f(p,q);if(h){d=k.getContentDim(a);n=m=1;q=p=0;if(d.innerBox.w<d.prettyBoxConstraints.minW||d.innerBox.w>d.prettyBoxConstraints.maxW)m=d.prettyfiedBox.w/d.innerBox.w,p=d.prettyfiedBox.l-d.innerBox.l;if(d.innerBox.h<d.prettyBoxConstraints.minH||d.innerBox.h>d.prettyBoxConstraints.maxH)n=d.prettyfiedBox.h/d.innerBox.h,q=d.prettyfiedBox.t-d.innerBox.t;g(m,n);f(p,q)}c.headerChanged&&(c.headerPreChangeDim.hasHeader?f(0,-(c.headerPreChangeDim.t-
d.t)):f(0,d.t-c.headerPreChangeDim.t),g(1,d.h/c.headerPreChangeDim.h))}},u=["shape","image","variable","description"];k.getVariableTableContentDim=function(a){return r(t(a))};k.resizeVariableTable=function(a,b,c,g){b=b||a.style.width;c=c||a.style.height;var f=b/a.style.width||1,e=c/a.style.height||1;a.style.width=b;a.style.height=c;y(a,f,e,g)};return k});