// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/templates/PlayerToolbarHolder.html":'\x3cdiv class\x3d"esriGEPlayerToolbar"\x3e\r\n\r\n    \x3c!--left--\x3e\r\n\r\n    \x3cdiv data-dojo-attach-point\x3d"infographicsSelectDiv" class\x3d"dijitInline playerToolbar_infographicsSelectDiv"\x3e\x3c/div\x3e\r\n    \r\n    \x3c!--center--\x3e\r\n    \r\n    \x3cdiv data-dojo-attach-point\x3d"areaTitleDiv" class\x3d"dijitInline playerToolbar_areaTitleDiv"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"areaTitleInnerDiv" class\x3d"dijitInline playerToolbar_areaTitleInnerDiv TrimWithEllipses"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\r\n    \x3cdiv data-dojo-attach-point\x3d"areasSelectDiv" class\x3d"dijitInline playerToolbar_areasSelectDiv"\x3e\x3c/div\x3e\r\n\r\n    \x3c!--right--\x3e\r\n\r\n    \x3cdiv data-dojo-attach-point\x3d"rightSideControlsBlock" class\x3d"dijitInline playerToolbar_rightSideControlsBlock"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"zoomSelectDiv" class\x3d"dijitInline dijitInline playerToolbar_zoomSelectDiv"\x3e\x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"pageSelectDiv" class\x3d"dijitInline dijitInline playerToolbar_pageSelectDiv"\x3e\x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"commandButtonsContainer" class\x3d"dijitInline playerToolbar_commandButtonsContainer"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/PlayerToolbar","dojo/_base/declare dojo/on dojo/string dojo/dom-class dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin ./PlayerSelect ./PlayerCommands ./PlayerThemes ./supportClasses/ToolbarArranger esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/PopupUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/text!./templates/PlayerToolbarHolder.html dojo/i18n!esri/nls/jsapi".split(" "),
function(l,m,n,g,c,p,q,h,r,v,w,f,x,k,t,y,d){function z(a){var b=[];u.forEach(function(e){"number"===typeof e.value&&b.push({value:e.value,score:a<e.value?a/e.value:e.value/a})});b.sort(function(a,b){return b.score-a.score});return b[0].value}d=d.geoenrichment.dijit.ReportPlayer.PlayerToolbar;var u=[{value:"fitPage",label:d.fitPage},{value:"fitPageWidth",label:d.fitPageWidth},{value:150,label:"150%"},{value:125,label:"125%"},{value:100,label:"100%"},{value:90,label:"90%"},{value:80,label:"80%"},{value:70,
label:"70%"},{value:60,label:"60%"},{value:50,label:"50%"}],A=l([p,q],{templateString:y,nls:d,formatAreaTitleFunc:null,showAreaTitle:!1,stretchToolbarNode:null,areasSelect:null,pageSelect:null,zoomSelect:null,_toolbarArranger:null,postCreate:function(){f.hide(this.commandButtonsContainer);this._toolbarArranger=new w({showAreaTitle:this.showAreaTitle,stretchToolbarNode:this.stretchToolbarNode,domNode:this.domNode,infographicsSelectDiv:this.infographicsSelectDiv,areaTitleDiv:this.areaTitleDiv,areaTitleInnerDiv:this.areaTitleInnerDiv,
rightSideControlsBlock:this.rightSideControlsBlock,areasSelectDiv:this.areasSelectDiv,zoomSelectDiv:this.zoomSelectDiv,pageSelectDiv:this.pageSelectDiv,commandButtonsContainer:this.commandButtonsContainer});this._initAreaSelect();this._initPageSelect();this._initZoomSelect()},_initAreaSelect:function(){var a=this;this.areasSelect=(new h({onChange:function(b){a.onShowAnalysisAreaAt(b.value)}})).placeAt(this.areasSelectDiv);this.own(this.areasSelect)},updateAreaSelect:function(a,b){var e=a.length,c=
a.map(function(a,b){return{label:1===e?a.name||a.shortName:a.shortName||a.name||n.substitute(d.areaIndex,{index:b+1}),value:b}});this.areasSelect.set("options",c);this.areasSelect.set("value",b);f[1<e?"show":"hide"](this.areasSelectDiv);a=a[b];this.formatAreaTitleFunc?this.formatAreaTitleFunc(this.areaTitleInnerDiv,a):this._formatAreaTitle(a)},_formatAreaTitle:function(a){this.areaTitleInnerDiv.innerHTML=a.name||a.shortName||""},_pageControlsVisible:!0,_initPageSelect:function(){var a=this;this.pageSelect=
(new h({onChange:function(b){a.onShowPageAt(b.value)}})).placeAt(this.pageSelectDiv);this.own(this.pageSelect)},setPageControlsVisible:function(a){this._pageControlsVisible=a;f[a?"show":"hide"](this.pageSelectDiv)},updatePageSelect:function(a,b){for(var e=[],c=0;c<a;c++)e.push({label:n.substitute(d.pageIndex,{index:c+1}),value:c});this.pageSelect.set("options",e);this.pageSelect.set("value",b);f[this._pageControlsVisible&&1<a?"show":"hide"](this.pageSelectDiv)},_initZoomSelect:function(){var a=this;
this.zoomSelect=(new h({onChange:function(b){if("fitPage"===b.value)a.onZoomToFitPage();else if("fitPageWidth"===b.value)a.onZoomToFitPageWidth();else a.onSetZoomPercent(b.value)}})).placeAt(this.zoomSelectDiv);this.own(this.zoomSelect);this.zoomSelect.set("options",u);this.zoomSelect.set("value",100)},setZoomSupportsInfo:function(a){f[a.supported?"show":"hide"](this.zoomSelectDiv);this.zoomSelect.store.data.forEach(function(b){b.hidden="fitPage"===b.value&&!a.canFitPage||"fitPageWidth"===b.value&&
!a.canFitPageWidth})},setZoomInfo:function(a){a=a.isFitPageScale?"fitPage":a.isFitPageWidthScale?"fitPageWidth":z(100*a.scale);a!==this.zoomSelect.get("value")&&this.zoomSelect.set("value",a)},createCommandButton:function(a,b){return this.createCustomCommandButton({callback:b,buttonClass:a.id===r.PRINT?"playerPrintButton":"playerExportButton",tooltip:a.id===r.PRINT?d.printInfographic:d.exportInfographic,visibleOnError:!1})},createCustomCommandButton:function(a){f.show(this.commandButtonsContainer);
var b=c.create("div",{"class":"playerToolbar_commandButtonContainer dijitInline"},this.commandButtonsContainer,a.addFirst?"first":"last");b.__visibleOnError=a.visibleOnError;b=c.create("div",{"class":"playerToolbar_commandButton"},b);a.buttonClass&&g.add(b,a.buttonClass);a.tooltip&&t.setTooltipToNode(b,a.tooltip);m(b,"click",a.callback);return b},setTheme:function(a){g.remove(this.domNode,"playerThemeDark playerThemeLight");g.add(this.domNode,a===v.DARK?"playerThemeDark":"playerThemeLight");this.areasSelect.setTheme(a);
this.pageSelect.setTheme(a);this.zoomSelect.setTheme(a)},setErrorShown:function(a){if(a){f.hide([this.areaTitleDiv,this.areasSelectDiv,this.pageSelectDiv,this.zoomSelectDiv]);for(a=0;a<this.commandButtonsContainer.children.length;a++){var b=this.commandButtonsContainer.children[a];f[b.__visibleOnError?"show":"hide"](b)}this.arrangeControls()}},arrangeControls:function(){this._toolbarArranger.arrangeControls()},hasVisibleControls:function(){return this._toolbarArranger.hasVisibleControls()},onShowPageAt:function(a){},
onShowAnalysisAreaAt:function(a){},onZoomToFitPage:function(){},onZoomToFitPageWidth:function(){},onSetZoomPercent:function(a){}});return l([p,q],{templateString:"\x3cdiv class\x3d'esriGEPlayerToolbarOuter'\x3e\x3c/div\x3e",popupButtonDiv:null,formatAreaTitleFunc:null,showToolbarInPopup:!1,showAreaTitle:!1,stretchToolbarNode:null,isMobileDevice:!1,showCloseButton:!1,toolbarHolder:null,postCreate:function(){var a=this;this.inherited(arguments);this.toolbarHolder=(new A({showAreaTitle:this.showAreaTitle,
stretchToolbarNode:this.stretchToolbarNode,onShowPageAt:function(b){a.onShowPageAt(b)},onShowAnalysisAreaAt:function(b){a.onShowAnalysisAreaAt(b)},onZoomToFitPage:function(){a.onZoomToFitPage()},onZoomToFitPageWidth:function(){a.onZoomToFitPageWidth()},onSetZoomPercent:function(b){a.onSetZoomPercent(b)}})).placeAt(this.domNode);this.own(this.toolbarHolder)},updateAreaSelect:function(a,b){this.toolbarHolder.formatAreaTitleFunc=this.formatAreaTitleFunc;this.toolbarHolder.updateAreaSelect(a,b)},setPageControlsVisible:function(a){this.toolbarHolder.setPageControlsVisible(a)},
updatePageSelect:function(a,b){this.toolbarHolder.updatePageSelect(a,b)},setZoomSupportsInfo:function(a){this.toolbarHolder.setZoomSupportsInfo(a)},setZoomInfo:function(a){this.toolbarHolder.setZoomInfo(a)},createCommandButton:function(a,b){return this.toolbarHolder.createCommandButton(a,b)},setTheme:function(a){this.toolbarHolder.setTheme(a)},setErrorShown:function(a){this.toolbarHolder.setErrorShown(a)},_popupHandle:null,_popupButton:null,update:function(){x.invoke(this,"_doUpdateToolbar")},_doUpdateToolbar:function(){g[this.isScrollShown()?
"add":"remove"](this.popupButtonDiv,"playerToolbar_parentHasScroll");g[this.isMobileDevice?"add":"remove"](this.popupButtonDiv,"isMobileDevice");g[this.isMobileDevice?"add":"remove"](this.toolbarHolder.domNode,"isMobileDevice");this._resetToolbarNode();var a=k.isOpen(this.toolbarHolder);this._popupHandle&&this._popupHandle.remove();this._popupHandle=null;this.showToolbarInPopup?(this._popupButton=c.create("div",{"class":"dijitInline playerToolbar_outerButton playerToolbar_settingsButton"},this.popupButtonDiv,
"first"),this._popupHandle=k.makePopup(this.toolbarHolder,this,this._popupButton,{orient:["before","below"],openPopup:a})):c.place(this.toolbarHolder.domNode,this.domNode);this.toolbarHolder.arrangeControls();f[this.toolbarHolder.hasVisibleControls()?"show":"hide"](this.domNode)},_resetToolbarNode:function(){this.toolbarHolder.domNode.parentNode&&this.toolbarHolder.domNode.parentNode.removeChild(this.toolbarHolder.domNode);c.empty(this.domNode);this._popupButton&&c.destroy(this._popupButton);this._popupButton=
null},closePopup:function(){k.close(this.toolbarHolder)},isScrollShown:function(){return!1},placeInfographicsSelect:function(a){a.placeAt(this.toolbarHolder.infographicsSelectDiv)},createCustomCommandButton:function(a){return this.toolbarHolder.createCustomCommandButton(a)},notifyCommandButtonsAdded:function(){if(this.showCloseButton)if(this.showToolbarInPopup){var a=c.create("div",{"class":"dijitInline playerToolbar_outerButton playerToolbar_closeButtonOuter"},this.popupButtonDiv);t.setTooltipToNode(a,
d.close);m(a,"click",function(){this.onClose()}.bind(this))}else this.createCustomCommandButton({buttonClass:"playerToolbar_closeButton",tooltip:d.close,callback:function(){this.closePopup();this.onClose()}.bind(this),visibleOnError:!0})},addInfographicsSelect:function(a){a.placeAt(this.toolbarHolder.infographicsSelectDiv)},onShowPageAt:function(a){},onShowAnalysisAreaAt:function(a){},onZoomToFitPage:function(){},onZoomToFitPageWidth:function(){},onSetZoomPercent:function(a){},onClose:function(){}})});