// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/dynamicSettings/SectionDynamicSettingsBuilder","dojo/_base/declare dojo/on dojo/promise/all dojo/dom-class dojo/dom-construct esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/PopupUtil esri/dijit/geoenrichment/utils/TooltipUtil ./_ChartSettingsBuilder ./_LocatorSettingsBuilder ./_MapSettingsBuilder ./SectionDynamicSettings dojo/i18n!esri/nls/jsapi".split(" "),function(h,e,k,l,f,m,g,n,p,q,r,t,d){d=d.geoenrichment.dijit.ReportPlayer.SectionDynamicSettingsBuilder;
return h(null,{_section:null,_settingsWidget:null,_settingsToolbar:null,constructor:function(a){this._section=a;this._createSettings()},_createSettings:function(){var a=this;k({chartSettings:p.provideChartSettings(this._section),locatorSettings:q.provideLocatorSettings(this._section),mapSettings:r.provideMapSettings(this._section)}).then(function(b){if(b.chartSettings||b.locatorSettings||b.mapSettings)a._addExportButton(b.locatorSettings),a._addSettingsButton(b),1<a._settingsToolbar.children.length&&
l.add(a._settingsToolbar,"hasMultipleButtons")})},_addSettingsButton:function(a){var b=this,c=!1,u=this._createButton("dijitInline sectionDynamicSettings_settingsButton "+(a.locatorSettings?"locatorTable":""),function(){c||(c=!0,g.makePopup(function(){return b._createPopup(a)},this._section,u,{orient:["before","below"]}))})},_addExportButton:function(a){if(a&&a.canExportToExcel){var b=this._createButton("dijitInline sectionDynamicSettings_exportButton");e(b,"click",function(){a.locatorTableInfographic.exportToExcel()});
n.setTooltipToNode(b,d.exportInfographicPanel)}},_createButton:function(a,b){return f.create("div",{"class":a},this._createSettingsToolbar(b))},_createSettingsToolbar:function(a){var b=this;if(!this._settingsToolbar){var c=function(a){b._settingsToolbar.style.opacity=a?"":"0";a&&b._settingsToolbar.__onShowHandles.forEach(function(a){return a()})};this._settingsToolbar=f.create("div",{"class":"sectionDynamicSettings_toolbar"},this._section.domNode);this._settingsToolbar.__onShowHandles=[];c(!1);this._section.own(e(document.body,
"mousemove",function(){c(m.isMouseOver(b._section.domNode))}))}a&&this._settingsToolbar.__onShowHandles.push(a);return this._settingsToolbar},_createPopup:function(a){function b(){g.close(c._settingsWidget)}var c=this;this._settingsWidget||(this._settingsWidget=new t({chartSettings:a.chartSettings,locatorSettings:a.locatorSettings,mapSettings:a.mapSettings,onSortChart:function(a){b();c._section.sortChart(a)},onChartToTable:function(){b();c._section.chartToTable()},onTableToChart:function(){b();c._section.tableToChart()},
onCalcStateChanged:function(a){b();c._section.setChartCalculationState(a)},onLocatorFilterChanged:function(a){c._section.getInfographic().getInnerInfographic().setSearchText(a.searchText);c._section.getInfographic().getInnerInfographic().setFilterRanges(a.filterRanges)},onLegendVisibilityChanged:function(a){c._section.getMapImages()[0].setLegendVisible(a)},onClosePopup:function(){b()}}),this._section.own(this._settingsWidget),this._settingsWidget.setVisualState(this._section.getVisualState()));return this._settingsWidget},
setVisualState:function(a){this._settingsWidget&&this._settingsWidget.setVisualState(a)}})});