// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/SectionDynamicLocatorSettings.html":'\x3cdiv class\x3d"esriGEReportPlayer_sectionDynamicLocatorSettings"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"refineResultsTitle" class\x3d"esiGERowHigh"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"esriGESpaceBeforeBig"\x3e\r\n        \x3cdiv class\x3d"sectionDynamicLocatorSettings_row"\x3e\r\n            \x3cdiv class\x3d"esriGERowHigh"\x3e${nls.byKeywords}\x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"textFilterDiv" class\x3d"esriGERowHigh"\x3e\x3c/div\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"filtersBlock"\x3e\x3c/div\x3e\r\n        \x3cdiv class\x3d"esriGERowHigh"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"resetButton" class\x3d"dijitInline esriGELink"\x3e${nls.resetFilters}\x3c/div\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/dynamicSettings/SectionDynamicLocatorSettings","dojo/_base/declare dojo/on dojo/string dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin dijit/form/TextBox esri/dijit/geoenrichment/NumericalSlider esri/dijit/geoenrichment/utils/InvokeUtil dojo/text!../../templates/SectionDynamicLocatorSettings.html dojo/i18n!esri/nls/jsapi".split(" "),function(g,e,h,f,k,l,m,n,p,q,b){b=b.geoenrichment.dijit.ReportPlayer.SectionDynamicSettingsBuilder;
return g([k,l],{templateString:q,nls:b,_originalStatRanges:null,_filters:null,textFilter:null,_filterWidgets:null,postCreate:function(){var a=this;this.inherited(arguments);this._buildKeywordFilter();e(this.resetButton,"click",function(){a.textFilter.set("value","");a._buildFiltersFromOriginals();a._buildRangeFilters();a._doEmitEvent()})},setNumPoints:function(a,c){this.refineResultsTitle.innerHTML=h.substitute(b.refineYourResults,{numTotal:a||0,numShown:c||0})},setStatRanges:function(a){this._originalStatRanges=
a||[];this._buildFiltersFromOriginals();this._buildRangeFilters()},_buildFiltersFromOriginals:function(){this._filters=this._originalStatRanges.map(function(a){return{label:a.alias,fieldName:a.fieldName,minValue:a.min,maxValue:a.max,lowerValue:a.min,upperValue:a.max,decimals:a.decimals}})},_buildKeywordFilter:function(){this.textFilter=(new m({"class":"sectionDynamicLocatorSettings_textFilter",trim:!0,placeHolder:b.keywordsPlaceholder})).placeAt(this.textFilterDiv);e(this.textFilter.textbox,"keyup",
this._emitEvent.bind(this));this.own(this.textFilter)},_buildRangeFilters:function(){var a=this;this._destroyFilterWidgets();this._filterWidgets=[];this._filters.forEach(function(c){var b=f.create("div",{"class":"esriGERowHigh sectionDynamicLocatorSettings_row"},a.filtersBlock),d=(new n({label:c.label,minValue:c.minValue,maxValue:c.maxValue,lowerValue:c.lowerValue,upperValue:c.upperValue,decimals:c.decimals,timeIntervalLength:250,onChange:function(b){c.lowerValue=d.round(b.lowerValue);c.upperValue=
d.round(b.upperValue);a._emitEvent()}})).placeAt(b);d.startup();a._filterWidgets.push(d)})},_emitEvent:function(){p.invoke(this,"_doEmitEvent",100)},_doEmitEvent:function(){this.onLocatorFilterChanged({searchText:this.textFilter.get("value"),filterRanges:this._filters.map(function(a){return{fieldName:a.fieldName,min:a.lowerValue,max:a.upperValue}})})},onLocatorFilterChanged:function(a){},setVisualState:function(a){a&&(a=a.stackElements[0]&&a.stackElements[0].cells&&a.stackElements[0].cells[0])&&(a.filterRanges&&
(a.filterRanges.forEach(function(a,b){b=this._filters.filter(function(b){return b.fieldName===a.fieldName})[0];b.lowerValue=a.min;b.upperValue=a.max},this),this._buildRangeFilters()),this.textFilter.set("value",a.searchText||""))},_destroyFilterWidgets:function(){this._filterWidgets&&(this._filterWidgets.forEach(function(a){a.destroy()}),this._filterWidgets.length=0);f.empty(this.filtersBlock)},destroy:function(){this._destroyFilterWidgets();this.inherited(arguments)}})});