// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/GEUtil","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when dojo/promise/all dojox/uuid/generateRandomUuid esri/kernel esri/request esri/urlUtils esri/dijit/geoenrichment/utils/requests/UniversalClient esri/dijit/geoenrichment/utils/UrlUtil ./stdGeographies/StdGeographiesModel ./PortalManager".split(" "),function(d,l,p,k,q,r,t,h,u,m,v,w,x){function g(a,b){a=u.urlToObject(a);if(b&&(b=l.mixin(a.query||{},b),!b.token)){var c=
t.id.credentials[0];b.token=c&&c.token}return{url:a.path,taskParams:b}}function e(a,b){f||(f=new n(a));return!b||f.initialized?f:f.initialize()}var n=d(null,{_geoenrichmentUrl:null,_geInfo:null,_capabilities:null,_supportedOperations:null,constructor:function(a){this._geoenrichmentUrl=a},_initDfd:null,initialized:!1,initialize:function(){var a=this;if(this._initDfd)return this._initDfd.promise;this._initDfd=new p;h({url:g(this._geoenrichmentUrl).url+"/Geoenrichment",content:{f:"json"},handleAs:"json"}).then(function(b){a._geInfo=
b;a._capabilities={};a._supportedOperations={};b.capabilities&&b.capabilities.forEach(function(b){a._capabilities[b.toLowerCase()]=!0});b.supportedOperations&&b.supportedOperations.forEach(function(b){a._supportedOperations[b.toLowerCase()]=!0});a.initialized=!0;a._initDfd.resolve()});return this._initDfd.promise},hasCapability:function(a){return this._capabilities[a.toLowerCase()]},supportsOperation:function(a){return this._supportedOperations[a.toLowerCase()]},enrich:function(a){a=g(this._geoenrichmentUrl,
a);a.taskParams.AddDerivativeVariables="all";return h({url:a.url+"/Geoenrichment/Enrich",content:a.taskParams,handleAs:"json"}).then(function(a){return a.results[0].value.FeatureSet||[]})},_contriesCache:{},getCountryInfo:function(a){var b=this;if(!this._contriesCache[a]){var c=g(this._geoenrichmentUrl,{f:"json"});this._contriesCache[a]=h({url:c.url+"/Geoenrichment/Countries/"+a,content:c.taskParams,handleAs:"json"}).then(function(c){var d=c.countries[0],e={};return q(d.hierarchies.map(function(c){return k(b.getStdGeographyModel(a,
c.ID),function(a){e[c.ID]=a})})).then(function(){return{country:d,geographiesModels:e}})})}return this._contriesCache[a]},_stdModelCache:null,getStdGeographyModel:function(a,b){b=b||"census";this._stdModelCache=this._stdModelCache||{};var c=a+b;if(!this._stdModelCache[c]){var d=g(this._geoenrichmentUrl,{f:"json"});this._stdModelCache[c]=h({url:d.url+"/Geoenrichment/StandardGeographyLevels/"+a+"/"+b,content:d.taskParams,handleAs:"json"}).then(function(c){return new w(a,b,c)})}return this._stdModelCache[c]},
formatReport:function(a){a=g(this._geoenrichmentUrl,a);return(new m({allowSSL:!0})).send(a.url+"/Geoenrichment/FormatReport",{handleAs:"bin",content:a.taskParams}).then(function(a){return a&&a.data&&"text/plain"===a.data.type?null:a})},_tasksHash:{},createReport:function(a){var b=g(this._geoenrichmentUrl,a),c=r();this._tasksHash[c]={taskName:"createReport",taskParams:l.clone(a)};return(new m({allowSSL:!0})).send(b.url+"/Geoenrichment/createReport",{handleAs:"text",content:b.taskParams}).then(function(a){return{taskID:c,
result:a}})},consumeCredits:function(a){if(a=this._tasksHash[a])return a=l.clone(a),delete a.taskParams.forStorage,this[a.taskName](a.taskParams)},_dataLayersCache:{},getLayerInfos:function(a){this._dataLayersCache[a]||(this._dataLayersCache[a]=this._getLayerInfos(a));return this._dataLayersCache[a]},_getLayerInfos:function(a){var b=g(this._geoenrichmentUrl,{f:"json"});return h({url:b.url+"/Geoenrichment/DataLayers/"+a,content:b.taskParams,handleAs:"json"}).then(function(a){return a&&a.layers||[]}).otherwise(function(a){console.log(a);
return[]})},getLayerInfo:function(a,b){var c=a+"_"+b;this._dataLayersCache[c]||(this._dataLayersCache[c]=this._getLayerInfo(a,b));return this._dataLayersCache[c]},_getLayerInfo:function(a,b){var c=g(this._geoenrichmentUrl,{f:"json"});return h({url:c.url+"/Geoenrichment/DataLayers/"+a+"/"+b,content:c.taskParams,handleAs:"json"}).then(function(a){return a&&a.layer}).otherwise(function(a){console.log(a);return null})}});d={provideGeoenrichmentUrl:function(a){return k(function(){if(!a.geoenrichmentUrl)return k(x.getPortalInfo(a),
function(b){a.geoenrichmentUrl=b.portal.helperServices.geoenrichment.url})}(),function(){v.registerCORS(a.geoenrichmentUrl)})}};d.GEClient=n;var f;d.getClient=function(){return f};d.initialize=function(a){return e(a,!0)};d.enrich=function(a,b){return e(a).enrich(b)};d.formatReport=function(a,b){return e(a).formatReport(b)};d.createReport=function(a,b){return e(a).createReport(b)};d.consumeCredits=function(a,b){return e(a).consumeCredits(b)};d.getLayerInfos=function(a,b){return e(a).getLayerInfos(b)};
d.hasCapability=function(a,b){return k(e(a,!0),function(){return f&&f.hasCapability(b)})};d.supportsOperation=function(a,b){return k(e(a,!0),function(){return f&&f.supportsOperation(b)})};d.getCountryInfo=function(a,b){return e(a).getCountryInfo(b)};d.getStdGeographyModel=function(a,b,c){return e(a).getStdGeographyModel(b,c)};return d});