// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/ReportDataProcessor","dojo/_base/lang dojo/when dojo/promise/all dojo/Deferred ./tasks/EnrichAreasTask ./tasks/RunReportTask ./AreaDataUtil ./CustomReportsManager ./attachments/AttributesUtil esri/dijit/geoenrichment/utils/DateUtil ../../core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoNameUtil ../../core/supportClasses/templateJsonUtils/fieldInfo/FieldLibrary ../../core/infographics/dataDrilling/EnrichUtil ./tasks/parsers/FeatureSetParser".split(" "),
function(x,h,k,p,q,r,d,l,y,m,c,n,t,u){var f={ENRICHED_DATA_NO_LEVELS:"enrichFieldData_noLevels",addFeatureAttributesCalculator:function(b,a){for(var e in b.attributes)d.setAreaDataObjectValue(e,b.attributes[e],a,c.AREA_ATTRIBUTES_CALCULATOR_NAME)},addAreaInfoCalculator:function(b,a){d.setAreaDataObjectValue("SITE_NAME",b.name||b.shortName||"",a,c.AREA_ATTRIBUTES_CALCULATOR_NAME);d.setAreaDataObjectValue("STORE_NAME",b.name||b.shortName||"",a,c.AREA_ATTRIBUTES_CALCULATOR_NAME);d.setAreaDataObjectValue("AREA_DESC",
b.description||"",a,c.AREA_ATTRIBUTES_CALCULATOR_NAME);d.setAreaDataObjectValue("AREA_DESC2",b.description||"",a,c.AREA_ATTRIBUTES_CALCULATOR_NAME);d.setAreaDataObjectValue("AREA_DESC3",b.description||"",a,c.AREA_ATTRIBUTES_CALCULATOR_NAME);d.setAreaDataObjectValue("STORE_ADDR",b.address||"",a,c.AREA_ATTRIBUTES_CALCULATOR_NAME);d.setAreaDataObjectValue("STORE_LAT",b.latitude||"",a,c.AREA_ATTRIBUTES_CALCULATOR_NAME);d.setAreaDataObjectValue("STORE_LONG",b.longitude||"",a,c.AREA_ATTRIBUTES_CALCULATOR_NAME)},
addEnrichFeatureSet:function(b,a,e,v){b=u.parse(b,e||f.ENRICHED_DATA_NO_LEVELS,function(b){return a[b]||b});d.mergeAreaData(b,v.fieldData.areaData)}};return{populateReportDataFromAttachmentsStore:function(b,a){var e=[];e.push(h(a.getNotes(),function(a){a&&a.length&&(b.fieldData.metadata[n.SITENOTE_FIELD_NAME]=a[0].text,b.fieldData.metadata[n.SITENOTES_FIELD_NAME]=a.map(function(a){return a.text}).join("\x3cbr/\x3e\x3cbr/\x3e"))}));e.push(h(a.getAttributes(),function(a){if(!a||!a.length)return null;
var e={attributes:{}};a.forEach(function(a){e.attributes[a.name]=a.value});b.analysisAreas.forEach(function(a,d){(a=b.fieldData.areaData[d])&&f.addFeatureAttributesCalculator(e,a)})}));return k(e)},runReportAndGetData:function(b){return h(l.getCustomReportByID(b),function(a){return(new r).execute({geoenrichmentUrl:b.geoenrichmentUrl,analysisAreas:b.analysisAreas,countryID:b.countryID,hierarchy:a.hierarchy,report:{reportID:a.reportID,portalUrl:a.templateData.getPortalUrl(!0),modified:a.modified},cacheResult:!0}).then(function(b){return{taskID:b.taskID,
selectedReport:a,areaData:b.areaData}},function(a){b.fieldData.errors.push(a);return(new p).reject(a)})})},applyRunReportAndGetDataResults:function(b,a){b&&b.areaData&&(a.fieldData.runReportTaskID=b.taskID,a.fieldData.areaData=b.areaData,a.analysisAreas&&this._reportDataFromAreas(a.analysisAreas,a.fieldData.areaData),b.selectedReport&&this._reportDataFromReport(b.selectedReport,a.fieldData))},_reportDataFromAreas:function(b,a){b.forEach(function(b,d){if(d=a[d])f.addFeatureAttributesCalculator(b.feature,
d),f.addAreaInfoCalculator(b,d)})},_reportDataFromReport:function(b,a){a=a.metadata;b&&!a.Title&&(a.Title=b.title);a.Source="Esri";a.Date=m.getReportFooterDate();a.Copyright="\u00a9"+m.getFullYear()+" Esri";a.ProductLabel="";a.ProductUrl="";a.PhoneNumber="";a.TrialUrlText=""},enrichFieldData:function(b,a){function e(b,c,e){function w(b){return a.fieldData.areaData.every(function(c,g){return void 0!==d.getAreaDataValue({fieldName:b,fieldData:a.fieldData,calculatorName:e,featureIndex:g,ignoreMetadata:!0})})}
var g=[],f={};b.forEach(function(a){w(a.fieldName)||(g.push(a.mapTo),f[a.mapTo]=a.fieldName,f[a.mapTo.substr(a.mapTo.indexOf(".")+1)]=a.fieldName)});return g.length?{fields:g,fieldsMap:f,comparisonLevels:c,calculatorName:e}:null}var c=[];b=t.optimizeInfos(b);b.forEach(function(a){var b;if(a.isGeneral||a.isChart)b=e(a.fields,a.levels,a.calculatorName);b&&c.push(b)});if(c.length)return h(l.getCustomReportByID(a),function(b){function d(b){a.fieldData.errors.push(b)}return k(c.map(function(c){return(new q).enrichAreas({geoenrichmentUrl:a.geoenrichmentUrl,
analysisAreas:a.analysisAreas,countryID:a.countryID,hierarchy:b.hierarchy,fields:c.fields,comparisonLevels:c.comparisonLevels}).then(function(b){f.addEnrichFeatureSet(b[0],c.fieldsMap,c.calculatorName,a)},d)}))})}}});