// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/2d/engine/webgl/mesh/factories/WGLMeshFactory","require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/Error ../../../../../../core/Logger ../../../../../../symbols/SimpleLineSymbol ../../definitions ../../enums ../../MaterialInfo ../../Utils ../../visualVariablesUtils ../../WGLDisplayObject ../VertexVector ../templates/meshTemplateUtils ../templates/WGLLabelTemplate ../templates/WGLLineTemplate ../templates/WGLMarkerTemplate ../../util/Matcher ../../util/serializationUtils ../../util/vvFlagUtils ../../util/Writer".split(" "),
function(H,B,U,z,L,M,t,e,C,D,I,N,n,u,O,P,J,E,F,x,K){Object.defineProperty(B,"__esModule",{value:!0});var w=L.getLogger("esri.views.2d.engine.webgl.WGLMeshFactory"),Q={esriGeometryPoint:"above-center above-left above-right center-center center-left center-right below-center below-left below-right".split(" "),esriGeometryPolygon:["always-horizontal"],esriGeometryPolyline:null,esriGeometryMultipoint:null,esriGeometryEnvelope:null},A=function(){function c(){this._materials=[];this._materialsIndex=new Map}
c.prototype.insert=function(a){var b=this._materials.length;this._materials.push(a);return b};c.prototype._hashGlyph=function(a,b,d){return"G-"+b+"-"+d+"-"+a.page};c.prototype._hashSprite=function(a,b,d){return"S-"+b+"-"+d+"-"+(a?a.page:-1)};c.prototype.createSpriteMaterial=function(a,b,d){var g=this._hashSprite(a,b,d);if(this._materialsIndex.has(g))return this._materialsIndex.get(g);var f=this._materials.length;a=C.default.fromSprite(a,b,d);this._materials.push(a);this._materialsIndex.set(g,f);return f};
c.prototype.createGlyphMaterial=function(a,b,d){var g=this._hashGlyph(a,b,d);if(this._materialsIndex.has(g))return this._materialsIndex.get(g);var f=this._materials.length;a=C.default.fromGlyph(a,b,d);this._materials.push(a);this._materialsIndex.set(g,f);return f};c.prototype.get=function(a){return this._materials[a]};c.prototype.serialize=function(a){F.serializeList(a,this._materials);return a};c.deserialize=function(a){var b=new c;b._materials=F.deserializeList(a,C.default);return b};return c}();
B.MaterialStore=A;var R=function(){function c(a){this._bucketSize=a;this._rowsLength=t.TILE_SIZE/a;this._colsLength=t.TILE_SIZE/a;this._grid=this._initGrid()}c.prototype.checkOverlap=function(a,b){a=Math.floor(a/this._bucketSize);b=Math.floor(b/this._bucketSize);if(0>a||a>=this._rowsLength||0>b||b>=this._colsLength||this._grid[b][a])return!0;this._grid[b][a]=!0;return!1};c.prototype.reset=function(){this._grid=this._initGrid()};c.prototype._initGrid=function(){for(var a=[],b=0;b<this._rowsLength;b++)a.push(Array(this._colsLength));
return a};return c}(),S=function(){function c(a,b,d){this.displayObjects=a;this.vertexVectorsMap=b;this._materials=d;this.grid=new R(t.COLLISION_EARLY_REJECT_BUCKET_SIZE)}c.prototype.get=function(a){return this.vertexVectorsMap[a]};c.prototype.pushDisplayObject=function(a){this.displayObjects.push(a)};c.prototype.encode=function(a,b){var d=F.serializeList(new K.default(Uint32Array,this._guessSize()),this.displayObjects).buffer(),g=this._materials.serialize(new K.default(Uint32Array)).buffer(),f={};
b.push(d);b.push(g);for(var c in this.vertexVectorsMap){var h=this.vertexVectorsMap[c];f[c]={};h.transfer(f[c],b)}a.displayObjects=d;a.materialStore=g;a.vertexBuffersMap=f;this.destroy()};c.prototype.destroy=function(){this.displayObjects=this.vertexVectorsMap=null};c.prototype._guessSize=function(){for(var a=this.displayObjects,b=Math.min(a.length,4),d=0,g=0;g<b;g++)d=Math.max(d,a[g].displayRecords.length);return 2*(12*a.length+a.length*d*40)};return c}(),T=function(){function c(){this._vvMap=new Map}
c.prototype.set=function(a,b){this._vvMap.set(a,b)};c.prototype.getValue=function(a,b,d){return this._vvMap.has(a)?this._vvMap.get(a)(b,d):0};return c}();H=function(){function c(a,b,d,g,f,c,h,e,y,m){var p=this;this._labelsDebugTemplate=null;this._matcher=a;this._materials=d;this._geometryType=g;this._idField=f;this._pixelRatio=y;this._vvMap=null;this._vvFlags=h;this._vvBuf=new ArrayBuffer(16);this._vvBufU32=new Uint32Array(this._vvBuf);this._vvBufF32=new Float32Array(this._vvBuf);this._createVVFunctionMap(c,
b,e);m&&(this._validateLabelingInfo(m)?this._labelTemplates=m.map(function(a){return O.default.fromText(p._materials,0,a.symbol,y,a.labelPlacement)}):w.error(new z("mapview-labeling:unsupported-geometry","LabelingInfo failed validation - unable to create labels for layer.")))}c.from=function(a,b,d,g,f,e,h,G){switch(a.type){case "simple":return c._fromSimpleRenderer(a,b,d,g,f,e,h,G);case "unique-value":case "uniqueValue":return c._fromUniqueValueRenderer(a,b,d,g,f,e,h,G);case "class-breaks":case "classBreaks":return c._fromClassBreaksRenderer(a,
b,d,g,f,e,h,G);default:return w.error(new z("mapview-mesh:invalid-renderer","Unable to handle unknown renderer type")),null}};Object.defineProperty(c.prototype,"materials",{get:function(){return this._materials},enumerable:!0,configurable:!0});c.prototype.createMeshData=function(a){var b=Array(5),d=this._matcher.getDefault(),g=!!x.getMarkerVVFlags(this._vvFlags),f=!!x.getFillVVFlags(this._vvFlags),c=!!x.getLineVVFlags(this._vvFlags,"esriGeometryPolyline"!==this._geometryType),h=!!x.getTextVVFlags(this._vvFlags);
!this._labelTemplates&&d&&1===d.length&&d[0]instanceof J.default?(b[e.WGLGeometryType.MARKER]=new n.VertexVectors(e.WGLGeometryType.MARKER,g,a),b[e.WGLGeometryType.FILL]=new n.VertexVectors(e.WGLGeometryType.FILL,f,0),b[e.WGLGeometryType.LINE]=new n.VertexVectors(e.WGLGeometryType.LINE,c,0),b[e.WGLGeometryType.TEXT]=new n.VertexVectors(e.WGLGeometryType.TEXT,h,0),b[e.WGLGeometryType.LABEL]=new n.VertexVectors(e.WGLGeometryType.LABEL,!1,0)):(b[e.WGLGeometryType.MARKER]=new n.VertexVectors(e.WGLGeometryType.MARKER,
g,a),b[e.WGLGeometryType.FILL]=new n.VertexVectors(e.WGLGeometryType.FILL,f,a),b[e.WGLGeometryType.LINE]=new n.VertexVectors(e.WGLGeometryType.LINE,c,a),b[e.WGLGeometryType.TEXT]=new n.VertexVectors(e.WGLGeometryType.TEXT,h,a),b[e.WGLGeometryType.LABEL]=new n.VertexVectors(e.WGLGeometryType.LABEL,!1,this._labelTemplates&&0<this._labelTemplates.length?a:0));return new S([],b,this._materials)};c.prototype.write=function(a,b,d,g,c){var f=1===this._matcher.size()&&this._matcher.getDefault()||this._matcher.match(b,
d),h=b.attributes[this._idField],e=new N(h),y=!!g&&!!this._labelTemplates;this._computeVV(b,d);if(f&&(b.geometry||b.centroid)){d=e.displayRecords;for(var m=0;m<f.length;m++){var l=f[m],k=a.get(l.geometryType);l.writeMesh(d,k,this._geometryType,h,b,this._pixelRatio,this._vvBufU32)}y&&(f=this._getLabelReference(f),this._writeLabelMesh(e,a,h,b,c,g.get(h),f));a.pushDisplayObject(e)}};c.prototype._hasBadLabelClass=function(a,b){var d=a.labelPlacement,c=Q[b];if(!c)return w.error(new z("mapview-labeling:unsupported-geometry-type",
"Unable to create labels for WebGL Feature Layer, "+b+" is not supported")),!0;c.some(function(a){return a===d})||(c=c[0],w.warn("Found invalid label placement type "+d+" for "+b+". Defaulting to "+c),a.labelPlacement=c);return!1};c.prototype._validateLabelingInfo=function(a){var b=this;return!a.some(function(a){return b._hasBadLabelClass(a,b._geometryType)})};c.prototype._getLabelReference=function(a){for(var b=0;b<a.length;b++){var d=a[b];if(d instanceof J.default)return d}return null};c.prototype._writeLabelMesh=
function(a,b,d,c,f,e,h){for(var g=a.displayRecords,y=0,m=0,l=-1,k=-1,q=0;q<e.labelingInfo.length;q++){var r=e.labelingInfo[q],p=e.text[q],v=this._labelTemplates[r],n=b.get(v.geometryType),u=f.get(v.symbolId).glyphMosaicItems,x=g.length;v.bindReferenceTemplate(h);if(!v.computeGlyphs(u,p)){u=v.computeAnchor(this._geometryType,c);p=v.bounds;if(-1===l&&(l=Math.floor(u[0]/t.COLLISION_BUCKET_SIZE),k=Math.floor(u[1]/t.COLLISION_BUCKET_SIZE),b.grid.checkOverlap(u[0],u[1])))return;v.writeMesh(g,n,this._geometryType,
d,c,this._pixelRatio,this._vvBufU32);a.anchor=u;a.addMetric(p,x,g.length-x,r);r=p.center;y=Math.max(p.halfWidth+Math.abs(r[0]),y);m=Math.max(p.halfHeight+Math.abs(r[1]),m)}}-1!==l&&(d=2.5*Math.max(y,m),b=Math.ceil(Math.abs((d-a.anchor[0]%t.COLLISION_BUCKET_SIZE)/t.COLLISION_BUCKET_SIZE)),d=Math.ceil(Math.abs((d-a.anchor[1]%t.COLLISION_BUCKET_SIZE)/t.COLLISION_BUCKET_SIZE)),a.xBucket=l,a.yBucket=k,a.xOverflow=b,a.yOverflow=d)};c.prototype._debugLabels=function(a,b,d,c,f){c={geometry:{paths:[[[c[0]+
f.center[0]-f.width/2,c[1]+f.center[1]+f.height/2],[0,-f.height],[f.width,0],[0,f.height],[-f.width,0]]]},attributes:{}};f=this._getLabelDebugTemplate();b=b.get(f.geometryType);f.writeMesh(a,b,"esriGeometryPolyline",d,c,this._pixelRatio,this._vvBufU32)};c.prototype._getLabelDebugTemplate=function(){this._labelsDebugTemplate||(this._labelsDebugTemplate=this._createLabelsDebugTemplate());return this._labelsDebugTemplate};c.prototype._createLabelsDebugTemplate=function(){var a=new M({style:"solid",width:1,
color:[255,0,0,1]});return P.default.fromSimpleLine(this._materials,0,a,null,this._pixelRatio)};c.prototype._isErrorVV=function(a){return null===a||isNaN(a)||Infinity===a};c.prototype._computeVV=function(a,b){if(!this._vvMap)return 0;var c=this._vvMap.getValue(e.VVType.SIZE,a,b),g=this._vvMap.getValue(e.VVType.COLOR,a,b),f=this._vvMap.getValue(e.VVType.OPACITY,a,b);a=this._vvMap.getValue(e.VVType.ROTATION,a,b);this._vvBufF32[e.VVType.SIZE]=this._isErrorVV(c)?NaN:c;this._vvBufF32[e.VVType.COLOR]=this._isErrorVV(g)?
NaN:g;this._vvBufF32[e.VVType.OPACITY]=this._isErrorVV(f)?NaN:f;this._vvBufF32[e.VVType.ROTATION]=this._isErrorVV(a)?NaN:a;return 0};c.prototype._createVVFunctionMap=function(a,b,c){if(a&&a.length)for(var d=0;d<a.length;d++){var f=a[d],e=D.getVVType(f.type);if(f=this._createGetValueFunction(f,b,c))this._vvMap||(this._vvMap=new T),this._vvMap.set(e,f)}};c.prototype._createGetValueFunction=function(a,b,c){if(D.getVVType(a.type)===e.VVType.SIZE){var d=I.getTypeOfSizeVisualVariable(a);return d===e.WGLVVFlag.SIZE_SCALE_STOPS?
null:this._createNormalizedFunction(a,b,c,d===e.WGLVVFlag.SIZE_UNIT_VALUE&&function(b){return I.getVisualVariableSizeValueRepresentationRatio(b,a.valueRepresentation)})}return this._createNormalizedFunction(a,b,c)};c.prototype._createNormalizedFunction=function(a,b,c,e){var d=a.field;if(d){if("string"===typeof d){var g=a.normalizationField;return g?function(a){if(a.attributes[d]&&a.attributes[g])return a=a.attributes[d]/a.attributes[g],e?e(a):a}:e?function(a){return e(a.attributes[d])}:function(a){return a.attributes[d]}}if("function"===
typeof d)return w.error(new z("mapview-rendering:unsupported-feature","Function field types are not currently supported. Please use a valueExpression instead")),function(a){};w.error(new z("mapview-rendering:invalid-type","The field for a vv must be a string or a number, but got "+typeof d));return function(a){}}if(a.valueExpression&&"$view.scale"!==a.valueExpression)return D.createArcadeFunction({valueExpression:a.valueExpression,spatialReference:c,layer:b},e);w.error("Unable to create a normalized function for visual variable: "+
a);return function(a){}};c._fromSimpleRenderer=function(a,b,d,e,f,p,h,n){var g=a.getSymbols();a=a.visualVariables;var m=x.getVVFlags(a),l=new E.default,k=new A;g.length&&l.setDefault(u.createMeshTemplates([],k,g[0],d,m,h));return new c(l,b,k,e,f,a,m,p,h,n)};c._fromUniqueValueRenderer=function(a,b,d,e,f,p,h,n){var g=a.uniqueValueInfos,m=a.visualVariables,l=x.getVVFlags(m),k=[a.field];a.field2&&k.push(a.field2);a.field3&&k.push(a.field3);for(var q=a.valueExpression,k=new E.MapMatcher(k,a.fieldDelimiter,
q?{valueExpression:q,spatialReference:p,layer:b}:null),q=new A,r=a.backgroundFillSymbol,r=r&&u.createMeshTemplates([],q,r,d,l,h),t=0;t<g.length;t++){var v=g[t],w=u.createMeshTemplates([],q,v.symbol,d,l,h);k.add(v.value,r?r.concat(w):w)}if(a=a.defaultSymbol)d=u.createMeshTemplates([],q,a,d,l,h),k.setDefault(r?r.concat(d):d);return new c(k,b,q,e,f,m,l,p,h,n)};c._fromClassBreaksRenderer=function(a,b,d,e,f,n,h,t){for(var g=a.isMaxInclusive,m=a.visualVariables,l=a.valueExpression,k=a.normalizationField,
q=a.normalizationTotal,r=a.normalizationType,p=x.getVVFlags(m),g=new E.IntervalMatcher(a.field,g,l?{valueExpression:l,spatialReference:n,layer:b}:null,{normalizationField:k,normalizationTotal:q,normalizationType:r}),l=new A,k=(k=a.backgroundFillSymbol)&&u.createMeshTemplates([],l,k,d,p,h,!0),q=0,r=a.classBreakInfos;q<r.length;q++){var v=r[q],w=u.createMeshTemplates([],l,v.symbol,d,p,h);g.add({min:v.minValue,max:v.maxValue},k?k.concat(w):w)}if(a=a.defaultSymbol)d=u.createMeshTemplates([],l,a,d,p,h),
g.setDefault(k?k.concat(d):d);return new c(g,b,l,e,f,m,p,n,h,t)};return c}();B.default=H});