// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/GridCellRenderer","dojo/_base/declare dojo/aspect ./GridDataUtil ./GridStyleUtil ./GridLayoutCalculator ./GridCellContentScaler ./GridCellContentSynchronizer ../../supportClasses/conditionalStyling/ConditionalStyleUtil ../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoRenderer ../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes ./GridQueryUtil ./tooltip/GridCellTooltipBuilder ../../../_devConfig".split(" "),
function(q,v,f,w,x,r,y,z,t,E,A,g,u,B,C){function k(a){return a[a.parentGrid.hasRealBorders?"getContentWidth":"getWidth"]()}function n(a){return a[a.parentGrid.hasRealBorders?"getContentHeight":"getHeight"]()}var D={color:"#FF0000"},l=q(null,{_parentState:null,constructor:function(a,b,c){var d=this;r.fitContentInsideCell(a);this._setParentState(a);c.forEach(function(c){var e=c[1];b.own(v.after(a,c[0],function(){d._checkParentChanged(e,a)&&(r.fitContentInsideCell(a),y.syncParentFieldInfoWithElementState(a,
b))}))})},_setParentState:function(a){var b=a.getFullStyle();this._parentState={width:a.getWidth(),height:a.getHeight(),horizontalAlign:b.horizontalAlign,verticalAlign:b.verticalAlign}},_checkParentChanged:function(a,b){var c;switch(a){case "width":a=b.getWidth();this._parentState.width!==a&&(this._parentState.width=a,c=!0);break;case "height":a=b.getHeight();this._parentState.height!==a&&(this._parentState.height=a,c=!0);break;case "horizontalAlign":case "verticalAlign":if(a=b.getFullStyle(),this._parentState.horizontalAlign!==
a.horizontalAlign||this._parentState.verticalAlign!==a.verticalAlign)this._parentState.horizontalAlign=a.horizontalAlign,this._parentState.verticalAlign=a.verticalAlign,c=!0}return c}});return q(null,{renderCellContent:function(a){var b=a.parentGrid,c=f.getFieldInfo(a);if(C.emulateErrors.reportContainerRenderError)throw Error("Error test: something crashed whend building the UI layout!");if(c){if(c.isChart){this._placeChartInCell(b,a);return}if(c.isImage||c.isShape){this._renderCellTooltip(a);this._placeImageOrShapeInCell(b,
a,c.isImage);return}if(c.isReportSection){this._placeReportSectionInCell(b,a);return}if(c.isInfographic){this._placeInfographicInCell(b,a);return}c.isMissing&&a.setStyle(D);b=this._getRenderedContent(a,c)}else b=a.gridData[a.column.field],b={formattedValue:null===b||void 0===b||"number"===typeof b&&isNaN(b)?"":b,value:b,formatFunction:null,isUnavailableData:!1,conditionalStyle:null};this._applyRenderedContent(a,b);a.setContent(null);this._renderCellTooltip(a)},_renderCellTooltip:function(a){a.viewModel.dynamicReportInfo&&
B.setDynamicTooltipToCell(a,a.viewModel.dynamicReportInfo.templateVariableProvider)},updateViewMode:function(a){var b=f.getFieldInfo(a);b&&(b.hasVariable||b.script||b.alias||b.isRichText)&&this._applyRenderedContent(a,this._getRenderedContent(a,b))},_getRenderedContent:function(a,b){a=this._prepareRenderContextForFieldCell(a,b);return t.renderFieldInfoInTableCell(b,a)},_applyRenderedContent:function(a,b){if(b){f.setFieldCellContent(a,b.formattedValue);if(!b.isUnavailableData)if("number"===typeof b.value&&
(f.setNumericCellValue(a,b.value),a.setNumberValue(b.value,a.parentGrid.enableNumberAnimation&&b.formatFunction)),b.conditionalStyle)a.setStyle(b.conditionalStyle.style),"string"===typeof b.conditionalStyle.formattedValue&&f.setFieldCellContent(a,b.conditionalStyle.formattedValue),a.__hasConditionalStyle=!0;else if(!1===b.conditionalStyle||a.__hasConditionalStyle)delete a.__hasConditionalStyle,a.setStyle(w.combineCellStyle(a.parentGrid,a.gridData,a.column));a.parentGrid&&a.parentGrid.viewModel.dynamicReportInfo&&
a.setUrl(f.getFieldCellUrl(a))}},_prepareRenderContextForFieldCell:function(a,b){var c=a.parentGrid,d=c.getSpecificViewMode(),e=c.getViewMode()===g.PREVIEW_VALUES;!b||"SiteNote"!==b.name&&"SiteNotes"!==b.name||(e=!0);d&&(d.richText===g.PREVIEW_VALUES&&b&&b.isRichText?e=!0:d.variable===g.PREVIEW_VALUES&&b&&(b.hasVariable||b.script)&&(e=!0));b=e;d=c.getViewMode()===g.EDIT;return{previewValues:b,previewConditionalStyle:!d,getPreviewValueFunction:c.getPreviewValueFunction,fieldData:c.viewModel.dynamicReportInfo&&
c.viewModel.dynamicReportInfo.fieldData,featureIndex:c.previewFeatureIndex||c.isMultiFeatureTable()&&x.calcRingIndexForCell(a),rowIndex:a.gridData&&a.gridData.index,isGraphicReport:c.viewModel.isGraphicStyle}},_placeChartInCell:function(a,b){var c={viewModel:a.viewModel,theme:a.theme,previewFeatureIndex:a.previewFeatureIndex,parentWidget:b,onContentLoadingStart:a.onContentLoadingStart.bind(a),onContentLoadingEnd:a.onContentLoadingEnd.bind(a)};return this._createChartPageFromParams(a,b,c)},_createChartPageFromParams:function(a,
b,c){var d=f.getFieldInfo(b).chartJson;a=a.viewModel.layoutBuilder.createElement("chart",{node:b.getContentContainerNode(),placeFunc:function(a){b.setContent(a)},json:d,creationParams:c});new l(b,a,[["onWidthChanged","width"],["onHeightChanged","height"]]);return a},_placeImageOrShapeInCell:function(a,b,c){var d=f.getFieldInfo(b),e=d[c?"imageJson":"shapeJson"],p=k(b),g=n(b);if(c){if(d.triggerJson&&a.viewModel.dynamicReportInfo){var m=t.getValueFromFieldData(d.triggerJson.fieldInfo,{fieldData:a.viewModel.dynamicReportInfo.fieldData});
z.processImageJsonForTrigger(e,m.value,d.triggerJson);m.isUnavailableData||"number"!==typeof m.value||f.setNumericCellValue(b,m.value)}e.style.width&&e.style.height&&!e.fitParent&&Math.round(e.style.width)!==Math.round(p)&&Math.round(e.style.height)!==Math.round(g)?e.fitParent=!1:(e.fitParent=!0,e.style.width=p,e.style.height=g)}else e.style.width=p,e.style.height=g;var h,d={viewModel:a.viewModel,theme:a.theme,parentWidget:b,alignParams:b.getFullStyle(),imageTriggerJson:d.triggerJson,getPreviewValueFunction:a.getPreviewValueFunction,
applyThemeStyle:a.applyThemeStyle,onInitialized:function(){if(b.domNode){var a=k(b),c=n(b);h&&h.resize&&h.resize({w:a,h:c},b.getFullStyle())}},onContentLoadingStart:a.onContentLoadingStart.bind(a),onContentLoadingEnd:a.onContentLoadingEnd.bind(a)};h=this._createImageOrShapeFromParams(a,b,e,c,d);new l(b,h,[["onWidthChanged","width"],["onHeightChanged","height"],["setStyle","horizontalAlign"]]);return h},_createImageOrShapeFromParams:function(a,b,c,d,e){return a.viewModel.layoutBuilder.createElement(d?
"image":"shape",{node:b.getContentContainerNode(),placeFunc:function(a){b.setContent(a)},relativeParent:b.domNode,json:c,creationParams:e})},_placeReportSectionInCell:function(a,b){var c={"class":"adjustableGrid_inCellSection"};c.json=f.getFieldInfo(b).sectionJson;c.viewModel=a.viewModel;c.theme=a.theme;c.viewPortContainer=a.viewPortContainer;c.parentWidget=b;c.initialWidth=k(b);c.noContentOffset=u.cellHasFloatingTableParent(b);c.onContentLoadingStart=a.onContentLoadingStart.bind(a);c.onContentLoadingEnd=
a.onContentLoadingEnd.bind(a);c.hasFixedLayout=!1;return this._createReportSectionFromParams(a,b,c)},_createReportSectionFromParams:function(a,b,c){c.parentGridCell=b;c=c.json&&c.json.stack&&c.json.type!==A.EMPTY?a.viewModel.layoutBuilder.createElement("section",c,b.getContentContainerNode()):a.viewModel.layoutBuilder.createElement("emptySection",c,b.getContentContainerNode());b.setContent(c);c.setViewMode&&c.setViewMode(a.getViewMode());new l(b,c,[["onWidthChanged","width"],["onHeightChanged","height"]]);
return c},_placeInfographicInCell:function(a,b){var c=f.getFieldInfo(b).infographicJson,d={viewModel:a.viewModel,theme:a.theme,parentWidget:b,width:k(b),height:n(b),adjustElementsWhenResized:u.cellHasFloatingTableParent(b),onContentLoadingStart:a.onContentLoadingStart.bind(a),onContentLoadingEnd:a.onContentLoadingEnd.bind(a)};b=this._createInfographicFromParams(a,b,c,d);b.setViewMode&&b.setViewMode(a.getViewMode());return b},_createInfographicFromParams:function(a,b,c,d){a=a.viewModel.layoutBuilder.createElement("infographic",
{node:b.getContentContainerNode(),placeFunc:function(a){b.setContent(a)},json:c,creationParams:d});new l(b,a,[["onWidthChanged","width"],["onHeightChanged","height"]]);return a}})});