// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/GridDataUtil",["dojo/_base/lang"],function(f){var c={getFieldCellValue:function(a){return a.gridData&&a.gridData[a.column.field]},setFieldCellContent:function(a,b){a.set("value",b);a.gridData[a.column.field]=b},clearFieldInfo:function(a,b){a.fieldInfos&&delete a.fieldInfos[b];a[b]="";c.setNumericDataValue(void 0,a,b)},getNumericCellValue:function(a){return c.getNumericDataValue(a.gridData,a.column.field)},setNumericCellValue:function(a,
b){return c.setNumericDataValue(b,a.gridData,a.column.field)},getNumericDataValue:function(a,b){return a&&b&&a[b+"_numeric"]},setNumericDataValue:function(a,b,c){b[c+"_numeric"]=a},isEmptyCell:function(a){return!a.get("value")&&!a.gridData[a.column.field]&&!c.getFieldInfo(a)},hasSpans:function(a){return c.getColumnSpan(a)||c.getRowSpan(a)},getColumnSpan:function(a){return a.gridData&&a.gridData.columnSpans&&a.gridData.columnSpans[a.column.field]},getRowSpan:function(a){return a.gridData&&a.gridData.rowSpans&&
a.gridData.rowSpans[a.column.field]},getDataColumnSpan:function(a,b){return a&&a.columnSpans&&a.columnSpans[b]},getDataRowSpan:function(a,b){return a&&a.rowSpans&&a.rowSpans[b]},getFieldInfo:function(a){return a&&a.gridData&&a.gridData.fieldInfos&&a.gridData.fieldInfos[a.column.field]},getGridFirstFieldInfo:function(a){return c.getFieldInfo(a.getFieldCells()[0])},setFieldInfo:function(a,b){a.gridData&&(a.gridData.fieldInfos[a.column.field]=b)},provideFieldInfo:function(a){c.setFieldInfo(a,c.getFieldInfo(a)||
{});return c.getFieldInfo(a)},getCellStyle:function(a,b){if(!a||!a.gridData)return null;var d=a.gridData.style&&a.gridData.style.fields&&a.gridData.style.fields[a.column.field];!d&&b&&(d={},c.setCellStyle(a,d));return d},setCellStyle:function(a,b){var c=a.gridData.style=a.gridData.style||{};c.fields=c.fields||{};c.fields[a.column.field]=b},updateCellStyle:function(a,b){a=c.getCellStyle(a,!0);f.mixin(a,b)},copyFieldStyle:function(a,b,d){a=c.getCellStyle(a);b=c.getCellStyle(b,!0);for(var e in d)void 0!==
a[e]&&(b[e]=a[e])},getFieldCellUrl:function(a){if(a.gridData&&a.gridData.urls&&a.column)return a.gridData.urls[a.column.field]},setFieldCellUrl:function(a,b){a.gridData&&a.column&&(a.gridData.urls=a.gridData.urls||{},void 0===b?delete a.gridData.urls[a.column.field]:a.gridData.urls[a.column.field]=b)},getConditionalFormatting:function(a){return(a=c.getFieldInfo(a))&&a.triggerJson},setConditionalFormatting:function(a,b){a=c.provideFieldInfo(a);b&&b.fieldInfo===a&&(b.fieldInfo=f.clone(b.fieldInfo),
delete b.fieldInfo.triggerJson);a.triggerJson=b},isRichTextCell:function(a){a=c.getFieldInfo(a);return!(!a||!a.isRichText)},isVariableFieldCell:function(a){a=c.getFieldInfo(a);return!(!a||!a.hasVariable&&!a.script)},isOnlyVariableFieldCell:function(a){a=c.getFieldInfo(a);return!(!a||!a.hasVariable)},isScriptFieldCell:function(a){a=c.getFieldInfo(a);return!(!a||!a.script)},isUneditableScript:function(a){a=c.getFieldInfo(a);return!!(a&&a.script&&a.script.isUneditableScript)},isNumericVariableFieldCell:function(a){a=
c.getFieldInfo(a);return!(!a||!(a.hasVariable&&"esriFieldTypeString"!==a.type||a.script&&!a.script.isUneditableScript&&"String"!==a.script.type))},isStringVariableFieldCell:function(a){a=c.getFieldInfo(a);return!(!a||!(a.hasVariable&&"esriFieldTypeString"===a.type||a.script&&"String"===a.script.type))},isChartCell:function(a){a=c.getFieldInfo(a);return!(!a||!a.isChart)},isImageCell:function(a){a=c.getFieldInfo(a);return!(!a||!a.isImage)},isMapImageCell:function(a){a=c.getFieldInfo(a);return!!(a&&
a.isImage&&a.imageJson.isMapImage)},isImageTriggerCell:function(a){a=c.getFieldInfo(a);return!!(a&&a.isImage&&a.triggerJson)},isShapeCell:function(a){a=c.getFieldInfo(a);return!(!a||!a.isShape)},isEmptyShapeCell:function(a){a=(a=c.getFieldInfo(a))&&a.shapeJson;return!(!a||a.g&&a.g.length)},isReportSectionCell:function(a){a=c.getFieldInfo(a);return!(!a||!a.isReportSection)},isInfographicCell:function(a){a=c.getFieldInfo(a);return!(!a||!a.isInfographic)}};return c});