// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/InfographicsPage.html":'\x3cdiv class\x3d"esriGEReportPlayer_infographicsPage"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d\'paginationDiv\' class\x3d"esriGEReportPlayer_reportContainerGrid reportContainerPreviewMode"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d\'emptyPlaceholderDiv\' class\x3d"infographicsPage_emptyPlaceholder esriGEAbsoluteStretched esriGEHidden"\x3e${nls.noInfographicsToShow}\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/InfographicsPage","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on dojox/uuid/generateRandomUuid dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/Pagination esri/dijit/geoenrichment/utils/ColorUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/FitUtil esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes ../themes/BackgroundThemeUtil ../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ../sections/sectionUtils/SectionJsonUtil dojo/text!../templates/InfographicsPage.html dojo/i18n!esri/nls/jsapi".split(" "),
function(p,g,q,r,f,D,E,t,u,v,w,x,m,y,z,A,h,B,C,k){function n(a){if(a&&a.children)for(;a.children.length;)a.removeChild(a.children[0])}function l(a){var b=h.getParentBox(a);return b&&b.w?b:B.calcSectionJsonBox(a)}k=k.geoenrichment.dijit.ReportPlayer.Infographics;return p([u,v],{templateString:C,nls:k,viewModel:null,theme:null,parentWidget:null,keepPagePosition:!0,renderBackgroundImage:!1,scaleSectionsToFit:!1,pagination:null,_sections:null,_currentMinWidth:0,_currentMinHeight:0,postCreate:function(){this.inherited(arguments);
this._sections=[];this._createPagination();r[this.scaleSectionsToFit?"add":"remove"](this.domNode,"scaleSectionsToFit")},_createPagination:function(){var a=this;this.pagination=(new w({createItemContainer:g.hitch(this,this._createItemContainer),updateItemContainer:g.hitch(this,this._updateItemContainer),onNodePreDestroy:n,onNodePlaced:g.hitch(this,this._onNodePlaced),scrollAnimation:"slide",cyclicPagination:!0,onPageChanged:function(){a.onPageIndexChanged(a.getCurrentPageIndex())}})).placeAt(this.paginationDiv);
this.own(this.pagination);this.pagination.set("items",[]);this.pagination.startup()},_createItemContainer:function(){var a=f.create("div",{"class":"infographicPage_infographicRoot"});a.style.minWidth=this._currentMinWidth+"px";a.style.minHeight=this._currentMinHeight+"px";return a},_sectionsHash:null,_getSectionByJson:function(a){if(!this.viewModel.dynamicReportInfo)return null;this._sectionsHash=this._sectionsHash||{};a._idInPagination||(a._idInPagination=t());return this._sectionsHash[a._idInPagination]},
_putSectionToHash:function(a,b){this._sectionsHash&&(this._sectionsHash[b._idInPagination]=a)},_updateItemContainer:function(a,b){this._createSectionNode(a,b)},_createSectionNode:function(a,b){if(a&&a.parentNode){n(a);f.empty(a);a.style.minWidth="";a.style.minHeight="";var c=f.create("div",{"class":"infographicPage_infographicRootSectionNode"},a),e=l(b);if(this.scaleSectionsToFit){a.style.width=this._currentMinWidth+2+"px";a.style.height=this._currentMinHeight+2+"px";var d=y.fitBox(e,{w:this._currentMinWidth,
h:this._currentMinHeight});c.style.transform="scale("+d.ratio+")";c.style.webkitTransform="scale("+d.ratio+")";c.style.position="absolute";c.style.left=(this._currentMinWidth-e.w)/2+"px";c.style.top=(this._currentMinHeight-e.h)/2+"px"}else a.style.width=e.w+2+"px",a.style.height=e.h+2+"px";c.style.width=e.w+"px";c.style.height=e.h+"px";(d=this._getSectionByJson(b))&&d.domNode?(d.placeAt(c),m.isNodeInLayout(a)&&this._onNodePlaced(a,b)):(d&&d.destroy(),a={"class":"adjustableGrid_inCellSection"},a.json=
b,a.viewModel=this.viewModel,a.theme=this.theme,a.parentWidget=this,a.initialWidth=e.w,a.hasFixedLayout=!1,d=this.viewModel.layoutBuilder.createElement("section",a,c),this._sections.push(d),d.setViewMode(z.PREVIEW_VALUES),a=!h.getParentBox(b),d.setResizedHeight(e.h,{resizeContentProportionally:a}),d.setWidth(e.w,{resizeContentProportionally:a}),this._putSectionToHash(d,b));this._renderNodeBackground(c,b);return d}},_renderNodeBackground:function(a,b){var c=h.getParentStyle(b),e=this.viewModel.getDocumentDefaultStyles(this.theme);
this.renderBackgroundImage&&e?(a=f.create("div",{"class":"esriGEAbsoluteStretched"},a,"first"),A.applyBackgroundImageFromSettings(a,e.backgroundImage,{documentOptions:this.parentWidget.documentOptions,pos:l(b)})||(a.style.backgroundColor=c&&c.backgroundColor&&!x.isTransparent(c.backgroundColor)?c.backgroundColor:e.backgroundColor)):a.style.backgroundColor=c&&c.backgroundColor},_currentSection:null,_onNodePlaced:function(a,b){(b=this._getSectionByJson(b))&&b.notifyShown();this._currentSection=b;this._isAutoResizeMode&&
this._resizePaginationToFitSelectedElement(a)},getCurrentPageIndex:function(){return this.pagination.get("currentPage")},setCurrentPageIndex:function(a){this.pagination.set("currentPage",a)},showNextPage:function(){this.pagination.set("currentPage","next")},showPreviousPage:function(){this.pagination.set("currentPage","prev")},_prevPageState:null,_sectionJsons:null,getNumItems:function(){return this.pagination.items.length},setItems:function(a){return this._setItems(a)},_setItems:function(a,b){function c(){e._resizeContent();
d.resolve()}var e=this;this._sectionJsons=a;var d=new q,f=this._prevPageState===b&&this.keepPagePosition,g=this.pagination.get("currentPage");this._calcMinWidthAndHeight();this._destroySections();this.pagination.set("items",a);this._prevPageState=b;m[a.length?"hide":"show"](this.emptyPlaceholderDiv);f?(this._resizeContent(),this.pagination.set("currentPage",Math.max(g,0)),setTimeout(c,100)):c();return d.promise},_calcMinWidthAndHeight:function(){this.scaleSectionsToFit?(this._currentMinWidth=this._width-
120-2,this._currentMinHeight=this._height-60-2):(this._currentMinHeight=this._currentMinWidth=0,this._sectionJsons&&this._sectionJsons.forEach(function(a){a=l(a);this._currentMinWidth=Math.max(this._currentMinWidth,a.w);this._currentMinHeight=Math.max(this._currentMinHeight,a.h)},this))},setHeight:function(a){this.domNode.style.height=a+"px"},_width:0,_height:0,_isAutoResizeMode:!0,_isResizing:!1,_pendingResizeNode:null,resize:function(a,b){this._width=a;this._height=b;this._resizeContent()},_checkAutoResizeMode:function(){this._isAutoResizeMode=
0===this._width&&0===this._height},_resizeContent:function(){this._checkAutoResizeMode();this._isResizing=!0;this._pendingResizeNode=null;this._isAutoResizeMode?(this.domNode.style.width="auto",this.domNode.style.height="auto",this.paginationDiv.style.width=this._currentMinWidth+"px",this.paginationDiv.style.height=this._currentMinHeight+"px",this.pagination.resize(),this.paginationDiv.style.width="auto",this.paginationDiv.style.height="auto"):(this._calcMinWidthAndHeight(),this.domNode.style.width=
this._width+"px",this.domNode.style.height=this._height+"px",this.paginationDiv.style.width=this._width+"px",this.paginationDiv.style.height=this._height+"px",this.pagination.resize());this._isResizing=!1;if(this._pendingResizeNode&&this._isAutoResizeMode)this._resizePaginationToFitSelectedElement(this._pendingResizeNode);else this.onResized()},_resizePaginationToFitSelectedElement:function(a){this._isAutoResizeMode&&(this._isResizing?this._pendingResizeNode=a:(this._pendingResizeNode=null,this.paginationDiv.style.width=
a.clientWidth+120+"px",this.paginationDiv.style.height=a.clientHeight+60+"px",this.onResized(!0)))},notifyShown:function(){this._currentSection&&this._currentSection.notifyShown()},onPageIndexChanged:function(a){},onResized:function(a){},_destroySections:function(){this._sections.forEach(function(a){a.destroy()});this._sections.length=0},destroy:function(){this._destroySections();this.inherited(arguments)}})});