// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_ColumnBarChartSeriesCalculator","dojo/_base/lang ../../ThemeCalculator ../../ChartSorting ../../../../supportClasses/conditionalStyling/ConditionalStyleUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder ./_ComparisonUtil ./_AxisBuilder ./_PointLabelUtil".split(" "),function(D,v,A,B,x,E,F,G,n){return{calcSeriesColumnBar:function(a){var f=a.chart,g=a.visualProperties,c=a.seriesItems,r=1===c.length,w=a.seriesItemsWithComparison||
c,h=a.chartType,y=a.comparisonInfo,z=a.themeSettings,t=a.viewModel,l=1===w.length&&a.sorting,x=1<w.length&&g.renderColumnBarsInOppositeDirections,p=[],b={minYValue:Infinity,maxYValue:-Infinity,stackedValues:g.isStacked?[]:null};n.createPointToLabelMap(f);var u={};w.forEach(function(d,c){if(d.points.length){var m={name:d.label,data:[],isComparisonSeries:d.isComparisonSeries,params:{plot:d.isComparisonSeries&&F.getComparisonPlotName(h,y)||void 0}},k=this._collectStatisticsForSeries(a,d,c,b);v.provideMissingIconsForPoints(d.points,
h);d.points.forEach(function(e,a){var b=k.values[a],C=b||0,f=a+1,q;g.conditionalStyling&&(q=(q=B.getConditionalStyle(C,g.conditionalStyling))&&q.backgroundColor);q=q||v.calcColorForPoint(e,d,a,c,r?1:2,h,z,d.isComparisonSeries,y);var l=E.getTooltipInfo(b,n.getPointLabel(e,t),d.label,k.minInSeries,k.maxInSeries,k.valuesSum,k.absValuesSum,k.avgInSeries,g,h,q,g.conditionalStyling,e.fieldInfo,y?!d.isComparisonSeries:void 0),p=u[f]=u[f]||[];p.push(l);l.getGroup=function(){return p};e={x:f,y:C*(x&&c>=w.length/
2?-1:1),originalValue:b,isUnavailableData:isNaN(b),valueProp:"y",unsortedIndex:a,name:n.getPointLabel(e,t),_valuesSumsInSeries:k.absValuesSum,point:e,fill:q,tooltip:l,icon:v.calcIconForPoint(e,q,h),bgIcon:v.calcBackgroundIconForPoint(e,h,z,g),stroke:{width:0}};g.yAxis.showValuesAsWeightsInSeries&&(e.y/=k.absValuesSum/100);m.data.push(e)});l&&l!==A.NONE&&(m.data.sort(function(e,a){return(e.y-a.y)*(l===A.DESC?-1:1)}),m.data.forEach(function(e,a){e.x=a+1}));m.data.forEach(function(a){n.updatePointIndexToLabelMap(f,
a.x,a.point,t)});p.push(m)}},this);b.stackedValues&&(b.stackedValues.sort(function(a,b){return b-a}),b.minYValue=b.stackedValues[b.stackedValues.length-1],b.maxYValue=b.stackedValues[0]);G.prettifyYAxis(b.minYValue,b.maxYValue,g.yAxis.baseLineValue,f,g,h,z,t,p.length);a.plotStat&&(D.mixin(a.plotStat,b),a.plotStat.pointIndexToTooltipsHash=u);return p},_collectStatisticsForSeries:function(a,f,g,c){var r=a.visualProperties,w=a.viewModel,h=a.seriesItems,y=a.previewFeatureIndex,z=a.isMultiFeatureChart,
t=a.excludedSeriesHash,l=a.selectedComparisonIndex,v=a.ge,p=a.chartType;a=1<h.length&&r.renderColumnBarsInOppositeDirections;var b=2===h.length&&a?x.CHART_DATA_SMOOTH:null;r.conditionalStyling&&(a=B.getStatistics(r.conditionalStyling))&&h.length&&(b=x.getChartData(a,h[0].points.length,b,!1));var u=[],d=0,n=0,m=1E6,k=-1E6;f.points.forEach(function(a,c){a=x.getPreviewValue(a,c,g,!1,p,r,w,z?c:y,b,f.isComparisonSeries,l,v,!1);a=(u[c]=a)||0;t&&t[f.label]||(d+=a,n+=Math.abs(a),m=Math.min(m,a),k=Math.max(k,
a))});f.points.forEach(function(a,b){a=u[b];a=r.yAxis.showValuesAsWeightsInSeries?a/n*100:a;c.stackedValues?(c.stackedValues[b]=c.stackedValues[b]||0,c.stackedValues[b]+=a):(c.minYValue=Math.min(a,c.minYValue),c.maxYValue=Math.max(a,c.maxYValue))});return{values:u,valuesSum:d,absValuesSum:n,minInSeries:m,maxInSeries:k,avgInSeries:d/f.points.length}}}});