// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/TableParser","dojo/_base/lang esri/dijit/geoenrichment/utils/JsonXmlConverter esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/RichTextJsonUtil ../../../supportClasses/DocumentOptions ../../ConversionUtil ../../../sections/SectionTypes ./AlignParser ./_HiddenCellsCollector".split(" "),function(E,x,F,G,e,f,H,y){function I(a,b,c,m,f){if(a.spannedWidths||a.spannedHeights){var n=
a.spannedWidths?a.spannedWidths.split(";").map(function(a){return e.ptToPx(a)}):[e.ptToPx(a.width)];a=a.spannedHeights?a.spannedHeights.split(";").map(function(a){return e.ptToPx(a)}):[e.ptToPx(a.height)];for(var l=0;l<n.length;l++)for(var p=0;p<a.length;p++){var k=c[f+l],q=b[m+p],k=q.style.fields[k.field]=q.style.fields[k.field]||{};k.width=n[l];k.height=a[p]}}}var u={parseTableCellAttributes:function(a,b,c){c=c.tableDefaultStyles;b=b||{};a.overrideStyle&&(b.overrideStyle=a.overrideStyle);a.pad&&
(b.horizontalPadding=e.ptToPx(a.pad));a.vpad&&(b.verticalPadding=e.ptToPx(a.vpad));a.angle&&(b.angle=Number(a.angle)||0);H.parseAlign(a,b);a.width&&(b.width=e.ptToPx(a.width));a.height&&(b.height=e.ptToPx(a.height));E.mixin(b,e.ptToPxObj(e.parseStyleString(a.style)));if(b.overrideStyle&&c){c=c.getStyle(b.overrideStyle);for(var f in c)delete b[f]}u._parseBorderProperties(a,b);return b},_SIDES:["Top","Right","Bottom","Left"],_parseBorderProperties:function(a,b){u._SIDES.forEach(function(c){a["border"+
c+"Width"]&&(a["border"+c+"Color"]&&(b["border"+c+"Color"]=a["border"+c+"Color"]),a["border"+c+"Width"]&&(b["border"+c+"Width"]=e.ptToPx(a["border"+c+"Width"])),a["border"+c+"Style"]&&(b["border"+c+"Style"]=a["border"+c+"Style"]),b["border"+c+"Opacity"]=Number(a["border"+c+"Opacity"])||1)})}},n={getElement:function(a,b){var c=e.pxToPt(G.getPageBox(b.templateJson.documentOptions).contentW);if(a.attributes.widths&&Number(a.attributes.width)>c){var m=e.splitTrim(a.attributes.widths,";",!0),B=Number(a.attributes.width)-
c,C=Number(m[m.length-1]);C>B&&(m[m.length-1]=C-B,a.attributes.widths=m.join(";"),a.attributes.width=c)}var l=0,p=a.attributes.widths?e.splitTrim(a.attributes.widths,";",!0).map(function(a){return{field:"field"+l++,style:{width:e.ptToPx(a)}}}):[],k=Number(a.attributes.fixedColumns)||0,q=Number(a.attributes.dynamicColumns)||0,d=[],t,v,z,w;(function(){a.tags&&(1.1<=b.revisionVersion?a.tags.forEach(function(a){if("tr"===a.name)d.push(a);else switch(a.attributes.type){case f.TABLE_BACKGROUND:t=a;break;
case f.TABLE_FOREGROUND:v=a;break;case f.TABLE_BACKGROUND_FLOATING_PANELS:z=a;break;case f.TABLE_FOREGROUND_FLOATING_PANELS:case f.TABLE_FLOATING_PANELS:w=a}}):a.tags.forEach(function(a){"tr"===a.name?d.push(a):"background"===a.name?t=a:"foreground"===a.name?v=a:"floatingElements"===a.name&&(w=a)}))})();if(d){var A=d.map(function(){return{style:{fields:{}},fieldInfos:{}}}),D=y.collectHiddenCells(d,b);d.forEach(function(a,c){var g=A[c];a.attributes&&a.attributes.height&&(g.style.height=e.ptToPx(a.attributes.height));
if(a.tags&&a.tags.length){var f=0;if(q){var n=[],m=[],d=0;a.tags.forEach(function(a){for(;y.isHidden(D,d,c);)d++;d<k?n.push(a):m.push(a);d++});var l=Math.round((p.length-k)/q);a.tags=n;for(var t=0;t<l;t++)a.tags=a.tags.concat(m)}a.tags.forEach(function(a){function e(a){a=a.tags&&1===a.tags.length&&a.tags[0];if(!a||!a.tags)return null;"b"===a.name?m.fontWeight="bold":"i"===a.name?m.fontStyle="italic":"u"===a.name&&(m.textDecoration="underline");return"b"===a.name||"i"===a.name||"u"===a.name?e(a)||
{tag:a.tags[0],parentTag:a}:null}function n(a){x.isRichText(a)?g.fieldInfos[d]=F.createFieldInfoFromRichText(a):g[d]=x.unrichHTML(a)}for(;y.isHidden(D,f,c);)f++;if(p[f]){var d=p[f].field,h=a.attributes||{},m=g.style.fields[d]={};u.parseTableCellAttributes(h,m,b);h.width&&I(h,A,p,c,f);var k=Number(h.colspan),h=Number(h.rowspan);k&&(g.columnSpans=g.columnSpans||{},g.columnSpans[d]=k);h&&(g.rowSpans=g.rowSpans||{},g.rowSpans[d]=h);var l=function(a){var b,c,d;if(a.tags&&a.tags.length)if(d=a.tags.filter(function(a){return"br"!==
a.name}),(c=d[0])&&"trigger"===c.name&&d[1]&&"d"===d[1].name)b=c,c=d[1];else{var f=e(a);c=f&&f.tag||d[0];a=f&&f.parentTag||a}return{firstTag:c,triggerTag:b,parentTag:a,hasMultipleTags:d&&1<d.length}}(a);a=l.firstTag;var k=l.parentTag,h=l.triggerTag,l=l.hasMultipleTags,r;if(l&&!h){var q=b.parsers.getParser("field").parseRichTextTag(k,b);q&&(g.fieldInfos[d]=q,r=!0)}if(a&&!r)if(h=b.parsers.getParser("field").parseField(a,k,h,b),"number"===typeof h)g[d]=h+"",r=!0;else if(h)g.fieldInfos[d]=h,r=!0;else if("chart"===
a.name)r=!0;else if("img"===a.name)r=!0;else if("text"===a.name)g[d]=a.attributes.name,r=!0;else if("a"===a.name&&a.tags&&"#text"===a.tags[0].name){if(h=a.attributes.href)g.urls=g.urls||{},g.urls[d]=h,g[d]=a.tags[0].text,r=!0}else"#text"!==a.name||l||(n(a.text),r=!0);r||n(x.getInnerHTML(k));f++}})}})}c={id:"table",backgroundSectionJson:t&&n._parseTableBackgroundForeground(t,b),foregroundSectionJson:v&&n._parseTableBackgroundForeground(v,b),backgroundFloatingTablesSectionJson:z&&n._parseFloatingPanels(z,
b),foregroundFloatingTablesSectionJson:w&&n._parseFloatingPanels(w,b),data:{columns:p,data:A||[]},style:{width:e.ptToPx(a.attributes.width),left:e.ptToPx(a.attributes.left),spaceBefore:e.ptToPx(a.attributes.spaceBefore),spaceAfter:e.ptToPx(a.attributes.spaceAfter),alternatingStyle:a.attributes.alternatingStyle},attributes:{}};k&&(c.attributes.fixedColumns=k);q&&(c.attributes.dynamicColumns=q);a.attributes.fixedRows&&(c.attributes.fixedRows=Number(a.attributes.fixedRows)||0);a.attributes.dynamicRows&&
(c.attributes.dynamicRows=Number(a.attributes.dynamicRows)||0);c.attributes.inSectionRole=a.attributes.inSectionRole;return c},_parseTableBackgroundForeground:function(a,b){a.attributes=a.attributes||{};a.attributes.type=f.DETAILS;return b.parsers.getParser("section").parseSection(a,b)},_parseFloatingPanels:function(a,b){a.attributes=a.attributes||{};a.attributes.type=f.DETAILS;return b.parsers.getParser("section").parseSection(a,b)}};n.parseTableCellAttributes=u.parseTableCellAttributes;return n});