// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/LocatorPointsController",["dojo/_base/declare","dojo/on","dojo/sniff","dojo/when","dijit/Destroyable"],function(h,f,g,k,l){return h(l,{_info:null,constructor:function(a){this._info=a;this._layerIndexes={};this._rendererJsons={};this._mapInfos={};this._graphicLayerInfos={}},getCalculatorName:function(){return this._info.calculatorName},getVariableObjects:function(){return this._info.variableObjects},getLayerID:function(){return this._info.layerID},
getLayerUrl:function(){return this._info.layerUrl},getLayerName:function(){return this._info.layerName},_rendererJsons:null,getRendererJson:function(a){return this._rendererJsons[a]},setRendererJson:function(a,b){this._rendererJsons[a]=b},_layerIndexes:null,getLayerIndex:function(a){return this._layerIndexes[a]},setLayerIndex:function(a,b){this._layerIndexes[a]=b},_mapInfos:null,getMapInfo:function(a){return this._mapInfos[a]},getMapInfos:function(){var a=[],b;for(b in this._mapInfos)a.push(this._mapInfos[b]);
return a},setMapInfo:function(a,b){this._mapInfos[a]=b},_getPointIndexForCellFunc:null,_getCellForPointAtFunc:null,_highlightedCell:null,setLocatorTableCallbacks:function(a){this._getPointIndexForCellFunc=a.getPointIndexForCellFunc;this._getCellForPointAtFunc=a.getCellForPointAtFunc},registerLocatorTable:function(a){var b=this,c;a.set("highlightRowsOnHover",!0);f(a.domNode,"mouseover,mousemove",function(){var d=a.getOverFieldCell();d&&d!==c&&(c=d,b._highlightGraphicForFieldCell(c))});f(a.domNode,
"mouseout",function(){b._highlightGraphicForFieldCell(null);c=null})},_highlightRowForGraphic:function(a,b){this._highlightedCell&&(this._highlightedCell.parentGrid&&this._highlightedCell.parentGrid.setCellRowHighlighted(this._highlightedCell,!1),this._highlightedCell=null);b&&this._getCellForPointAtFunc&&(a=a.getPointIndexForGraphicFunc(b),k(this._getCellForPointAtFunc(a),function(a){a&&a.parentGrid&&(a.parentGrid.setCellRowHighlighted(a,!0),this._highlightedCell=a)}.bind(this)))},_graphicLayerInfos:null,
setLocatorPointsLayer:function(a,b,c,d){this._unSetInfo(a);b={graphicsLayer:b,getPointIndexForGraphicFunc:d.getPointIndexForGraphicFunc,getGraphicForPointAtFunc:d.getGraphicForPointAtFunc,setGraphicHighlightedFunc:d.setGraphicHighlightedFunc,layerMouseOverHandle:null,layerMouseOutHandle:null,highlightedGraphic:null};this._graphicLayerInfos[a]=b;this._addLayerListeners(b,c)},_addLayerListeners:function(a,b){var c=this,d=a.graphicsLayer,e;a.layerMouseOverHandle=f(g("touch")?b:d,g("touch")?"mouse-down, mouse-move":
"mouse-move",function(b){b.graphic&&b.graphic._graphicsLayer===d&&e!==b.graphic&&(a.layerMouseOutHandle&&a.layerMouseOutHandle.remove(),a.layerMouseOutHandle=null,e&&a.setGraphicHighlightedFunc(e,!1),e=b.graphic,c._highlightRowForGraphic(a,e),a.setGraphicHighlightedFunc(e,!0),a.layerMouseOutHandle=f.once(d,"mouse-out",function(b){c._highlightRowForGraphic(a,null);e&&a.setGraphicHighlightedFunc(e,!1);e=null}))})},_highlightGraphicForFieldCell:function(a){for(var b in this._graphicLayerInfos){var c=
this._graphicLayerInfos[b];c.highlightedGraphic&&(c.setGraphicHighlightedFunc(c.highlightedGraphic,!1),c.highlightedGraphic=null);if(a){var d=this._getPointIndexForCellFunc(a);if(d=c.getGraphicForPointAtFunc(d))c.setGraphicHighlightedFunc(d,!0),c.highlightedGraphic=d}}},setPointVisibleAt:function(a,b){for(var c in this._graphicLayerInfos){var d=this._graphicLayerInfos[c].getGraphicForPointAtFunc(a);if(d)d[b?"show":"hide"]()}},_unSetInfo:function(a){var b=this._graphicLayerInfos[a];delete this._graphicLayerInfos[a];
b&&(b.layerMouseOverHandle&&b.layerMouseOverHandle.remove(),b.layerMouseOutHandle&&b.layerMouseOutHandle.remove())},_unSetLayers:function(){Object.keys(this._graphicLayerInfos).forEach(this._unSetInfo.bind(this));this._graphicLayerInfos={}},destroy:function(){this._unSetLayers()}})});