// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/LocatorPointsBuilder","dojo/_base/Color dojo/_base/lang dojo/when esri/graphic esri/layers/GraphicsLayer esri/renderers/SimpleRenderer esri/renderers/jsonUtils esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/jsonUtils esri/dijit/PopupTemplate ./LayerInfoLoader ../../../../dataProvider/supportClasses/AreaDataUtil ../../../../dataProvider/supportClasses/AreasInfoTemplateBuilder esri/dijit/geoenrichment/utils/ColorUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(g,r,t,u,x,v,y,l,m,w,z,A,B,C,D,n){n=n.geoenrichment.dijit.ReportPlayer.ReportPlayer;var d={},p={_defaultLocatorSymbol:null,_defaultLocatorSymbolHighlighted:null,getDefaultLocatorSymbol:function(){this._defaultLocatorSymbol||(this._defaultLocatorSymbol=new l(l.STYLE_CIRCLE,10,new m(m.STYLE_SOLID,new g([255,0,0,1]),2),new g([255,0,0,.75])));return this._defaultLocatorSymbol},getDefaultLocatorSymbolHighlighted:function(){this._defaultLocatorSymbolHighlighted||(this._defaultLocatorSymbolHighlighted=
new l(l.STYLE_CIRCLE,11,new m(m.STYLE_SOLID,new g([255,255,255,1]),2),new g([255,50,50,1])));return this._defaultLocatorSymbolHighlighted}};d.addLocatorPoints=function(b,c){b.locatorPointsControllers&&b.locatorPointsControllers.forEach(function(e){var k=B.getAreaDataObjectCalculator(b.fieldData.areaData[0],e.getCalculatorName());if(k){var a=[k.data].concat(k.comparisonLevels);if(a.length){var h=e.getRendererJson(b.calculatorFieldName),f=new x,g=h?y.fromJson(h):new v(p.getDefaultLocatorSymbol());f.setRenderer(g);
a.forEach(function(a,b){if(a.Point||a.Polygon){var q=e.getVariableObjects().map(function(b){return{label:b.alias,value:a[b.fieldName]}}),q=new z({title:"",fieldInfos:[],description:C.buildAttributesTable(null,q)}),c=r.mixin({},a);delete c.Point;delete c.Polygon;c.__pointIndex=b;b=new u({attributes:c,geometry:JSON.parse(a.Point||a.Polygon)});b.setSymbol(h?w.fromJson(h.symbol):p.getDefaultLocatorSymbol());b.setInfoTemplate(q);f.add(b)}});d._registerLayer(f,b.map,e,b);c.registerLayerInfo({layer:f,preferredIndex:e.getLayerIndex(b.calculatorFieldName),
geometryType:k.data.Point?"esriGeometryPoint":"esriGeometryPolygon"});d._provideNameForLayer(f,e,b)}}})};d._registerLayer=function(b,c,e,k){var a=e.getRendererJson(k.calculatorFieldName),h,f;if(a){a=r.clone(a.symbol);switch(a.type){case "esriSMS":a.size*=1.1;var d=D.getHighlightColor(new g(a.color.slice(0,3)));a.color[0]=d.r;a.color[1]=d.g;a.color[2]=d.b;break;case "esriPMS":a.width*=1.1,a.height*=1.1,a.xoffset*=1.1,a.yoffset*=1.1,f=new u,f.setSymbol(new l(l.STYLE_SQUARE,Math.max(a.width,a.height)/
.75,new m(m.STYLE_SOLID,new g([255,255,0,.7]),2),new g([0,0,0,0])))}h=w.fromJson(a)}else h=p.getDefaultLocatorSymbolHighlighted();e.setLocatorPointsLayer(k.calculatorFieldName,b,c,{getPointIndexForGraphicFunc:function(a){return a.attributes&&a.attributes.__pointIndex},getGraphicForPointAtFunc:function(a){var c;b.graphics.some(function(b){if(b.attributes&&b.attributes.__pointIndex===a)return c=b,!0});return c},setGraphicHighlightedFunc:function(a,c){f&&b.remove(f);!c&&a.__originalSymbol?(a.setSymbol(a.__originalSymbol),
delete a.__originalSymbol):c&&!a.__originalSymbol&&(a.__originalSymbol=a.symbol,a.setSymbol(h),b.remove(a),f&&(f.setGeometry(a.geometry),b.add(f)),b.add(a))}})};d._provideNameForLayer=function(b,c,e){var d=c.getLayerUrl(),a=c.getLayerID();c=(c=c.getLayerName())&&{name:c};d?t(c||A.getInfo(d),function(a){b.name=a&&a.name||n.locatorLayerLegendTitle;b.onVisibilityChange()}):t(c||e.geClient&&e.geClient.getLayerInfo(e.countryID,a),function(a){b.name=a&&a.name||n.locatorLayerLegendTitle;b.onVisibilityChange()})};
d.getDefaultLocatorRendererJson=function(){return(new v(p.getDefaultLocatorSymbol())).toJson()};return d});