// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/graphic","dojo/_base/declare dojo/_base/lang dojo/has ./kernel ./domUtils ./lang ./InfoTemplate ./geometry/jsonUtils ./symbols/jsonUtils".split(" "),function(f,h,w,x,k,l,y,z,A){function v(){}f=f(null,{declaredClass:"esri.Graphic",constructor:function(a,b,c,d){a&&!a.declaredClass?(this.geometry=a.geometry?z.fromJson(a.geometry):null,this.symbol=a.symbol?A.fromJson(a.symbol):null,this.attributes=a.attributes||null,this.infoTemplate=a.infoTemplate?new y(a.infoTemplate):null):(this.geometry=
a,this.symbol=b,this.attributes=c,this.infoTemplate=d)},_geomVersion:0,_shape:null,_bgShape:null,_dataAttrs:null,_layer:null,_sourceLayer:null,_graphicsLayer:null,_suspended:!1,size:null,visible:!0,_aggregationSourceLayer:null,_aggregationInfo:null,_computedAttributes:null,_computedVersion:null,_computedGeomVersion:null,setSize:function(a){this.size=a},getAggregationSourceLayer:function(){return this._aggregationSourceLayer},setAggregationSourceLayer:function(a){this._aggregationSourceLayer=a},isAggregate:function(){return!!this._aggregationInfo},
getAggregationInfo:function(){return this._aggregationInfo},setAggregationInfo:function(a){this._aggregationInfo=a},getChildGraphics:function(){var a=this.getAggregationSourceLayer();return a?a.getChildGraphics(this):[]},getDojoShape:function(){return this._shape},getShapes:function(){var a=[];this._shape&&a.push(this._shape);this._bgShape&&a.push(this._bgShape);return a},getNode:function(){var a=this._shape&&this._shape.getNode();return a&&a.nodeType?a:null},getNodes:function(){var a=this.getShapes(),
b,c,d=a.length,g=[];for(c=0;c<d;c++)(b=a[c]&&a[c].getNode())&&b.nodeType&&g.push(b);return g},getLayer:function(){return this._layer},getSourceLayer:function(){return this._sourceLayer||this._layer},clone:function(){var a=new this.constructor(this.toJson());a.visible=this.visible;a._layer=this._layer;a._sourceLayer=this._sourceLayer;a._aggregationSourceLayer=this._aggregationSourceLayer;a._aggregationInfo=this._aggregationInfo;return a},draw:function(){var a=this._graphicsLayer;a&&a._draw(this,!0);
return this},setGeometry:function(a){this.geometry=a;this._geomVersion++;var b=this._graphicsLayer;b&&(b._updateExtent(this),this.draw(),a&&"polyline"===a.type&&b._updateSVGMarkers());return this},setSymbol:function(a,b){var c=this._graphicsLayer,d=this._shape;this.symbol=a;c&&(b&&d&&c._removeShape(this),this.draw());return this},setAttributes:function(a){this.attributes=a;this._clearCache();return this},setInfoTemplate:function(a){this.infoTemplate=a;return this},getInfoTemplate:function(){return this._getEffInfoTemplate()},
_getEffInfoTemplate:function(){var a=this.getLayer();return this.infoTemplate||a&&a.infoTemplate},getTitle:function(){var a=this.getInfoTemplate(),b=a&&a.title;if(h.isFunction(b))b=b.call(a,this);else if(h.isString(b))var c=(a=this.getLayer())&&a._getDateOpts,b=l.substitute(this.attributes,b,{first:!0,dateFormat:c&&c.call(a)});return b},getContent:function(){var a=this.getInfoTemplate(),b=a&&a.content;if(h.isFunction(b))b=b.call(a,this);else if(h.isString(b))var c=(a=this.getLayer())&&a._getDateOpts,
b=l.substitute(this.attributes,b,{dateFormat:c&&c.call(a)});return b},attr:function(a,b){null==b||this._dataAttrs||(this._dataAttrs={});this._dataAttrs&&(this._dataAttrs[a]=b,this._setDataAttr(a,b));return this},_isSuspended:function(){return this._suspended},_suspend:function(){this._suspended=!0;this.draw()},_resume:function(){this._suspended=!1;this.draw()},show:function(){this.visible=!0;this.attr("data-hidden");var a,b,c;if(this.getShapes().length)for(a=this.getNodes(),c=a.length,b=0;b<c;b++)k.show(a[b]);
else this.draw();(a=this._graphicsLayer)&&a._graphicVisibilityChanged(this);return this},hide:function(){this.visible=!1;this.attr("data-hidden","");var a=this._graphicsLayer,b,c,d;if(a){if("canvas-2d"===a.surfaceType)a._removeShape(this);else if(b=this.getNodes(),d=b.length)for(c=0;c<d;c++)k.hide(b[c]);a._graphicVisibilityChanged(this)}return this},toJson:function(){var a={};this.geometry&&(a.geometry=this.geometry.toJson());this.attributes&&(a.attributes=h.mixin({},this.attributes));this.symbol&&
(a.symbol=this.symbol.toJson());this.infoTemplate&&(a.infoTemplate=this.infoTemplate.toJson());return a},_setDataAttr:function(a,b){var c=this.getNodes(),d,g=c.length;for(d=0;d<g;d++)this._setDOMDataAttr(c[d],a,b)},_setDOMDataAttr:function(a,b,c){null==c?a.removeAttribute(b):a.setAttribute(b,c)},_applyDataAttrs:function(){var a=this._dataAttrs;if(a){var b=this.getNodes(),c,d=b.length;for(c=0;c<d;c++)for(var g in a)this._setDOMDataAttr(b[c],g,a[g])}},_getViewInfo:function(a){return(a=(a=a||this.getLayer())&&
a.getMap())&&a._getViewInfo()},_getDataValue:function(a,b,c,d,g){var f=b.id,h=this.attributes,r=a.field,t=b.isNumeric,e=null;if(f){var m=this._computedAttributes,n=this._computedVersion,p=this._computedGeomVersion;d=this._getViewInfo(d);var u=b.dependsOnView||b.isJSFunc,q=b.dependsOnGeometry,k=q&&!!g;m||(m=this._computedAttributes={});u&&!n&&(n=this._computedVersion={});q&&!p&&(p=this._computedGeomVersion={});var l=u&&n[f]!==d._version||q&&p[f]!==this._geomVersion,e=m[f];if(void 0===e||l||k)e=null,
b.hasExpr?(e=c.createExecContext(this,d),(a=e.vars.$feature)&&g&&(a._geometry=g),e=c.executeFunction(b.compiledFunc,e)):b.isJSFunc?e=r(this,a):h&&(e=h[r],t&&this._isValidNumber(e)&&(b=a.normalizationType||"field",c=e,e=null,g=a.normalizationTotal,a=h[a.normalizationField],"log"===b&&0!==c?e=Math.log(c)*Math.LOG10E:"percent-of-total"===b&&this._isValidNumber(g)&&0!==g?e=c/g*100:"field"===b&&this._isValidNumber(a)&&0!==a&&(e=c/a))),e=this._sanitizeValue(e,t),k||(m[f]=e,u&&(n[f]=d._version),q&&(p[f]=
this._geomVersion))}else h&&(e=this._sanitizeValue(h[r],t));return e},_sanitizeValue:function(a,b){b&&!this._isValidNumber(a)&&(a=null);return a},_isValidNumber:function(a){return"number"===typeof a&&!isNaN(a)&&Infinity!==a&&-Infinity!==a},_clearCache:function(){this._computedAttributes=this._computedVersion=this._computedGeomVersion=null}});f.prototype.getShape=f.prototype.getDojoShape;v.prototype=f.prototype;f.simpleConstructor=v;w("extend-esri")&&(x.Graphic=f);return f});