// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/PopupManager","./geometry/Extent ./geometry/ScreenPoint ./kernel ./layerUtils ./tasks/query dijit/registry dojo/_base/array dojo/_base/declare dojo/_base/Deferred dojo/_base/lang dojo/has dojo/on dojo/promise/all dojo/Stateful require".split(" "),function(E,y,F,D,G,H,h,t,u,x,I,J,K,L,M){var z;t=t(L,{declaredClass:"esri.PopupManager",enabled:!1,map:null,_mapClickHandle:null,_featureLayersCache:{},constructor:function(a){this._mapClickHandler=x.hitch(this,this._mapClickHandler)},setMap:function(a){if(this.map)if(a!==
this.map)this.unsetMap();else return;this.map=a;this._setupClickHandler()},unsetMap:function(){this.map&&(this.map=null);this._mapClickHandle&&(this._mapClickHandle.remove(),this._mapClickHandle=null)},getMapLayer:function(a){var b;if(a&&(b=a.getLayer())&&(a=b.id,this._featureLayersCache[a])){var c=a.lastIndexOf("_");-1<c&&(a=a.substring(0,c),b=this.map.getLayer(a))}return b},_enabledSetter:function(a){this.enabled=a;this._setupClickHandler()},_setupClickHandler:function(){this._mapClickHandle&&(this._mapClickHandle.remove(),
this._mapClickHandle=null);this.enabled&&this.map&&(this._mapClickHandle=this.map.on("click",this._mapClickHandler))},_mapClickHandler:function(a){var b=this.map.infoWindow,c=a.graphic;b&&this.map.loaded&&(b.clearFeatures&&b.setFeatures?this._showPopup(a):c&&c.getInfoTemplate()&&this._showInfoWindow(c,a.mapPoint))},_showPopup:function(a){var b=this.map,c=b.infoWindow,d=this,g=[],f=[b.graphics].concat(h.map(b.graphicsLayerIds,b.getLayer,b));h.forEach(f,function(a){a&&a.loaded&&a.infoTemplate&&!a.suspended&&
g.push(a)});var m=[];h.forEach(b.layerIds,function(a){(a=b.getLayer(a))&&a.loaded&&!a.suspended&&(d._isImageServiceLayer(a)&&a.infoTemplate?g.push(a):"esri.layers.WMSLayer"===a.declaredClass&&a.getFeatureInfoURL?g.push(a):"esri.layers.ArcGISDynamicMapServiceLayer"!==a.declaredClass&&"esri.layers.ArcGISTiledMapServiceLayer"!==a.declaredClass||!a.infoTemplates||m.push(a))});this._getSubLayerFeatureLayers(m).then(function(f){g=g.concat(f);var l=null;a.graphic&&a.graphic.getInfoTemplate()&&!d._isImageServiceLayer(a.graphic._layer)&&
(l=a.graphic);if(g.length||l){var e=d._calculateClickTolerance(g),n=a.screenPoint;f=b.toMap(new y(n.x-e,n.y+e));var e=b.toMap(new y(n.x+e,n.y-e)),q=new E(f.x,f.y,e.x,e.y,b.spatialReference);if(q=q.intersects(b.extent)){var m=new G,p=!!l,v=!0;f=h.map(g,function(c){m.timeExtent=c.useMapTime?b.timeExtent:null;var e=d._isReductionEnabled(c);c=e?c.getFeatureReductionLayer():c;var f;if(d._isImageServiceLayer(c))m.geometry=a.mapPoint,v=!1,f=c.queryVisibleRasters(m,{rasterAttributeTableFieldPrefix:"Raster.",
returnDomainValues:!0}),f.addCallback(function(){var a=c.getVisibleRasters();p=p||0<a.length;return a});else if("esri.layers.WMSLayer"===c.declaredClass){f=new u;var g=c._getPopupGraphic(b,a.screenPoint);g?(f.resolve([g]),p=!0):f.resolve([])}else d._featureLayersCache[c.id]||"function"===typeof c.queryFeatures&&(0===c.currentMode||1===c.currentMode)?(m.geometry=q,f=c.queryFeatures(m),f.addCallback(function(a){a=a.features;a=h.filter(a,function(a){return a.visible});p=p||0<a.length;return a})):(f=
new u,g=h.filter(c.graphics,function(a){return a&&a.visible&&q.intersects(a.geometry)}),e&&d._isParentLayer(c,l)&&(e=d._findGraphicById(g,l,"cluster_id"))&&(l=e),p=p||0<g.length,f.resolve(g));return f});l&&(e=new u,e.resolve([l]),f.unshift(e));h.some(f,function(a){return!a.isFulfilled()})||p?(c.setFeatures(f),c.show(a.mapPoint,{closestFirst:v})):(c.hide(),c.clearFeatures())}}})},_getSubLayerFeatureLayers:function(a,b){var c=b||new u,d=[];b=a.length;var g=Math.floor(this.map.extent.getWidth()/this.map.width),
f=this.map.getScale(),m=!1,t=this,l=0;a:for(;l<b;l++){var e=a[l],n=e.dynamicLayerInfos||e.layerInfos;if(n){var q=null;e._params&&(e._params.layers||e._params.dynamicLayers)&&(q=e.visibleLayers);for(var q=D._getVisibleLayers(n,q),y=D._getLayersForScale(f,n),p=n.length,v=0;v<p;v++){var A=n[v],r=A.id,w=e.infoTemplates[r];if(!A.subLayerIds&&w&&w.infoTemplate&&-1<h.indexOf(q,r)&&-1<h.indexOf(y,r)){if(!z){m=!0;break a}var B=e.id+"_"+r,k=this._featureLayersCache[B];k&&k.loadError||(k||((k=w.layerUrl)||(k=
A.source?this._getLayerUrl(e.url,"/dynamicLayer"):this._getLayerUrl(e.url,r)),k=new z(k,{id:B,drawMode:!1,mode:z.MODE_SELECTION,outFields:this._getOutFields(w.infoTemplate),resourceInfo:w.resourceInfo,source:A.source}),this._featureLayersCache[B]=k),k.setDefinitionExpression(e.layerDefinitions&&e.layerDefinitions[r]),k.setGDBVersion(e.gdbVersion),k.setInfoTemplate(w.infoTemplate),k.setMaxAllowableOffset(g),k.setUseMapTime(!!e.useMapTime),e.layerDrawingOptions&&e.layerDrawingOptions[r]&&e.layerDrawingOptions[r].renderer&&
k.setRenderer(e.layerDrawingOptions[r].renderer),d.push(k))}}}}if(m){var x=new u;M(["./layers/FeatureLayer"],function(a){z=a;x.resolve()});x.then(function(){t._getSubLayerFeatureLayers(a,c)})}else{var C=[];h.forEach(d,function(a){if(!a.loaded){var b=new u;J.once(a,"load, error",function(){b.resolve()});C.push(b.promise)}});C.length?K(C).then(function(){d=h.filter(d,function(a){return!a.loadError&&a.isVisibleAtScale(f)});c.resolve(d)}):(d=h.filter(d,function(a){return a.isVisibleAtScale(f)}),c.resolve(d))}return c.promise},
_getLayerUrl:function(a,b){var c=a.indexOf("?");return-1===c?a+"/"+b:a.substring(0,c)+"/"+b+a.substring(c)},_getOutFields:function(a){var b;a.info&&"esri.dijit.PopupTemplate"===a.declaredClass?(b=[],h.forEach(a.info.fieldInfos,function(a){var c=a.fieldName&&a.fieldName.toLowerCase();c&&"shape"!==c&&0!==c.indexOf("relationships/")&&b.push(a.fieldName)})):b=["*"];return b},_calculateClickTolerance:function(a){var b=6,c,d;h.forEach(a,function(a){if(c=a.renderer)"esri.renderer.SimpleRenderer"===c.declaredClass?
((d=c.symbol)&&d.xoffset&&(b=Math.max(b,Math.abs(d.xoffset))),d&&d.yoffset&&(b=Math.max(b,Math.abs(d.yoffset)))):"esri.renderer.UniqueValueRenderer"!==c.declaredClass&&"esri.renderer.ClassBreaksRenderer"!==c.declaredClass||h.forEach(c.infos,function(a){(d=a.symbol)&&d.xoffset&&(b=Math.max(b,Math.abs(d.xoffset)));d&&d.yoffset&&(b=Math.max(b,Math.abs(d.yoffset)))})});return b},_showInfoWindow:function(a,b){var c=this.map.infoWindow,d=a.geometry;b=d&&"point"===d.type?d:b;d=a.getContent();c.setTitle(a.getTitle());
d&&x.isString(d.id)&&(a=H.byId(d.id))&&a.set&&/_PopupRenderer/.test(a.declaredClass)&&a.set("showTitle",!1);c.setContent(d);c.show(b)},_findGraphicById:function(a,b,c){var d,g=(b=b.attributes)&&b[c];h.some(a,function(a){var b=a.attributes;b&&b[c]===g&&(d=a);return!!d});return d},_isParentLayer:function(a,b){b=b&&b.getLayer();return a&&b===a},_isReductionEnabled:function(a){return a&&a.isFeatureReductionActive&&a.isFeatureReductionActive()},_isImageServiceLayer:function(a){return"esri.layers.ArcGISImageServiceLayer"===
a.declaredClass||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass}});I("extend-esri")&&(F.PopupManager=t);return t});