// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/request","require dojo/_base/array dojo/_base/config dojo/_base/Deferred dojo/_base/lang dojo/_base/url dojo/_base/xhr ./core/request/script dojo/request/iframe dojo/dom-construct dojo/io-query ./kernel ./config ./sniff ./lang ./urlUtils ./deferredUtils".split(" "),function(U,H,I,u,x,V,y,fa,ga,ba,W,g,ha,r,J,v,C){function F(a){a=new V(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function ia(a){return this._xhr?this._xhr.getResponseHeader(a):null}function ja(a,e){var b=W.objectToQuery(a.content);
b&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+b);if(2E3<a.url.length){if("data:"!==a.url.toLowerCase().slice(0,5))return a=new u,a.reject(x.mixin(Error(),{message:"When using responseType 'image', URL length cannot exceed 2000 characters."})),a;if(3E6<a.url.length)return a=new u,a.reject(x.mixin(Error(),{message:"When using responseType 'image', data URL length cannot exceed 3000000 characters."})),a}var d=new Image;e.allowImageDataAccess&&(d.crossOrigin=a.withCredentials?"use-credentials":"anonymous");
var g=!1,n=new u(function(a){g=!0;d.onload=d.onerror=d.onabort=null;d.src=""});e=function(a){d.onload=d.onerror=d.onabort=null;g||n.reject(Error("Unable to load the resource"))};d.onload=function(){d.onload=d.onerror=d.onabort=null;g||n.resolve(this)};d.onerror=e;d.onabort=e;d.alt="";d.src=a.url;return n}function L(a,e,b,d){var X=!1,n=!1,z,h;J.isDefined(e)&&(x.isObject(e)?(X=!!e.useProxy,n=!!e.usePost,z=e.crossOrigin):X=!!e);a=x.mixin({},a);a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));10>r("ie")&&
!ka.test(a.url)&&(a.url=encodeURI(a.url));var p=a.content,f=a.url,k=b&&a.form,A=q;z=J.isDefined(z)?z:A.useCors;a.load=function(c){var b;c&&(c.error?(b=x.mixin(Error(),c.error),b.log=!!I.isDebug):"error"===c.status&&(b=x.mixin(Error(),c),b.log=!!I.isDebug),b&&(a.failOk=!b.log,J.isDefined(b.httpCode)||(b.httpCode=b.code)));return b||c};a.error=function(c,b){b&&b.xhr&&b.xhr.abort();c instanceof Error||(c=x.mixin(Error(),c));c.log=!!I.isDebug;a.failOk=!c.log;A.errorHandler(c,b);return c};a._token&&(a.content=
a.content||{},a.content.token=a._token);var t=0,m;p&&f&&(m=W.objectToQuery(p),t=m.length+f.length+1,r("esri-url-encodes-apostrophe")&&(t=m.replace(/'/g,"%27").length+f.length+1));a.timeout=J.isDefined(a.timeout)?a.timeout:A.timeout;a.handleAs=a.handleAs||"json";try{var D,c,l=z&&v.canUseXhr(a.url)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),ca=v.hasSameOrigin(a.url,window.location.href)||l,K=n||b||t>A.postLength?!0:!1,da=ca||-1===a.handleAs.indexOf("json")||!a.callbackParamName||b?
!1:!0,E=v.getProxyRule(a.url)||A.alwaysUseProxy||X||!("image"===a.handleAs&&!e.allowImageDataAccess||da&&!K||ca)?!0:!1;b&&!r("esri-file-upload")&&!E&&l&&(E=!0);if(E)if(D=v.getProxyUrl(f,z),c=D.path,D._xo&&(l=!0),!K&&c.length+1+t>A.postLength&&(K=!0),a.url=c+"?"+f,K)a.content=x.mixin(D.query||{},p);else{var ea=W.objectToQuery(x.mixin(D.query||{},p));ea&&(a.url+="?"+ea);a.content=null}if(!da||K||E){var M=a.headers;!l||M&&M.hasOwnProperty("X-Requested-With")||(M=a.headers=M||{},M["X-Requested-With"]=
null);if(b){var w=a.callbackParamName||"callback.html",F=a.callbackElementName||"textarea",N,S,O,T,L=k.elements?k.elements.length:0,G;if(p=a.content)for(N in p.token&&-1<f.toLowerCase().indexOf("/sharing/servers/")&&(f+=(-1===f.indexOf("?")?"?":"\x26")+"token\x3d"+p.token,a.url=E?c+"?"+f:f,delete p.token),p)if(O=p[N],J.isDefined(O)){S=null;for(T=0;T<L;T++)if(G=k.elements[T],G.name===N){S=G;break}S?S.value=O:d?k.append(N,O):k.appendChild(ba.create("input",{type:"hidden",name:N,value:O}))}if(r("esri-file-upload")){H.forEach(k.elements,
function(a){a.name===w&&k.removeChild(a)});var P=d?k:new FormData(k);if(11<r("safari")&&"entries"in P&&"delete"in P){d=[];for(var B=P.entries(),Y=B.next();!Y.done;){var Z=Y.value;Z[1]instanceof File&&""===Z[1].name&&d.push(Z[0]);Y=B.next()}d.forEach(function(a){P.delete(a)})}a.contentType=!1;a.postData=P;delete a.form}else{k.enctype="multipart/form-data";9>r("ie")&&(k.encoding="multipart/form-data");k.method="post";H.some(k.elements,function(a){return a.name===w})||k.appendChild(ba.create("input",
{type:"hidden",name:w,value:F}));if(-1!==f.toLowerCase().indexOf("addattachment")||-1!==f.toLowerCase().indexOf("updateattachment"))f+=(-1===f.indexOf("?")?"?":"\x26")+w+"\x3d"+F,a.url=E?c+"?"+f:f;delete a.content}}if(l&&!a.hasOwnProperty("withCredentials")&&"with-credentials"===q.useCors){var f=E?c:f,C=v.canUseXhr(f,!0),aa=-1<C?q.corsEnabledServers[C]:null;if(aa&&aa.hasOwnProperty("withCredentials"))aa.withCredentials&&(a.withCredentials=!0);else if(g.id){var R=g.id.findServerInfo(f);R&&R.webTierAuth&&
(a.withCredentials=!0)}}a=Q?Q(a):a;if("image"===a.handleAs)return ja(a,e);if(K){if(b&&!r("esri-file-upload")){h=new u(function(){U.cancel()});var U=ga.post(a.url,a).then(function(a){h.resolve(a)}).otherwise(function(a){h.reject(a)});h.addCallback(function(c){return a.load(c)});h.addErrback(function(c){return a.error(c)});return h}!E&&r("safari")&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+"_ts\x3d"+(new Date).getTime()+ma++);return y.post(a)}return y.get(a)}a=Q?Q(a):a;a.jsonp=a.callbackParamName;
a.query=a.content;h=new u(function(){V.cancel()});var V=fa.get(a.url,a).then(function(a){h.resolve(a)}).otherwise(function(a){h.reject(a)});h.addCallback(function(c){return a.load(c)});h.addErrback(function(c){return a.error(c)});return h}catch(la){return h=new u,h.errback(a.error(la)),h}}function G(a){var e=q.corsStatus,b=v.canUseXhr(a,!0);-1<b&&q.corsEnabledServers.splice(b,1);var d=new u;d.reject({log:!!I.isDebug});e[F(a)]=d.promise;return b}function B(a){var e=q.corsStatus;try{var b=F(a);if(q.corsDetection&&
q.useCors&&r("esri-cors")&&a&&-1!==a.toLowerCase().indexOf("/rest/services")&&!v.hasSameOrigin(a,window.location.href)&&!v.canUseXhr(a)){if(e[b]&&!e[b].isCanceled())return e[b];var d=new u(C._dfdCanceller);e[b]=d.promise;var g=y.get({url:a.substring(0,a.toLowerCase().indexOf("/rest/")+6)+"info",content:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null},timeout:1E3*q.corsDetectionTimeout});d._pendingDfd=g;g.then(function(e){e?(v.canUseXhr(a)||q.corsEnabledServers.push(b),d.resolve()):
d.reject()},function(a){d.reject(a)});return d.promise}}catch(n){console.log("esri._detectCors: an unknown error occurred while detecting CORS support")}return na}function R(a){Q=a}function w(a,e,b,d){function m(a){a._pendingDfd=L(b,d,A,k);if(!a._pendingDfd){a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;var c=Error("Deferred object is missing");c.log=!!I.isDebug;a.errback(c);a._pendingDfd=null;return a}a._pendingDfd.addCallback(function(b){if(!b)return b;var c=a._pendingDfd&&a._pendingDfd.ioArgs&&
a._pendingDfd.ioArgs.xhr;if(!c)return b;if(c=c.getResponseHeader("Content-Type"))if(c=c.toLowerCase(),-1===c.indexOf("text/plain")&&-1===c.indexOf("application/json"))return b;if(b instanceof ArrayBuffer&&750>=b.byteLength)c=new Blob([b]);else if(b instanceof Blob&&750>=b.size)c=b;else return b;var d=new u,l=new FileReader;l.readAsText(c);l.onloadend=function(){var a;if(!l.error)try{var c=JSON.parse(l.result);c.error&&(a=c.error)}catch(pa){}a?(a=x.mixin(Error(),a),a.log=!!I.isDebug,null==a.httpCode&&
(a.httpCode=a.code),d.reject(a)):d.resolve(b)};return d.promise}).addCallback(function(b){a.ioArgs=a._pendingDfd&&a._pendingDfd.ioArgs;d.returnFullResponse&&(b={data:b,_xhr:a.ioArgs&&a.ioArgs.xhr,getHeader:ia});a.callback(b);a._pendingDfd=null}).addErrback(function(c){var l,e,f;c&&(l=c.code,e=c.subcode,f=(f=c.messageCode)&&f.toUpperCase());if(c&&403==l&&(4==e||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&-1===c.message.toLowerCase().indexOf("permission"))){if(!b._ssl){b._ssl=b._sslFromServer=
!0;w(a,!0,b,d);return}}else if(c&&415==c.status){if(G(b.url),!b._err415){b._err415=1;w(a,!0,b,d);return}}else if(g.id&&-1!==H.indexOf(g.id._errorCodes,l)&&!g.id._isPublic(b.url)&&!z&&(403!=l||-1===H.indexOf(oa,f)&&(!J.isDefined(e)||2==e&&b._token))){a._pendingDfd=g.id.getCredential(b.url,{token:b._token,error:c});a._pendingDfd.addCallback(function(c){b._token=c.token;b._credential=c;b._ssl=b._sslFromServer||c.ssl;w(a,!0,b,d)}).addErrback(function(b){a.errback(b);a._pendingDfd=null});return}a.ioArgs=
a._pendingDfd&&a._pendingDfd.ioArgs;a.isFulfilled()||a.errback(c);a._pendingDfd=null})}var n=b.form,z=d.disableIdentityLookup,h=d._preLookup,p=!1;if(r("esri-workers")&&!1!==q.useWorkers)if(!0===d.useWorkers||!0===q.useWorkers)p=!0;else if(d.workerOptions){var f=d.workerOptions;if(f.callback||f.worker&&f.worker.worker instanceof Worker)p=!0}var k=n&&r("esri-file-upload")&&n instanceof FormData,A=n&&(n.elements?H.some(n.elements,function(a){return"file"===a.type}):k),B=-1!==b.url.toLowerCase().indexOf("token\x3d")||
b.content&&b.content.token||A&&H.some(n.elements,function(a){return"token"===a.name})?1:0;if(!e){a.addCallback(function(a){if((/\/sharing\/rest\/accounts\/self/i.test(b.url)||/\/sharing\/rest\/portals\/self/i.test(b.url))&&!B&&!b._token&&a.user&&a.user.username){q.webTierAuthServers.push(F(b.url));a=q.corsEnabledServers;var c=v.canUseXhr(b.url,!0),d={host:F(b.url),withCredentials:!0};if(-1===c)a.push(d);else{var e=a[c];e instanceof RegExp?(d.host=e,a.splice(c,1,d)):"object"===typeof e?e.withCredentials=
!0:a.splice(c,1,d)}}if(a=b._credential)if(c=(c=g.id.findServerInfo(a.server))&&c.owningSystemUrl)c=c.replace(/\/?$/,"/sharing"),(a=g.id.findCredential(c,a.userId))&&-1===g.id._getIdenticalSvcIdx(c,a)&&a.resources.splice(0,0,c)});a.addBoth(function(a){delete b._credential;!a||r("ie")&&a.nodeType||(a._ssl=b._ssl)});var C=b.load,D=b.error;C&&a.addCallback(function(b){var c=a._pendingDfd,c=c&&c.ioArgs;return C.call(c&&c.args,b,c)});D&&a.addErrback(function(b){var c=a._pendingDfd,c=c&&c.ioArgs;return D.call(c&&
c.args,b,c)})}!g.id||B||b._token||g.id._isPublic(b.url)||z&&!h||!(e=g.id.findCredential(b.url))||(b._token=e.token,b._ssl=e.ssl);p?d.workerOptions&&d.workerOptions.worker?(t||(t=y),y=d.workerOptions.worker,m(a)):U(["./workers/RequestClient"],function(b){t||(t=y);if(d.workerOptions){var c=d.workerOptions;y=b.getClient(c.callback,c.cbFunction)}else y=b.getClient();m(a)}):(t&&(y=t,t=null),m(a));return a}function m(a,e){a.url=v.fixUrl(a.url);e=e||{};var b=new u(C._dfdCanceller),d=B(a.url);b._pendingDfd=
d;d.always(function(d){d&&"cancel"===d.dojoType?b.reject(d):w(b,!1,a,e)});return b}var t=null,Q,q=ha.defaults.io,oa=["COM_0056","COM_0057"],ma=0,ka=/%[0-9A-F]{2}/i,na=function(){var a=new u;a.resolve();return a.promise}();m._makeRequest=L;m._processRequest=w;m._disableCors=G;m._detectCors=B;m.setRequestPreCallback=R;r("extend-esri")&&(g.request=m,g._makeRequest=L,g._processRequest=w,g._disableCors=G,g._detectCors=B,g.setRequestPreCallback=R);return m});