// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/sniff",["dojo/_base/sniff","dojo/global","./kernel"],function(a,b,d){var e=a("ff"),g=a("ie"),n=void 0===g&&7<=a("trident"),p=a("edge"),l=a("webkit"),h=a("opera"),m=a("chrome"),q=a("safari"),k=navigator.userAgent,f;(f=k.match(/(iPhone|iPad|CPU)\s+OS\s+(\d+\_\d+)/i))&&a.add("esri-iphone",parseFloat(f[2].replace("_",".")));(f=k.match(/Android\s+(\d+\.\d+)/i))&&a.add("esri-android",parseFloat(f[1]));(f=k.match(/Fennec\/(\d+\.\d+)/i))&&a.add("esri-fennec",parseFloat(f[1]));0<=k.indexOf("BlackBerry")&&
0<=k.indexOf("WebKit")&&a.add("esri-blackberry",1);a.add("esri-touch",a("esri-iphone")||a("esri-android")||a("esri-blackberry")||6<=a("esri-fennec")||(e||l)&&document.createTouch?!0:!1);(f=k.match(/Android|webOS|iPhone|iPad|iPod|BlackBerry|Opera Mini|IEMobile/i))&&a.add("esri-mobile",f);a.add("esri-pointer",navigator.pointerEnabled||navigator.msPointerEnabled);d._getDOMAccessor=function(a){var c="";e?c="Moz":l?c="Webkit":g?c="ms":h&&(c="O");return c+a.charAt(0).toUpperCase()+a.substr(1)};a.add("esri-phonegap",
!!b.cordova);a.add("esri-cors",a("esri-phonegap")||b.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest);a.add("esri-file-upload",b.FormData&&b.FileList?!0:!1);a.add("esri-script-sandbox",function(){return"MessageChannel"in b&&"HTMLIFrameElement"in b&&"sandbox"in HTMLIFrameElement.prototype});a.add("esri-secure-context",function(){if("isSecureContext"in b)return b.isSecureContext;if(b.location&&b.location.origin)return 0===b.location.origin.indexOf("https:")});a.add("esri-wasm","WebAssembly"in
b);a.add("esri-workers",b.Worker?!0:!1);a.add("esri-featurelayer-webgl-labeling",!1);a.add("esri-transforms",n||p||9<=g||3.5<=e||4<=m||3.1<=q||10.5<=h||3.2<=a("esri-iphone")||2.1<=a("esri-android"));a.add("esri-transitions",n||p||10<=g||4<=e||4<=m||3.1<=q||10.5<=h||3.2<=a("esri-iphone")||2.1<=a("esri-android"));a.add("esri-transforms3d",n||p||10<=e||12<=m||4<=q||3.2<=a("esri-iphone")||3<=a("esri-android"));a.add("esri-url-encodes-apostrophe",function(){if(b.document)return!1;var a=b.document.createElement("a");
a.href="?'";return-1<a.href.indexOf("?%27")});3>a("esri-android")&&(a.add("esri-transforms",!1,!1,!0),a.add("esri-transitions",!1,!1,!0),a.add("esri-transforms3d",!1,!1,!0));a.add("esri-will-change",a("esri-transforms")&&(52<=m||11.1<=q));d._css=function(b){var c=a("esri-transforms3d");void 0!==b&&null!==b?c=b:c&&(m||q&&!a("esri-iphone"))&&(c=!1);var d=c?"translate3d(":"translate(",f=c?m?",-1px)":",0px)":")",k=c?"scale3d(":"scale(",n=c?",1)":")",p=c?"rotate3d(0,0,1,":"rotate(",r=c?"matrix3d(":"matrix(",
t=c?",0,0,":",",u=c?",0,0,0,0,1,0,":",",v=c?",0,1)":")";return{names:{transition:l&&"-webkit-transition"||e&&"MozTransition"||h&&"OTransition"||g&&"msTransition"||"transition",transform:l&&"-webkit-transform"||e&&"MozTransform"||h&&"OTransform"||g&&"msTransform"||"transform",transformName:l&&"-webkit-transform"||e&&"-moz-transform"||h&&"-o-transform"||g&&"-ms-transform"||"transform",origin:l&&"-webkit-transform-origin"||e&&"MozTransformOrigin"||h&&"OTransformOrigin"||g&&"msTransformOrigin"||"transformOrigin",
endEvent:l&&"webkitTransitionEnd"||e&&"transitionend"||h&&"oTransitionEnd"||g&&"MSTransitionEnd"||"transitionend"},translate:function(a,b){return d+a+"px,"+b+"px"+f},scale:function(a){return k+a+","+a+n},rotate:function(a){return p+a+"deg)"},matrix:function(a){return r+a.xx+","+a.xy+t+a.yx+","+a.yy+u+a.dx.toFixed(10)+(e&&59>=e?"px,":",")+a.dy.toFixed(10)+(e&&59>=e?"px":"")+v},getScaleFromMatrix:function(a){if(!a)return 1;a=a.toLowerCase();var b=-1<a.indexOf("matrix3d")?"matrix3d(":"matrix(";return Number(a.substring(b.length,
a.indexOf(",")))}}};a("extend-esri")&&(d.isiPhone=a("esri-iphone"),d.isAndroid=a("esri-android"),d.isFennec=a("esri-fennec"),d.isBlackBerry=a("esri-blackberry"),d.isTouchEnabled=a("esri-touch"),d.isPointerEnabled=a("esri-pointer"),d._hasCors=a("esri-cors"),d._hasFileUpload=a("esri-file-upload"),d._hasTransforms=a("esri-transforms"),d._hasTransitions=a("esri-transitions"),d._has3DTransforms=a("esri-transforms3d"));return a});