// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/urlUtils","dojo/_base/lang dojo/_base/array dojo/_base/url dojo/global dojo/io-query ./kernel ./lang ./config ./sniff dojo/i18n!./nls/jsapi".split(" "),function(g,v,n,k,q,h,r,w,p,x){var c={},l=w.defaults.io,y=/^[a-z][a-z0-9\+\-\.]*:/i,t=/^\s*http:/i,u=/^\s*https:/i,z=/:\d+$/,A=/^https?:\/\/[^/]+\.arcgis.com\/sharing(\/|$)/i;c.isHTTP=function(a){var b=k.location.protocol;return null==a?"http:"===b||"https:"===b:a?"https:"===b:"http:"===b};c.getProtocolForWebResource=function(a){return c.isHTTP()?
k.location.protocol:a?"https:":"http:"};c.urlToObject=function(a){var b={},c=new n(a),d=a.indexOf("?");null===c.query?b={path:a,query:null}:(b.path=a.substring(0,d),b.query=q.queryToObject(c.query));c.fragment&&(b.hash=c.fragment,null===c.query&&(b.path=b.path.substring(0,b.path.length-(c.fragment.length+1))));return b};c.getProxyUrl=function(a,b){var e=g.isString(a)?0===g.trim(a).toLowerCase().indexOf("https:"):a,d=l.proxyUrl,f,m=x.io.proxyNotSet;g.isString(a)&&(a=c.getProxyRule(a))&&(d=a.proxyUrl);
if(!d)throw console.log(m),Error(m);e&&!1!==b&&p("esri-secure-context")&&(b=d,0!==b.toLowerCase().indexOf("http")&&(b=c.getAbsoluteUrl(b)),b=b.replace(/^http:/i,"https:"),c.canUseXhr(b)&&(d=b,f=1));d=c.urlToObject(d);d._xo=f;return d};c.addProxy=function(a){var b=c.getProxyRule(a),e;b?e=c.urlToObject(b.proxyUrl):l.alwaysUseProxy&&(e=c.getProxyUrl());e&&(b=c.urlToObject(a),a=e.path+"?"+b.path,(e=q.objectToQuery(g.mixin(e.query||{},b.query)))&&(a+="?"+e));return a};c.addProxyRule=function(a){var b=
a.urlPrefix=c.urlToObject(a.urlPrefix).path.replace(/([^\/])$/,"$1/").replace(/^https?:\/\//ig,"").toLowerCase(),e=l.proxyRules,d,f=e.length,m,g=f;for(d=0;d<f;d++)if(m=e[d].urlPrefix,0===b.indexOf(m)){if(b.length===m)return-1;g=d;break}else 0===m.indexOf(b)&&(g=d+1);e.splice(g,0,a);return g};c.getProxyRule=function(a){var b=l.proxyRules,e=b.length,d=c.urlToObject(a).path.replace(/([^\/])$/,"$1/").replace(/^https?:\/\//ig,"").toLowerCase(),f;for(a=0;a<e;a++)if(0===d.indexOf(b[a].urlPrefix)){f=b[a];
break}return f};c.hasSameOrigin=function(a,b,c){a=a.toLowerCase();b=b.toLowerCase();var d=k.location.href.toLowerCase();a=0===a.indexOf("http")?new n(a):d=new n(d);b=0===b.indexOf("http")?new n(b):g.isString(d)?new n(d):d;return(c||a.scheme===b.scheme)&&a.host===b.host&&a.port===b.port};c.canUseXhr=function(a,b){var e=p("esri-phonegap")?!0:!1,d=c.hasSameOrigin,f=l.corsEnabledServers,g,h=-1;!e&&p("esri-cors")&&f&&f.length&&(e=v.some(f,function(b,c){b=!b||"object"!==typeof b||b instanceof RegExp?b:
b.host;if(b instanceof RegExp){if(b.test(a))return h=c,!0}else if(b&&(g=0!==b.trim().toLowerCase().indexOf("http"),d(a,g?"http://"+b:b)||g&&d(a,"https://"+b)))return h=c,!0;return!1}));return b?h:e};c.getAbsoluteUrl=function(a){var b=c.getProtocolForWebResource();return g.isString(a)&&!y.test(a)?0===a.indexOf("//")?b+a:0===a.indexOf("/")?b+"//"+k.location.host+a:h._appBaseUrl+a:a};c.fixUrl=function(a){a=g.trim(a);a=c.getAbsoluteUrl(a);a=c.normalizeSlashes(a);a=a.replace(/^(https?:\/\/)(arcgis\.com)/i,
"$1www.$2");a=c.downgradeToHTTP(a);return a=c.upgradeToHTTPS(a)};c.normalize=function(a){return c.fixUrl(a)};c.normalizeSlashes=function(a){if(/^https?:\/\//i.test(a)){var b,c,d=a.indexOf("?");-1<d?(b=a.slice(0,d),c=a.slice(d+1)):b=a;a=b.replace(/\/{2,}/g,"/");a=a.replace("/","//");c&&(a+="?"+c)}return a};c.downgradeToHTTP=function(a){return c.isHTTP(!1)&&u.test(a)&&c.hasSameOrigin(k.location.href,a,!0)&&!c.canUseXhr(a)?a.replace(u,"http:"):a};c.upgradeToHTTPS=function(a){var b=l.httpsDomains,e=c.isHTTP(!1),
d=c.isHTTP(!0);if(!t.test(a))return a;a=g.trim(a);var f=a.indexOf("/",7),f=-1===f?a:a.slice(0,f),f=f.toLowerCase().slice(7);if(z.test(f))if(r.endsWith(f,":80"))f=f.slice(0,-3),a=a.replace(":80","");else return a;if(e&&f===k.location.host&&(!A.test(a)||!c.canUseXhr(a)))return a;e=!1;if(d&&f===k.location.host)e=!0;else if(b)for(d=0;d<b.length;d++){var h=b[d];if(f===h||r.endsWith(f,"."+h)){e=!0;break}}e||!p("esri-secure-context")||l.alwaysUseProxy||c.getProxyRule(a)||(e=!0);e&&(a=a.replace(t,"https:"));
return a};p("extend-esri")&&(g.mixin(h,c),h._getProxyUrl=c.getProxyUrl,h._getProxiedUrl=c.addProxy,h._hasSameOrigin=c.hasSameOrigin,h._canDoXOXHR=c.canUseXhr,h._getAbsoluteUrl=c.getAbsoluteUrl,h.fixUrl=c.fixUrl);return c});