// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/ReportContainerGrid.html":'\x3cdiv class\x3d"esriGEReportPlayer_reportContainerGrid esriGENonSelectable"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"mainContainer" class\x3d"reportContainerGrid_mainContainer"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"fillerContainer" class\x3d"reportContainerGrid_gridZoomFillerContainer"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"scalableContainer" class\x3d"reportContainerGrid_gridZoomScalableContainer"\x3e\r\n                \x3cdiv data-dojo-attach-point\x3d"stackContainer" class\x3d"reportContainerGrid_gridStackContainer"\x3e\x3c/div\x3e\r\n            \x3c/div\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/reportContainerGrid/ReportContainerGrid","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when dojo/on dojo/sniff dojo/dom-construct dojo/dom-class dojo/dom-geometry dojo/dom-style dojo/store/Memory dijit/_WidgetBase dijit/_TemplatedMixin ./_HiddenContentSupport ./_ScrollSupport ./_ZoomSupport ../grid/coreUtils/GridDataUtil ./utils/QueryUtil ./utils/SerializationManager ./utils/ContentLoadingEventManager ../supportClasses/DocumentOptions ../supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder ../themes/BackgroundThemeUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes dojo/text!../templates/ReportContainerGrid.html".split(" "),
function(q,m,r,g,I,t,d,h,f,e,u,v,w,x,y,z,n,k,A,B,C,D,E,F,G,p,H){return q([v,w,x,y,z],{templateString:H,viewModel:null,theme:null,parentWidget:null,showWatermark:!0,isSourceContainer:!0,documentOptions:null,loadingManager:null,serializationManager:null,renderOptions:{center:!1,minTop:0,minRight:0,minBottom:0,minLeft:0},_grids:null,_enableAsyncRendering:!0,postCreate:function(){this.serializationManager=(new this._getSerializationManagerClass)(this);this._grids=[];this.inherited(arguments);this.updateLayout();
this.setViewMode(p.PREVIEW_VALUES);this.isSourceContainer&&h.add(this.domNode,"reportContainerGrid_sourceContainer")},_getSerializationManagerClass:function(){return A},setDocumentOptions:function(a,b){this.documentOptions&&m.mixin(this.documentOptions,a);this.updateLayout(b)},updateLayout:function(a){var b=this;this.documentOptions&&(this._updateContainerSize(),this._grids.forEach(function(c,l){a&&void 0!==a.pageIndex&&a.pageIndex!==l||(b._updateGridWrappingNodeForCurrentDocumentLayout(c),c.setMaxWidth(b._getAllowedPageWidth()),
c.resizeToFitAllowedWidth(),c.resizeToFitHeight(b._getPageHeight()))}),this._syncFillerContainer())},getFirstPageDomNode:function(){var a=this.stackContainer.children[0];return a&&a.children[0]},getPageDomNodes:function(){return this._getGridContainers()},_getGridContainers:function(){for(var a=[],b=0;b<this.stackContainer.children.length;b++){var c=this.stackContainer.children[b];c&&a.push(c.children[0])}return a},_placeGridContainer:function(a,b){var c=d.create("div",{"class":"reportContainerGrid_gridContainerWrapper"});
(b=void 0!==b&&this.stackContainer.children[b])?d.place(c,b,"before"):d.place(c,this.stackContainer);d.place(a,c);a.backgroundImage=d.create("div",{"class":"reportContainerGrid_stackContainerBackgroundImage esriGEAbsoluteStretched"},a);t("ie")||this.viewModel.dynamicReportInfo||!this.showWatermark||(this._sampleWatermarkDiv=d.create("div",{"class":"sampleValuesWatermark esriGEAbsoluteStretched"},a,"first"))},getGridContainer:function(a){return this._getGridContainer(a)},_getGridContainer:function(a){a=
a.isFloatingTable?a.parentGrid:a;return a.domNode&&a.domNode.parentNode},_getGridContainerWrapper:function(a){return(a=this._getGridContainer(a))&&a.parentNode},_updateGridWrappingNodeForCurrentDocumentLayout:function(a){a.isEmptyTable()&&e.set(a.domNode,{width:this._getAllowedPageWidth()+"px",height:this._getPageHeight()+"px"});if(a=this._getGridContainer(a)){var b=this.viewModel.getDocumentDefaultStyles(this.theme);e.set(a,{paddingLeft:(this.documentOptions.left||0)+"px",paddingRight:(this.documentOptions.right||
0)+"px",paddingTop:(this.documentOptions.top||0)+"px",paddingBottom:(this.documentOptions.bottom||0)+"px",backgroundColor:this.documentOptions.backgroundColor||b&&b.backgroundColor})}E.applyBackgroundImageFromSettings(a.backgroundImage,b&&b.backgroundImage)},_updateContainerSize:function(){var a=0===this._heigth?"auto":e.get(this.domNode,"height")+"px";e.set(this.mainContainer,"height",a);e.set(this.mainContainer,"maxWidth",this._maxWidth?this._maxWidth+"px":"");e.set(this.mainContainer,"maxHeight",
this._maxHeight?this._maxHeight+"px":"");this._syncFillerContainer()},getCurrentPageDim:function(){return C.getPageBox(this.documentOptions)},_getAllowedPageWidth:function(){return this.getCurrentPageDim().contentW},_getPageHeight:function(){return this.getCurrentPageDim().contentH},getCanvasOffsets:function(){var a=f.position(this.mainContainer),b=f.position(this.fillerContainer);return{l:b.x-a.x,r:a.x+a.w-b.x-b.w,w:b.w,h:b.h}},_currentPageIndex:-1,getFullWidth:function(){var a=this.getFirstPageDomNode();
return f.getMarginBox(a).w+f.getMarginExtents(this.stackContainer).w},getFullHeight:function(){var a=this.getFirstPageDomNode();return f.getMarginBox(a).h+f.getMarginExtents(this.stackContainer).h},getNumberOfPages:function(){return this._grids.length},showAllPages:function(){this.showPageAt(-1)},showPageAt:function(a){this._grids.forEach(function(b,c){var l=-1===a||a===c;(c=F[l?"showNodeFromBackground":"hideNodeInBackground"](this._getGridContainerWrapper(b),"reportContainerPage_"+c))&&this.own(c);
this.isCurrentContainer()&&l&&b.notifyShown()},this);this._currentPageIndex=a;this._syncFillerContainer()},getShownGrid:function(){return this._grids[this._currentPageIndex]},getCurrentPageIndex:function(){return this._currentPageIndex},getGrids:function(){return this._grids},isCurrentContainer:function(){return!1},_width:0,_heigth:0,resize:function(a,b){this._width=void 0===a?this._width:a;this._heigth=void 0===b?this._heigth:b;void 0!==a&&e.set(this.domNode,"width",0===this._width?"auto":this._width+
"px");void 0!==b&&e.set(this.domNode,"height",0===this._heigth?"auto":this._heigth+"px");this._updateContainerSize()},_maxWidth:0,_maxHeight:0,setMaxWidth:function(a){this._maxWidth=a},setMaxHeight:function(a){this._maxHeight=a},screenToPageCoords:function(a,b){return k.screenToPageCoords(this,a,b)},getLayoutCells:function(a){a=a||{};return k.getLayoutCells(this,{sectionFuncName:a.sectionFuncName,floatingCells:!1!==a.floatingCells})},getCellPageGrid:function(a){return a&&a.parentGrid?a.parentGrid.isFloatingTable?
a.parentGrid.parentGrid:a.parentGrid:null},clear:function(a){this._grids.forEach(function(a,c){a.destroy()},this);this._grids.length=0;this.stackContainer&&d.empty(this.stackContainer);this._syncFillerContainer()},_removeGrid:function(a){if(a){var b=this._getGridContainerWrapper(a);a.destroy();b&&d.destroy(b);a=this._grids.indexOf(a);this._grids.splice(a,1);this._syncFillerContainer()}},removeGridAt:function(a){this._removeGrid(this._grids[a])},getGridJsonAt:function(a){return this._grids[a].toJson()},
setHeight:function(a){e.set(this.mainContainer,"height",a+"px")},_viewMode:null,getViewMode:function(){return this._viewMode},setViewMode:function(a){this._viewMode!==a&&(this._viewMode=a,a===p.EDIT?(h.add(this.domNode,"reportContainerEditMode"),h.remove(this.domNode,"reportContainerPreviewMode")):(h.remove(this.domNode,"reportContainerEditMode"),h.add(this.domNode,"reportContainerPreviewMode")),this._updateContainerSize(),this._grids.forEach(function(b,c){b.setViewMode(a)},this))},hasFocusedChild:function(){return k.hasFocusedChild(this)},
collectFieldInfos:function(a){return k.collectFieldInfos(this,a)},createGridFromSectionTableJson:function(a,b,c){void 0!==b&&"replace"===c&&this._removeGrid(this._grids[b]);c=d.create("div",{"class":"reportContainerGrid_stackContainer"});this._placeGridContainer(c,b);a=this._createGridFromTableJson(a,c);a.setMaxWidth(this._getAllowedPageWidth());a.setSettings({style:{width:this._getAllowedPageWidth(),left:0,spaceBefore:0,spaceAfter:0}});this._updateGridWrappingNodeForCurrentDocumentLayout(a);void 0!==
b?this._grids.splice(b,0,a):this._grids.push(a);this._syncFillerContainer();return a},_getGridClass:function(){return this.viewModel.layoutBuilder.getClass("grid")},_createGridFromTableJson:function(a,b){var c=this;a.data=a.data||{};a=new (this._getGridClass())(m.mixin({"class":"outerAdjustableGrid",fieldCellClass:"outerAdjustableGridCell",viewModel:this.viewModel,theme:this.theme,parentWidget:this,viewPortContainer:this.mainContainer,reportContainerPageNode:b,columns:a.data.columns||[],store:new u({data:a.data.data||
[],idProperty:"id"}),backgroundSectionJson:a.backgroundSectionJson,foregroundSectionJson:a.foregroundSectionJson,backgroundFloatingTablesSectionJson:a.backgroundFloatingTablesSectionJson,foregroundFloatingTablesSectionJson:a.foregroundFloatingTablesSectionJson,stickToRight:!0,keepGridSizeWhenResized:!1,looseResize:!0,layoutDefaults:{defaultRowHeight:250,rowMinHeight:30,columnMinWidth:50},renderBordersFromTheme:!0,hasRealBorders:!0,inheritThemeBackground:!1,enableBackgroundForeground:!0,enableAsyncRendering:this._enableAsyncRendering,
_preRenderFieldCell:function(a){n.getFieldInfo(a)||c.isSourceContainer||n.setFieldInfo(a,c.createEmptySectionJson())},_postCreateFieldCell:function(a){c._postCreateFieldCell(a)},onContentLoadingStart:function(){c.loadingManager&&c.loadingManager.onContentLoadingStart()},onContentLoadingEnd:function(){c.loadingManager&&c.loadingManager.onContentLoadingEnd()}},this._getGridCreationParams(b)),d.create("div",null,b));a.setViewMode(this._viewMode);return a},_postCreateFieldCell:function(a){},createEmptySectionJson:function(){return D.createFieldInfoFromSection({type:G.EMPTY})},
_getGridCreationParams:function(a){return null},notifyShown:function(){g(this.serializationManager.notifyShown(),function(){this.getShownGrid()&&this.getShownGrid().notifyShown()}.bind(this))},getVisualState:function(){return{pages:this._grids.map(function(a,b){return{grid:a.getVisualState()}})}},setVisualState:function(a){a&&a.pages&&a.pages.length===this._grids.length&&this._grids.forEach(function(b,c){b.setVisualState(a.pages[c].grid)})},_pagePromise:null,_contentPromise:null,fromJson:function(a,
b){b=b||{};var c=this;this._enableAsyncRendering=!b.renderSync;this._contentPromise=this._pagePromise=null;var d;b.keepZoom?d=this.getZoomInfo():this.resetZoom();this._currentPageIndex=-1;this.loadingManager&&this.loadingManager.destroy();this.loadingManager=null;var e=new r;b.waitUntilAllContentIsReady?(this.loadingManager=new B,this.loadingManager.init(),this._pagePromise=this.serializationManager.fromJson(a,b),this._contentPromise=g(this._pagePromise,function(){this._contentPromise=null;this.loadingManager.notifyPagesLoaded();
return this.loadingManager.returnOnLoadEnd()}.bind(this))):this._pagePromise=this.serializationManager.fromJson(a,b);g(this._pagePromise,function(){this._pagePromise=null}.bind(this));g(b.waitUntilAllContentIsReady?this._contentPromise:this._pagePromise,e.resolve,e.reject);return g(e.promise,function(){d&&c.setZoomInfo(d)})},getPagePromise:function(){return this._pagePromise},getContentPromise:function(){return this._contentPromise},toJson:function(a){return this.serializationManager.toJson(a)},onPendingDataApplied:function(){},
destroy:function(){this.loadingManager&&this.loadingManager.destroy();this.loadingManager=null;this.clear();this.inherited(arguments)}})});