// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/arcgis/csv","dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/sniff dojo/number dojox/data/CsvStore ../kernel ../config ../request ../SpatialReference ../geometry/jsonUtils ../geometry/webMercatorUtils".split(" "),function(l,c,z,A,M,N,O,B,P,r,C,D){function E(a){var b=0,f="";c.forEach([","," ",";","|","\t"],function(c){var g=a.split(c).length;g>b&&(b=g,f=c)});return f}function F(a,b){if(!a||"[object Date]"!==Object.prototype.toString.call(a)||isNaN(a.getTime()))return!1;a=!0;
if(A("chrome")&&/\d+\W*$/.test(b)){if(b.match(/[^0-9a-zA-Z\s]/))return!1;if(b=b.match(/[a-zA-Z]{2,}/)){a=!1;for(var c=0,e=b.length,g=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!a&&c<=e&&!(a=!g.test(b[c]));)c++;a=!a}}return a}function G(a,b,f){var e=a.indexOf("\n"),e=l.trim(a.substr(0,e)),g=b.columnDelimiter;g||(g=E(e));var k=new N({data:a,separator:g});k.fetch({onComplete:function(a,
g){g=0;var d={layerDefinition:b.layerDefinition,featureSet:{features:[],geometryType:"esriGeometryPoint"}},e=d.layerDefinition.objectIdField,t=d.layerDefinition.fields;e||c.some(t,function(a){return"esriFieldTypeOID"===a.type?(e=a.name,!0):!1})||(t.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1}),e="__OBJECTID");var n,h,m=k._attributes,r=[],u=[];c.forEach(t,function(a){"esriFieldTypeDate"===a.type?r.push(a.name):"esriFieldTypeDouble"!==a.type&&"esriFieldTypeInteger"!==
a.type||u.push(a.name)});b.locationInfo&&"coordinates"===b.locationInfo.locationType?(n=b.locationInfo.latitudeFieldName,h=b.locationInfo.longitudeFieldName):c.forEach(m,function(a){var d;d=c.indexOf(H,a.toLowerCase());-1!==d&&(n=a);d=c.indexOf(I,a.toLowerCase());-1!==d&&(h=a)});if(n&&h){-1===c.indexOf(u,n)&&u.push(n);-1===c.indexOf(u,h)&&u.push(h);var q;l.isArray(b.outFields)&&-1===c.indexOf(b.outFields,"*")&&(q=b.outFields);c.forEach(m,function(a){c.some(t,function(d){return a===d.name})||t.push({name:a,
alias:a,type:a===n||a===h?"esriFieldTypeDouble":"esriFieldTypeString"})});var m=0,x=a.length;for(m;m<x;m++){var v=a[m],w=k.getAttributes(v),p={};c.forEach(w,function(a){if(a&&(a===n||a===h||!q||-1<c.indexOf(q,a))){var d=a;0===a.length&&c.forEach(t,function(d,b){d.name==="attribute_"+(b-1)&&(a="attribute_"+(b-1))});if(-1<c.indexOf(r,a)){var d=k.getValue(v,d),b=new Date(d);p[a]=F(b,d)?b.getTime():null}else-1<c.indexOf(u,a)?(b=M.parse(k.getValue(v,d)),a!==n&&a!==h||!(isNaN(b)||181<Math.abs(b))||(b=parseFloat(k.getValue(v,
d))),isNaN(b)?p[a]=null:p[a]=b):p[a]=k.getValue(v,d)}});p[e]=g;g++;var w=p[n],y=p[h];null==y||null==w||isNaN(w)||isNaN(y)||(q&&-1===c.indexOf(q,n)&&delete p[n],q&&-1===c.indexOf(q,h)&&delete p[h],d.featureSet.features.push({geometry:{x:y,y:w,spatialReference:{wkid:4326}},attributes:p}))}d.layerDefinition.name="csv";f&&f(d)}else setTimeout(function(){console.error("File does not seem to contain fields with point coordinates.")},1),f&&f(null,Error("File does not seem to contain fields with point coordinates."))},
onError:function(a){console.error("Error fetching items from CSV store: ",a);f&&f(null,a)}});return!0}function x(a,b,f,e,g,k){0===a.length&&g(null);var m=C.getGeometryType(b),h=[];c.forEach(a,function(a){a=new m(a);a.spatialReference=f;h.push(a)},this);b=[102113,102100,3857];f.wkid&&4326===f.wkid&&e.wkid&&-1<c.indexOf(b,e.wkid)?(c.forEach(h,function(a){a.xmin?(a.xmin=Math.max(a.xmin,-180),a.xmax=Math.min(a.xmax,180),a.ymin=Math.max(a.ymin,-89.99),a.ymax=Math.min(a.ymax,89.99)):a.rings?c.forEach(a.rings,
function(a){c.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.paths?c.forEach(a.paths,function(a){c.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.x&&(a.x=Math.min(Math.max(a.x,-180),180),a.y=Math.min(Math.max(a.y,-89.99),89.99))},this),a=[],c.forEach(h,function(b){b=D.geographicToWebMercator(b);102100!==e.wkid&&(b.spatialReference=e);a.push(b.toJson())},
this),g(a)):null!==f.wkid&&-1<c.indexOf(b,f.wkid)&&null!==e.wkid&&4326===e.wkid?(a=[],c.forEach(h,function(b){a.push(D.webMercatorToGeographic(b).toJson())},this),g(a)):(b=function(b,f){b&&b.length===a.length?(a=[],c.forEach(b,function(b){b&&(b.rings&&0<b.rings.length&&0<b.rings[0].length&&0<b.rings[0][0].length&&!isNaN(b.rings[0][0][0])&&!isNaN(b.rings[0][0][1])||b.paths&&0<b.paths.length&&0<b.paths[0].length&&0<b.paths[0][0].length&&!isNaN(b.paths[0][0][0])&&!isNaN(b.paths[0][0][1])||b.xmin&&!isNaN(b.xmin)&&
b.ymin&&!isNaN(b.ymin)||b.x&&!isNaN(b.x)&&b.y&&!isNaN(b.y))?a.push(b.toJson()):a.push(null)},this),g(a)):k(b,f)},B.defaults.geometryService?B.defaults.geometryService.project(h,e,l.hitch(this,b),k):g(null))}function J(a,b){var f=[102113,102100,3857];return a&&b&&a.wkid===b.wkid&&a.wkt===b.wkt||a&&b&&a.wkid&&b.wkid&&-1<c.indexOf(f,a.wkid)&&-1<c.indexOf(f,b.wkid)?!0:!1}function K(a,b,f,e){if(a.featureSet&&0!==a.featureSet.features.length)if(J(f,b))e(a);else{var g,k=function(b){var d=[];c.forEach(a.featureSet.features,
function(a,c){b[c]&&(a.geometry=b[c],d.push(a))},this);e(a)},m=function(b,c){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Final try.");e(a)},h=function(c,e){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Try one more time.");x(g,a.featureSet.geometryType,b,f,l.hitch(this,k),l.hitch(this,m))};a.featureSet.features&&0<a.featureSet.features.length?(g=[],c.forEach(a.featureSet.features,function(b){if(b.geometry.toJson)g.push(b.geometry);else{var c=
C.getGeometryType(a.featureSet.geometryType);g.push(new c(b.geometry))}}),b.toJson||(b=new r(b)),f.toJson||(f=new r(f)),x(g,a.featureSet.geometryType,b,f,l.hitch(this,k),l.hitch(this,h))):e(a)}}var H="lat latitude y ycenter latitude83 latdecdeg point-y lat_dd".split(" "),I="lon lng long longitude x xcenter longitude83 longdecdeg point-x long_dd".split(" "),L={latFieldStrings:H,longFieldStrings:I,buildCSVFeatureCollection:function(a){var b=new z,c=function(a,c){c?b.errback(c):b.callback(a)},e={url:a.url,
handleAs:"text",load:function(b){G(b,a,l.hitch(this,c))},error:function(a){b.errback(a);console.error("error: "+a)}};-1<a.url.indexOf("arcgis.com")&&-1<a.url.indexOf("/content/items")&&-1<a.url.indexOf("/data")&&(e.headers={"Content-Type":""});P(e,{usePost:!1});return b},projectFeatureCollection:function(a,b,c){var e=new z;c||(c=new r({wkid:4326}));K(a,c,b,l.hitch(this,function(a){e.callback(a)}));return e},generateDefaultPopupInfo:function(a){var b={esriFieldTypeDouble:1,esriFieldTypeSingle:1},f=
{esriFieldTypeInteger:1,esriFieldTypeSmallInteger:1},e={esriFieldTypeDate:1},g=null;a=c.map(a.layerDefinition.fields,l.hitch(this,function(a){"NAME"===a.name.toUpperCase()&&(g=a.name);var c="esriFieldTypeOID"!==a.type&&"esriFieldTypeGlobalID"!==a.type&&"esriFieldTypeGeometry"!==a.type,h=null;if(c){var d=a.name.toLowerCase();if(-1<",stretched value,fnode_,tnode_,lpoly_,rpoly_,poly_,subclass,subclass_,rings_ok,rings_nok,".indexOf(","+d+",")||-1<d.indexOf("area")||-1<d.indexOf("length")||-1<d.indexOf("shape")||
-1<d.indexOf("perimeter")||-1<d.indexOf("objectid")||d.indexOf("_")===d.length-1||d.indexOf("_i")===d.length-2&&1<d.length)c=!1;a.type in f?h={places:0,digitSeparator:!0}:a.type in b?h={places:2,digitSeparator:!0}:a.type in e&&(h={dateFormat:"shortDateShortTime"})}return l.mixin({},{fieldName:a.name,label:a.alias,isEditable:!0,tooltip:"",visible:c,format:h,stringFieldOption:"textbox"})}));return{title:g?"{"+g+"}":"",fieldInfos:a,description:null,showAttachments:!1,mediaInfos:[]}},_getSeparator:E,
_isValidDate:F,_processCsvData:G,_projectGeometries:x,_sameSpatialReference:J,_projectFeatureSet:K};A("extend-esri")&&l.setObject("arcgis.csv",L,O);return L});