/*
	Copyright (c) 2004-2016, The JS Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/request/xhr",["../errors/RequestError","./watch","./handlers","./util","../has"],function(p,y,q,e,c){function z(a,b){var c=a.xhr;a.status=a.xhr.status;try{a.text=c.responseText}catch(d){}"xml"===a.options.handleAs&&(a.data=c.responseXML);var g;if(b)this.reject(b);else{try{q(a)}catch(d){g=d}e.checkStatus(c.status)?g?this.reject(g):this.resolve(a):(b=g?new p("Unable to load "+a.url+" status: "+c.status+" and an error in handleAs: transformation of response",a):new p("Unable to load "+a.url+
" status: "+c.status,a),this.reject(b))}}function A(a){return this.xhr.getResponseHeader(a)}function l(a,b,v){var g=c("native-formdata")&&b&&b.data&&b.data instanceof FormData,d=e.parseArgs(a,e.deepCreate(B,b),g);a=d.url;b=d.options;var C=!b.data&&"POST"!==b.method&&"PUT"!==b.method;10>=c("ie")&&(a=a.split("#")[0]);var k,h=e.deferred(d,r,t,w,z,function(){k&&k()}),f=d.xhr=l._create();if(!f)return h.cancel(new p("XHR was not created")),v?h:h.promise;d.getHeader=A;u&&(k=u(f,h,d,b.uploadProgress));var q=
"undefined"===typeof b.data?null:b.data,D=!b.sync,E=b.method;try{f.open(E,a,D,b.user||void 0,b.password||void 0);b.withCredentials&&(f.withCredentials=b.withCredentials);c("native-response-type")&&b.handleAs in x&&(f.responseType=x[b.handleAs]);var m=b.headers;a=g||C?!1:"application/x-www-form-urlencoded";if(m)for(var n in m)"content-type"===n.toLowerCase()?a=m[n]:m[n]&&f.setRequestHeader(n,m[n]);a&&!1!==a&&f.setRequestHeader("Content-Type",a);m&&"X-Requested-With"in m||f.setRequestHeader("X-Requested-With",
"XMLHttpRequest");e.notify&&e.notify.emit("send",d,h.promise.cancel);f.send(q)}catch(F){h.reject(F)}y(h);f=null;return v?h:h.promise}c.add("native-xhr",function(){return"undefined"!==typeof XMLHttpRequest});c.add("dojo-force-activex-xhr",function(){return c("activex")&&"file:"===window.location.protocol});c.add("native-xhr2",function(){if(c("native-xhr")&&!c("dojo-force-activex-xhr")){var a=new XMLHttpRequest;return"undefined"!==typeof a.addEventListener&&("undefined"===typeof opera||"undefined"!==
typeof a.upload)}});c.add("native-formdata",function(){return"undefined"!==typeof FormData});c.add("native-response-type",function(){return c("native-xhr")&&"undefined"!==typeof(new XMLHttpRequest).responseType});c.add("native-xhr2-blob",function(){if(c("native-response-type")){var a=new XMLHttpRequest;a.open("GET","https://dojotoolkit.org/",!0);a.responseType="blob";var b=a.responseType;a.abort();return"blob"===b}});var x={blob:c("native-xhr2-blob")?"blob":"arraybuffer",document:"document",arraybuffer:"arraybuffer"},
t,w,u,r;c("native-xhr2")?(t=function(a){return!this.isFulfilled()},r=function(a,b){b.xhr.abort()},u=function(a,b,c,g){function d(a){b.handleResponse(c)}function e(a){a=new p("Unable to load "+c.url+" status: "+a.target.status,c);b.handleResponse(c,a)}function k(a){a.lengthComputable?(c.loaded=a.loaded,c.total=a.total,b.progress(c)):3===c.xhr.readyState&&(c.loaded="loaded"in a?a.loaded:a.position,b.progress(c))}a.addEventListener("load",d,!1);a.addEventListener("error",e,!1);a.addEventListener("progress",
k,!1);g&&a.upload&&a.upload.addEventListener("progress",k,!1);return function(){a.removeEventListener("load",d,!1);a.removeEventListener("error",e,!1);a.removeEventListener("progress",k,!1);a.upload.removeEventListener("progress",k,!1);a=null}}):(t=function(a){return a.xhr.readyState},w=function(a){return 4===a.xhr.readyState},r=function(a,b){a=b.xhr;b=typeof a.abort;"function"!==b&&"object"!==b&&"unknown"!==b||a.abort()});var B={data:null,query:null,sync:!1,method:"GET"};l._create=function(){throw Error("XMLHTTP not available");
};if(c("native-xhr")&&!c("dojo-force-activex-xhr"))l._create=function(){return new XMLHttpRequest};else if(c("activex"))try{new ActiveXObject("Msxml2.XMLHTTP"),l._create=function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(a){try{new ActiveXObject("Microsoft.XMLHTTP"),l._create=function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(b){}}e.addCommonMethods(l);return l});