// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/DataBrowser/templates/ShoppingCart.html":'\x3cdiv class\x3d"ShoppingCart" data-dojo-attach-event\x3d"mouseout:_hideListOnLeave"\x3e\r\n    \x3ctable data-dojo-attach-point\x3d"label" class\x3d"Label" data-dojo-attach-event\x3d"click:_toggleList"\x3e\r\n        \x3ctr\x3e\r\n            \x3ctd class\x3d"ShoppingCart_CounterTD"\x3e\r\n                \x3cdiv class\x3d"ShoppingCart_CounterDivLeftBorder"\x3e\x3c/div\x3e\x3cdiv data-dojo-attach-point\x3d"divCounter" class\x3d"ShoppingCart_CounterDiv"\x3e\x3c/div\x3e\x3cdiv class\x3d"ShoppingCart_CounterDivRightBorder"\x3e\x3c/div\x3e\r\n            \x3c/td\x3e\r\n            \x3ctd class\x3d"ShoppingCart_LabelTd"\x3e\r\n                \x3cdiv data-dojo-attach-point\x3d"selectedVariablesLabel"\x3e\x3c/div\x3e\r\n            \x3c/td\x3e\r\n            \x3ctd\x3e\r\n                \x3cdiv class\x3d"ShoppingCartOpener" data-dojo-attach-point\x3d"divShoppingCartOpener"\x3e\x26#x25bc;\x3c/div\x3e\r\n            \x3c/td\x3e\r\n        \x3c/tr\x3e\r\n    \x3c/table\x3e\r\n        \r\n    \x3cdiv data-dojo-attach-point\x3d"divOuter" class\x3d"ShoppingCart_OuterDiv"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"divList" class\x3d"ShoppingCart_DivList"\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"divEmpty" class\x3d"ShoppingCart_DivEmpty"\x3e\r\n            \x3cdiv\x3e${nls.noVariables}\x3c/div\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/DataBrowser/ShoppingCart","dojo/_base/lang dojo/_base/window dojo/dom-construct dojo/dom-attr dojo/on dojo/when dojox/mvc/Templated dgrid/List ../../../declare ../utils/TooltipUtil dojo/text!./templates/ShoppingCart.html dojo/i18n!../../../nls/jsapi ./VariableUtil ./VariableToggle".split(" "),function(f,w,b,x,g,n,p,q,r,k,t,h,u,v){h=h.geoenrichment.dijit.ShoppingCart;return r("esri.dijit.geoenrichment.ShoppingCart",p,{nls:h,templateString:t,variables:null,selection:null,
allowToggles:!0,allowMoveButtons:!1,allowEditButtons:!1,_list:null,_content:null,postCreate:function(){this.inherited(arguments);var a=h.selectedVars,d=a.split(/\s+/),c=d.length-1;if(2>c)a=d.join("\x3cbr/\x3e");else{for(var a=a.length-c,e=d[0].length,l=0,b=1;b<c;b++){var k=e+d[b].length;Math.abs(2*e-a)>Math.abs(2*k-a)&&(l=b);e=k}a=d.slice(0,l+1).join("\x26nbsp;")+"\x3cbr/\x3e"+d.slice(l+1).join("\x26nbsp;")}this.selectedVariablesLabel.innerHTML=a;this.selection=[];this._content=[];this._list=new q({renderRow:f.hitch(this,
this._renderVariable)},this.divList);g(this.divList,"click, touchend",f.hitch(this,this._stopPropagation));this._updateLabel();this.divOuter.style.display="none";var m=this;this.watch("selection",function(){n(m.variables.synchronize(),f.hitch(m,m._onSelectionChanged))})},_updateLabel:function(){this.divCounter.innerHTML=this._content.length.toString()},_onSelectionChanged:function(){for(var a=[],d=Math.min(this._content.length,this.selection.length),c=0;c<d;c++){var e=this.selection[c],b=this._content[c];
if(!b.hash[e])break;b.group.value=e;a.push(b)}d=this.selection.length;for(c=a.length;c<d;c++)e=this.selection[c],b={hash:{}},b.group=u.getToggleGroup(this.variables,e,b.hash),e=b.group.states&&this.allowToggles?b.group.states.ids[0]:b.group.value,e=this.variables.get(e),b.title=e&&e.alias,a.push(b);this._content=a;this._updateLabel()},_toggleList:function(a){this._stopPropagation(a);"none"===this.divOuter.style.display?this._displayList():this._hideList()},_stopPropagation:function(a){a.stopPropagation&&
a.stopPropagation()},_displayList:function(){this.refresh();this.divShoppingCartOpener.innerHTML="\x26#x25b2;";this.divOuter.style.display=""},_hideList:function(){this.divShoppingCartOpener.innerHTML="\x26#x25bc;";this.divOuter.style.display="none"},_hideListOnLeave:function(a){if("none"!=this.divOuter.style.display){a=a.relatedTarget;for(var d=!0;a;){if(a===this.label||a===this.divOuter){d=!1;break}a=a.parentNode}this._onMouseLeave(d)}},_onMouseLeave:function(a){a&&this._hideList()},_renderVariable:function(a){var d=
b.create("div",{"class":"ShoppingCartRow"}),c=b.create("div",{"class":"ShoppingCartRowCloser ShoppingCartRowFloatEnd"},d);k.setTooltipToNode(c,h.removeVariable);g(c,"click",f.hitch(this,this._onRemove,a));b.create("div",{"class":"dijitInline ShoppingCartRowSpacer ShoppingCartRowFloatEnd",innerHTML:"\x26nbsp;"},d);this.allowEditButtons&&this._canEditData(a)&&(c=b.create("div",{"class":"ShoppingCartRowEditButton ShoppingCartRowFloatEnd"},d),k.setTooltipToNode(c,h.editVariable),g(c,"click",f.hitch(this,
this._onEditData,a)),b.create("div",{"class":"dijitInline ShoppingCartRowSpacer ShoppingCartRowFloatEnd",innerHTML:"\x26nbsp;"},d));a.group.states&&this.allowToggles&&(c=new v(a.group,b.create("div",{"class":"dijitInline ShoppingCartRowFloatEnd"},d)),g(c,"change",f.hitch(this,this._onToggleChange,c,a)),b.create("div",{"class":"dijitInline ShoppingCartRowSpacer ShoppingCartRowFloatEnd",innerHTML:"\x26nbsp;"},d));if(this.allowMoveButtons){c=b.create("div",{"class":"dijitInline ShoppingCartRowFloatEnd upDownArrowsBlock"},
d);if(0<this._content.indexOf(a)){var e=b.create("div",{"class":"dijitInline upArrow"},c);g(e,"click",f.hitch(this,this._onMove,a,!0))}this._content.indexOf(a)<this._content.length-1&&(c=b.create("div",{"class":"dijitInline downArrow"},c),g(c,"click",f.hitch(this,this._onMove,a,!1)));b.create("div",{"class":"dijitInline ShoppingCartRowSpacer ShoppingCartRowFloatEnd",innerHTML:"\x26nbsp;"},d)}a=this.variables.get(a.group.states&&this.allowToggles?a.group.states.ids[0]:a.group.value);b.create("div",
{"class":"TrimWithEllipses ShoppingCartRowLabel",innerHTML:a&&a.alias||""},d);return d},_onRemove:function(a){var d=this.selection.slice();a=this._content.indexOf(a);d.splice(a,1);this._content.splice(a,1);this.set("selection",d);this.refresh()},_onToggleChange:function(a,d){d.group.value=a.value;var c=this.selection.slice();c[this._content.indexOf(d)]=a.value;this.set("selection",c)},_onMove:function(a,d){var c=this.selection.slice(),b=this._content.indexOf(a),f=c[b];c.splice(b,1);this._content.splice(b,
1);c.splice(d?b-1:b+1,0,f);this._content.splice(d?b-1:b+1,0,a);this.set("selection",c);this.refresh()},_canEditData:function(a){return!1},_onEditData:function(a){},refresh:function(){this._list.refresh();this._list.renderArray(this._content);this._updateLabel();this.divEmpty.style.visibility=this._content.length?"hidden":"visible"}})});