// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/ChartJsonUtil","dojo/_base/lang ./ThemeCalculator ./ChartTypes ./ChartDataLabelsTypes ../legends/ChartLegendPlacements ../legends/ChartLegendTypes ./_ChartJsonCleaner ./_ChartJsonClassicReportSupports esri/dijit/geoenrichment/utils/ObjectUtil ./plots/supportClasses/GaugeLabelPlacement".split(" "),function(b,d,k,l,f,m,n,p,g,q){var h={getDefaultChartSettings:function(a){a=a||{};var c=b.mixin({},a.font),e=b.mixin({},a.font);delete e.fontSize;
return{isChart:!0,type:a.chartType||k.COLUMN,isMultiFeatureChart:!!a.isMultiFeatureChart,seriesItems:[],visualProperties:{width:a.width||400,height:a.height||300,barBorders:!1,view3D:!1,origin:0,backgroundColor:void 0,backgroundImageData:void 0,panelBackgroundColor:void 0,title:{text:"",align:"center",style:b.mixin({},c)},xAxis:{show:!0,showTicks:!0,ticksInside:!1,showLine:!0,title:"",titleStyle:b.mixin({},c),style:b.mixin({},c),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,
gridLinesOpacity:1,gridLinesThickness:.5,gridLinesStyle:void 0,gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,placement:void 0},yAxis:{show:!0,showTicks:!0,ticksInside:!1,showLine:!0,title:"",titleStyle:b.mixin({},c),style:b.mixin({},c),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,gridLinesOpacity:1,gridLinesThickness:.5,gridLinesStyle:void 0,gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,baseLine:!0,baseLineColor:void 0,
baseLineOpacity:1,baseLineThickness:.5,baseLineStyle:void 0,baseLineValue:0,showPercentIndicator:!1,showValuesAsWeightsInSeries:!1,placement:void 0},legend:{type:m.SERIES,series:{placement:f.RIGHT,placementOffset:10,hasBorder:!0,labelParts:"Label",style:b.mixin({},c)},minMax:{placement:f.RIGHT,placementOffset:3,titleStyle:b.mixin({},e),minVariableLabelStyle:b.mixin({},e),maxVariableLabelStyle:b.mixin({},e)}},isStacked:!1,columnThickness:d.DEFAULT_COLUMN_THICKNESS,showColumnBarBackground:!1,columnBarBackgroundColor:void 0,
renderColumnBarsInOppositeDirections:!1,columnBarGap:void 0,lineThickness:d.DEFAULT_LINE_THICKNESS,fillLineArea:!1,lineAreaOpacity:1,donutHolePercent:d.DEFAULT_DONUT_HOLE_PERCENT,donutGap:d.DEFAULT_DONUT_GAP,donutArcPercent:d.DEFAULT_DONUT_ARC_PERCENT,gaugeHolePercent:d.DEFAULT_GAUGE_HOLE_PERCENT,gaugeRangeMin:void 0,gaugeRangeMax:void 0,gaugeGap:d.DEFAULT_GAUGE_GAP,gaugeStartAngle:d.DEFAULT_GAUGE_ANGLE,gaugeArcPercent:d.DEFAULT_GAUGE_ARC_PERCENT,gaugeLabelPlacement:q.INSIDE,gaugeLabelStyle:b.mixin({},
e),gaugeShowArrow:!1,gaugeArrowLineColor:void 0,gaugeArrowFillColor:void 0,gaugeConditionalStylingIgnoreOthers:!1,gaugeConditionalStylingLabel:!1,ringBackgroundColor:void 0,showWholePictures:!1,dataLabels:l.NONE,dataLabelsStyle:b.mixin({},c),dataLabelsDecimals:0,dataLabelsInside:!1,dataLabelsStackedInColumns:!1,dataLabelsHorizontalAlign:void 0,chartIcons:void 0,floatingIcons:void 0,showAxisIcons:!1,showChartIcons:!1,floatingTexts:void 0,sorting:void 0,conditionalStyling:void 0},comparisonInfo:void 0}},
provideDefaultValueForMissing:function(a,c){c=h.getDefaultChartSettings(c);g.populateObject(a,c);return a},cleanUpJson:function(a,c){n.cleanUpJson(a,c)},filterChartJsonForClassicReport:function(a){return g.filterByPattern(a,p)},createChartPoint:function(a,c,b,d,f){return{color:b||"",label:c||a&&a.alias,fieldInfo:a,iconFieldInfo:d,captionFieldInfo:f}}};return h});