// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/ThemeCalculator","dojo/_base/lang dojox/charting/Theme ../../themes/ThemeLibrary ./ChartTypes ./ChartLineMarkers ./plots/supportClasses/GaugeLabelPlacement ../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder".split(" "),function(h,r,t,f,k,v,u){function p(d,b){var a;switch(d){case f.COLUMN:a=b.column&&b.column.colors;break;case f.BAR:a=b.bar&&b.bar.colors;break;case f.LINE:a=b.line&&b.line.colors;break;case f.PIE:a=b.pie&&
b.pie.colors;break;case f.DONUT:a=b.donut&&b.donut.colors;break;case f.GAUGE:a=b.gauge&&b.gauge.colors;break;case f.RING:a=b.ring&&b.ring.colors;break;case f.PICTURE_COLUMN:a=b.pictureColumn&&b.pictureColumn.colors;break;case f.PICTURE_BAR:a=b.pictureBar&&b.pictureBar.colors}a&&a.length||(a=null);return a||b.colors||q}var e={},q=["#AAAAAA","#888888","#555555","#333333"];e.DEFAULT_LINE_THICKNESS=1;e.DEFAULT_COLUMN_THICKNESS="Medium";e.DEFAULT_DONUT_HOLE_PERCENT=50;e.DEFAULT_DONUT_GAP=3;e.DEFAULT_DONUT_ARC_PERCENT=
100;e.DEFAULT_GAUGE_HOLE_PERCENT=80;e.DEFAULT_GAUGE_GAP=2;e.DEFAULT_GAUGE_ANGLE=0;e.DEFAULT_GAUGE_ARC_PERCENT=100;e.getThemeForSettings=function(d,b){var a=new r({colors:b.colors||q});if(!d)return a;var c=d.visualProperties;a.plotarea.fill=c.backgroundColor||b.backgroundColor;a.plotarea.stroke={width:0};a.chart.fill="transparent";a.axis.title.font="normal normal normal 11px Verdana";!f.isPieLike(d.type)&&d.type!==f.RING&&c.backgroundImageData&&(a.plotarea.backgroundImageData=c.backgroundImageData);
var g=h.mixin({},b.dataLabelsStyle,c.dataLabelsStyle);g.color&&(a.series.fontColor=g.color);a.series.font=e.combineFontString(g);a.series.showColumnBarBackground=c.showColumnBarBackground;a.series.columnBarBackgroundColor=c.columnBarBackgroundColor||b.columnBarBackground&&b.columnBarBackground.backgroundColor;a.series.renderColumnBarsInOppositeDirections=c.renderColumnBarsInOppositeDirections;a.series.baseLineValue=c.yAxis.baseLineValue;d.type===f.DONUT&&(a.series.donutHolePercent=void 0!==c.donutHolePercent?
c.donutHolePercent:e.DEFAULT_DONUT_HOLE_PERCENT,a.series.donutGap=void 0!==c.donutGap?c.donutGap:e.DEFAULT_DONUT_GAP,a.series.donutArcPercent=void 0!==c.donutArcPercent?c.donutArcPercent:e.DEFAULT_DONUT_ARC_PERCENT,a.series.donutArcPercent=Math.min(100,Math.max(50,a.series.donutArcPercent)));d.type===f.GAUGE&&(a.series.donutHolePercent=void 0!==c.gaugeHolePercent?c.gaugeHolePercent:e.DEFAULT_GAUGE_HOLE_PERCENT,a.series.donutGap=void 0!==c.gaugeGap?c.gaugeGap:e.DEFAULT_GAUGE_GAP,a.series.startAngle=
void 0!==c.gaugeStartAngle?c.gaugeStartAngle:e.DEFAULT_GAUGE_ANGLE,a.series.donutArcPercent=void 0!==c.gaugeArcPercent?c.gaugeArcPercent:e.DEFAULT_GAUGE_ARC_PERCENT,a.series.donutArcPercent=Math.min(100,Math.max(50,a.series.donutArcPercent)),a.series.donutShowIcons=c.showChartIcons,c.gaugeShowArrow&&(a.series.donutShowArrowIndicator=!0,a.series.donutGap=0,100!==a.series.donutArcPercent&&(a.series.startAngle=0),a.series.donutArrowIndicatorLineColor=c.gaugeArrowLineColor||b.gauge&&b.gauge.arrowIndicator.lineColor,
a.series.donutArrowIndicatorFillColor=c.gaugeArrowFillColor||b.gauge&&b.gauge.arrowIndicator.backgroundColor),g=h.mixin({},b.gauge&&b.gauge.dataLabelStyle,c.gaugeLabelStyle),a.series.donutMainLabelPosition=c.gaugeLabelPlacement,a.series.donutMainLabelFont=e.combineFontString(g),a.series.donutMainLabelFontColor=c.gaugeConditionalStylingLabel?null:g.color,a.series.donutMainLabelFontColorFromConditionalStyling=c.gaugeConditionalStylingLabel&&!!c.conditionalStyling,a.series.donutMainLabelFontSize=c.gaugeLabelStyle&&
c.gaugeLabelStyle.fontSize,a.series.donutMainLabelTextDecoration=g.textDecoration,a.series.isPercentState=u.isFieldInfoInPercentState(d.seriesItems[0].points[0].fieldInfo));d.type===f.RING&&(a.series.show100PercentLabel=!0,a.series.ringBackgroundColor=c.ringBackgroundColor||b.ring&&b.ring.ringBackground&&b.ring.ringBackground.backgroundColor);f.isPictureLike(d.type)&&(a.series.showWholePictures=c.showWholePictures);a.marker.fill="#FFFFFF";a.series.outline=null;return a};e.getComparisonSymbol=function(){return k.getMarkerPath(k.CIRCLE)};
e.calcColorForPoint=function(d,b,a,c,e,l,h,k,m){e=f.isPieLike(l)||!h.renderSingleDataSeriesWithSameColor&&1===e;var g=p(l,h),n;if(l===f.LINE)k&&m?d=m.color||h.comparisonInfo.lineColor:(n=g[c%g.length],d=b.color||n||"#FFFFFF");else if(k&&m&&m.color)d=m.color;else{if(l===f.GAUGE&&1===a&&h.gauge.othersColor)return d&&d.color||h.gauge.othersColor;n=n||(e?g[a%g.length]:g[c%g.length]);d=d&&d.color||!f.isPieLike(l)&&b.color||n||"#FFFFFF"}return d};e.calcColorForSeries=function(d,b,a,c,e){a=f.isPieLike(c)||
!e.renderSingleDataSeriesWithSameColor&&1===a;e=p(c,e);b=c===f.LINE?e[b%e.length]:a?null:e[b%e.length];return d&&d.color||b||"#FFFFFF"};e.provideMissingIconsForPoints=function(d,b){if(!f.isPictureLike(b))return null;var a,c=[];d.forEach(function(b){b.iconFieldInfo?(a=b.iconFieldInfo,c.forEach(function(b){b.iconFieldInfo=h.clone(a)}),c.length=0):a?b.iconFieldInfo=h.clone(a):c.push(b)})};e.calcIconForPoint=function(d,b,a){if(!f.isPictureLike(a))return null;(d=d.iconFieldInfo)&&d.shapeJson&&b&&(d.shapeJson.themeStyle=
{fillColor:b,borderColor:b});return d};e.calcBackgroundIconForPoint=function(d,b,a,c){if(!f.isPictureLike(b))return null;b=c.columnBarBackgroundColor||a.columnBarBackground&&a.columnBarBackground.backgroundColor;return(d=d.iconFieldInfo)&&d.shapeJson&&b?(d=h.clone(d),d.shapeJson.themeStyle={fillColor:b,borderColor:b},d):null};e.combineFontString=function(d){d=d||{};return(d.fontStyle||"normal")+" normal "+(d.fontWeight||"normal")+" "+((d.fontSize||"11")+"px")+" "+(d.fontFamily||t.DEFAULT_FONT_FAMILY_CLASSIC)};
return e});