// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
require({cache:{"esri/arcgis/csv":function(){define("dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/sniff dojo/number dojox/data/CsvStore ../kernel ../config ../request ../SpatialReference ../geometry/jsonUtils ../geometry/webMercatorUtils".split(" "),function(p,d,m,l,h,c,a,f,k,b,e,n){function g(a){var b=0,e="";d.forEach([","," ",";","|","\t"],function(f){var t=a.split(f).length;t>b&&(b=t,e=f)});return e}function C(a,b){if(!a||"[object Date]"!==Object.prototype.toString.call(a)||isNaN(a.getTime()))return!1;
a=!0;if(l("chrome")&&/\d+\W*$/.test(b)){if(b.match(/[^0-9a-zA-Z\s]/))return!1;if(b=b.match(/[a-zA-Z]{2,}/)){a=!1;for(var e=0,f=b.length,t=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!a&&e<=f&&!(a=!t.test(b[e]));)e++;a=!a}}return a}function r(a,b,e){var f=a.indexOf("\n"),f=p.trim(a.substr(0,f)),t=b.columnDelimiter;t||(t=g(f));var k=new c({data:a,separator:t});k.fetch({onComplete:function(a,
f){f=0;var y={layerDefinition:b.layerDefinition,featureSet:{features:[],geometryType:"esriGeometryPoint"}},t=y.layerDefinition.objectIdField,n=y.layerDefinition.fields;t||d.some(n,function(a){return"esriFieldTypeOID"===a.type?(t=a.name,!0):!1})||(n.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1}),t="__OBJECTID");var c,g,v=k._attributes,q=[],r=[];d.forEach(n,function(a){"esriFieldTypeDate"===a.type?q.push(a.name):"esriFieldTypeDouble"!==a.type&&"esriFieldTypeInteger"!==
a.type||r.push(a.name)});b.locationInfo&&"coordinates"===b.locationInfo.locationType?(c=b.locationInfo.latitudeFieldName,g=b.locationInfo.longitudeFieldName):d.forEach(v,function(a){var b;b=d.indexOf(z,a.toLowerCase());-1!==b&&(c=a);b=d.indexOf(A,a.toLowerCase());-1!==b&&(g=a)});if(c&&g){-1===d.indexOf(r,c)&&r.push(c);-1===d.indexOf(r,g)&&r.push(g);var m;p.isArray(b.outFields)&&-1===d.indexOf(b.outFields,"*")&&(m=b.outFields);d.forEach(v,function(a){d.some(n,function(b){return a===b.name})||n.push({name:a,
alias:a,type:a===c||a===g?"esriFieldTypeDouble":"esriFieldTypeString"})});var v=0,F=a.length;for(v;v<F;v++){var x=a[v],l=k.getAttributes(x),u={};d.forEach(l,function(a){if(a&&(a===c||a===g||!m||-1<d.indexOf(m,a))){var b=a;0===a.length&&d.forEach(n,function(b,e){b.name==="attribute_"+(e-1)&&(a="attribute_"+(e-1))});if(-1<d.indexOf(q,a)){var b=k.getValue(x,b),e=new Date(b);u[a]=C(e,b)?e.getTime():null}else-1<d.indexOf(r,a)?(e=h.parse(k.getValue(x,b)),a!==c&&a!==g||!(isNaN(e)||181<Math.abs(e))||(e=parseFloat(k.getValue(x,
b))),isNaN(e)?u[a]=null:u[a]=e):u[a]=k.getValue(x,b)}});u[t]=f;f++;var l=u[c],B=u[g];null==B||null==l||isNaN(l)||isNaN(B)||(m&&-1===d.indexOf(m,c)&&delete u[c],m&&-1===d.indexOf(m,g)&&delete u[g],y.featureSet.features.push({geometry:{x:B,y:l,spatialReference:{wkid:4326}},attributes:u}))}y.layerDefinition.name="csv";e&&e(y)}else setTimeout(function(){console.error("File does not seem to contain fields with point coordinates.")},1),e&&e(null,Error("File does not seem to contain fields with point coordinates."))},
onError:function(a){console.error("Error fetching items from CSV store: ",a);e&&e(null,a)}});return!0}function q(a,b,k,c,g,h){0===a.length&&g(null);var t=e.getGeometryType(b),r=[];d.forEach(a,function(a){a=new t(a);a.spatialReference=k;r.push(a)},this);b=[102113,102100,3857];k.wkid&&4326===k.wkid&&c.wkid&&-1<d.indexOf(b,c.wkid)?(d.forEach(r,function(a){a.xmin?(a.xmin=Math.max(a.xmin,-180),a.xmax=Math.min(a.xmax,180),a.ymin=Math.max(a.ymin,-89.99),a.ymax=Math.min(a.ymax,89.99)):a.rings?d.forEach(a.rings,
function(a){d.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.paths?d.forEach(a.paths,function(a){d.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.x&&(a.x=Math.min(Math.max(a.x,-180),180),a.y=Math.min(Math.max(a.y,-89.99),89.99))},this),a=[],d.forEach(r,function(b){b=n.geographicToWebMercator(b);102100!==c.wkid&&(b.spatialReference=c);a.push(b.toJson())},
this),g(a)):null!==k.wkid&&-1<d.indexOf(b,k.wkid)&&null!==c.wkid&&4326===c.wkid?(a=[],d.forEach(r,function(b){a.push(n.webMercatorToGeographic(b).toJson())},this),g(a)):(b=function(b,e){b&&b.length===a.length?(a=[],d.forEach(b,function(b){b&&(b.rings&&0<b.rings.length&&0<b.rings[0].length&&0<b.rings[0][0].length&&!isNaN(b.rings[0][0][0])&&!isNaN(b.rings[0][0][1])||b.paths&&0<b.paths.length&&0<b.paths[0].length&&0<b.paths[0][0].length&&!isNaN(b.paths[0][0][0])&&!isNaN(b.paths[0][0][1])||b.xmin&&!isNaN(b.xmin)&&
b.ymin&&!isNaN(b.ymin)||b.x&&!isNaN(b.x)&&b.y&&!isNaN(b.y))?a.push(b.toJson()):a.push(null)},this),g(a)):h(b,e)},f.defaults.geometryService?f.defaults.geometryService.project(r,c,p.hitch(this,b),h):g(null))}function D(a,b){var e=[102113,102100,3857];return a&&b&&a.wkid===b.wkid&&a.wkt===b.wkt||a&&b&&a.wkid&&b.wkid&&-1<d.indexOf(e,a.wkid)&&-1<d.indexOf(e,b.wkid)?!0:!1}function w(a,f,c,k){if(a.featureSet&&0!==a.featureSet.features.length)if(D(c,f))k(a);else{var g,n=function(b){var e=[];d.forEach(a.featureSet.features,
function(a,f){b[f]&&(a.geometry=b[f],e.push(a))},this);k(a)},r=function(b,e){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Final try.");k(a)},h=function(b,e){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Try one more time.");q(g,a.featureSet.geometryType,f,c,p.hitch(this,n),p.hitch(this,r))};a.featureSet.features&&0<a.featureSet.features.length?(g=[],d.forEach(a.featureSet.features,function(b){if(b.geometry.toJson)g.push(b.geometry);else{var f=
e.getGeometryType(a.featureSet.geometryType);g.push(new f(b.geometry))}}),f.toJson||(f=new b(f)),c.toJson||(c=new b(c)),q(g,a.featureSet.geometryType,f,c,p.hitch(this,n),p.hitch(this,h))):k(a)}}var z="lat latitude y ycenter latitude83 latdecdeg point-y lat_dd".split(" "),A="lon lng long longitude x xcenter longitude83 longdecdeg point-x long_dd".split(" "),E={latFieldStrings:z,longFieldStrings:A,buildCSVFeatureCollection:function(a){var b=new m,e=function(a,e){e?b.errback(e):b.callback(a)},f={url:a.url,
handleAs:"text",load:function(b){r(b,a,p.hitch(this,e))},error:function(a){b.errback(a);console.error("error: "+a)}};-1<a.url.indexOf("arcgis.com")&&-1<a.url.indexOf("/content/items")&&-1<a.url.indexOf("/data")&&(f.headers={"Content-Type":""});k(f,{usePost:!1});return b},projectFeatureCollection:function(a,e,f){var c=new m;f||(f=new b({wkid:4326}));w(a,f,e,p.hitch(this,function(a){c.callback(a)}));return c},generateDefaultPopupInfo:function(a){var b={esriFieldTypeDouble:1,esriFieldTypeSingle:1},e=
{esriFieldTypeInteger:1,esriFieldTypeSmallInteger:1},f={esriFieldTypeDate:1},c=null;a=d.map(a.layerDefinition.fields,p.hitch(this,function(a){"NAME"===a.name.toUpperCase()&&(c=a.name);var k="esriFieldTypeOID"!==a.type&&"esriFieldTypeGlobalID"!==a.type&&"esriFieldTypeGeometry"!==a.type,g=null;if(k){var d=a.name.toLowerCase();if(-1<",stretched value,fnode_,tnode_,lpoly_,rpoly_,poly_,subclass,subclass_,rings_ok,rings_nok,".indexOf(","+d+",")||-1<d.indexOf("area")||-1<d.indexOf("length")||-1<d.indexOf("shape")||
-1<d.indexOf("perimeter")||-1<d.indexOf("objectid")||d.indexOf("_")===d.length-1||d.indexOf("_i")===d.length-2&&1<d.length)k=!1;a.type in e?g={places:0,digitSeparator:!0}:a.type in b?g={places:2,digitSeparator:!0}:a.type in f&&(g={dateFormat:"shortDateShortTime"})}return p.mixin({},{fieldName:a.name,label:a.alias,isEditable:!0,tooltip:"",visible:k,format:g,stringFieldOption:"textbox"})}));return{title:c?"{"+c+"}":"",fieldInfos:a,description:null,showAttachments:!1,mediaInfos:[]}},_getSeparator:g,
_isValidDate:C,_processCsvData:r,_projectGeometries:q,_sameSpatialReference:D,_projectFeatureSet:w};l("extend-esri")&&p.setObject("arcgis.csv",E,a);return E})},"dojox/data/CsvStore":function(){define("dojo/_base/lang dojo/_base/declare dojo/_base/xhr dojo/_base/kernel dojo/data/util/filter dojo/data/util/simpleFetch".split(" "),function(p,d,m,l,h,c){d=d("dojox.data.CsvStore",null,{constructor:function(a){this._attributes=[];this._attributeIndexes={};this._dataArray=[];this._arrayOfAllItems=[];this._loadFinished=
!1;a.url&&(this.url=a.url);this._csvData=a.data;a.label?this.label=a.label:""===this.label&&(this.label=void 0);this._storeProp="_csvStore";this._idProp="_csvId";this._features={"dojo.data.api.Read":!0,"dojo.data.api.Identity":!0};this._loadInProgress=!1;this._queuedFetches=[];this.identifier=a.identifier;""===this.identifier?delete this.identifier:this._idMap={};"separator"in a&&(this.separator=a.separator);"urlPreventCache"in a&&(this.urlPreventCache=a.urlPreventCache?!0:!1)},url:"",label:"",identifier:"",
separator:",",urlPreventCache:!1,_assertIsItem:function(a){if(!this.isItem(a))throw Error(this.declaredClass+": a function was passed an item argument that was not an item");},_getIndex:function(a){a=this.getIdentity(a);this.identifier&&(a=this._idMap[a]);return a},getValue:function(a,f,c){this._assertIsItem(a);var b=c;if("string"===typeof f)f=this._attributeIndexes[f],null!=f&&(b=this._dataArray[this._getIndex(a)][f]||c);else throw Error(this.declaredClass+": a function was passed an attribute argument that was not a string");
return b},getValues:function(a,f){return(a=this.getValue(a,f))?[a]:[]},getAttributes:function(a){this._assertIsItem(a);var f=[];a=this._dataArray[this._getIndex(a)];for(var c=0;c<a.length;c++)""!==a[c]&&f.push(this._attributes[c]);return f},hasAttribute:function(a,f){this._assertIsItem(a);if("string"===typeof f)return f=this._attributeIndexes[f],a=this._dataArray[this._getIndex(a)],"undefined"!==typeof f&&f<a.length&&""!==a[f];throw Error(this.declaredClass+": a function was passed an attribute argument that was not a string");
},containsValue:function(a,f,c){var b=void 0;"string"===typeof c&&(b=h.patternToRegExp(c,!1));return this._containsValue(a,f,c,b)},_containsValue:function(a,f,c,b){a=this.getValues(a,f);for(f=0;f<a.length;++f){var e=a[f];if("string"===typeof e&&b)return null!==e.match(b);if(c===e)return!0}return!1},isItem:function(a){if(a&&a[this._storeProp]===this)if(a=a[this._idProp],this.identifier){if(this._dataArray[this._idMap[a]])return!0}else if(0<=a&&a<this._dataArray.length)return!0;return!1},isItemLoaded:function(a){return this.isItem(a)},
loadItem:function(a){},getFeatures:function(){return this._features},getLabel:function(a){if(this.label&&this.isItem(a))return this.getValue(a,this.label)},getLabelAttributes:function(a){return this.label?[this.label]:null},_fetchItems:function(a,f,c){var b=this,e=function(a,e){var c=null;if(a.query){var d,g,c=[],k=a.queryOptions?a.queryOptions.ignoreCase:!1,n={};for(d in a.query)g=a.query[d],"string"===typeof g&&(n[d]=h.patternToRegExp(g,k));for(k=0;k<e.length;++k){var r=!0,m=e[k];for(d in a.query)g=
a.query[d],b._containsValue(m,d,g,n[d])||(r=!1);r&&c.push(m)}}else c=e.slice(0,e.length);f(c,a)};if(this._loadFinished)e(a,this._arrayOfAllItems);else if(""!==this.url)if(this._loadInProgress)this._queuedFetches.push({args:a,filter:e});else{this._loadInProgress=!0;var d=m.get({url:b.url,handleAs:"text",preventCache:b.urlPreventCache});d.addCallback(function(f){try{b._processData(f),e(a,b._arrayOfAllItems),b._handleQueuedFetches()}catch(q){c(q,a)}});d.addErrback(function(e){b._loadInProgress=!1;if(c)c(e,
a);else throw e;});var g=null;a.abort&&(g=a.abort);a.abort=function(){var b=d;b&&-1===b.fired&&(b.cancel(),b=null);g&&g.call(a)}}else if(this._csvData)try{this._processData(this._csvData),this._csvData=null,e(a,this._arrayOfAllItems)}catch(r){c(r,a)}else{var k=Error(this.declaredClass+": No CSV source data was provided as either URL or String data input.");if(c)c(k,a);else throw k;}},close:function(a){},_getArrayOfArraysFromCsvFileContents:function(a){if(p.isString(a)){var f=/^\s+/g,c=/\s+$/g,b=/""/g,
e=[],d=this._splitLines(a);for(a=0;a<d.length;++a){var g=d[a];if(0<g.length){for(var g=g.split(this.separator),h=0;h<g.length;){var m=g[h].replace(f,""),q=m.replace(c,""),l=q.charAt(0),w=q.charAt(q.length-1),z=q.charAt(q.length-2),A=q.charAt(q.length-3);if(2===q.length&&'""'==q)g[h]="";else if('"'==l&&('"'!=w||'"'==w&&'"'==z&&'"'!=A)){if(h+1===g.length)return;g[h]=m+this.separator+g[h+1];g.splice(h+1,1)}else'"'==l&&'"'==w&&(q=q.slice(1,q.length-1),q=q.replace(b,'"')),g[h]=q,h+=1}e.push(g)}}this._attributes=
e.shift();for(a=0;a<this._attributes.length;a++)this._attributeIndexes[this._attributes[a]]=a;this._dataArray=e}},_splitLines:function(a){var c=[],d,b="",e=!1;for(d=0;d<a.length;d++){var h=a.charAt(d);switch(h){case '"':e=!e;b+=h;break;case "\r":e?b+=h:(c.push(b),b="",d<a.length-1&&"\n"==a.charAt(d+1)&&d++);break;case "\n":e?b+=h:(c.push(b),b="");break;default:b+=h}}""!==b&&c.push(b);return c},_processData:function(a){this._getArrayOfArraysFromCsvFileContents(a);this._arrayOfAllItems=[];if(this.identifier&&
void 0===this._attributeIndexes[this.identifier])throw Error(this.declaredClass+": Identity specified is not a column header in the data set.");for(a=0;a<this._dataArray.length;a++){var c=a;this.identifier&&(c=this._dataArray[a][this._attributeIndexes[this.identifier]],this._idMap[c]=a);this._arrayOfAllItems.push(this._createItemFromIdentity(c))}this._loadFinished=!0;this._loadInProgress=!1},_createItemFromIdentity:function(a){var c={};c[this._storeProp]=this;c[this._idProp]=a;return c},getIdentity:function(a){return this.isItem(a)?
a[this._idProp]:null},fetchItemByIdentity:function(a){var c,d=a.scope?a.scope:l.global;if(this._loadFinished)c=this._createItemFromIdentity(a.identity),this.isItem(c)||(c=null),a.onItem&&a.onItem.call(d,c);else{var b=this;if(""!==this.url)this._loadInProgress?this._queuedFetches.push({args:a}):(this._loadInProgress=!0,c=m.get({url:b.url,handleAs:"text"}),c.addCallback(function(c){try{b._processData(c);var e=b._createItemFromIdentity(a.identity);b.isItem(e)||(e=null);a.onItem&&a.onItem.call(d,e);b._handleQueuedFetches()}catch(g){a.onError&&
a.onError.call(d,g)}}),c.addErrback(function(b){this._loadInProgress=!1;a.onError&&a.onError.call(d,b)}));else if(this._csvData)try{b._processData(b._csvData),b._csvData=null,c=b._createItemFromIdentity(a.identity),b.isItem(c)||(c=null),a.onItem&&a.onItem.call(d,c)}catch(e){a.onError&&a.onError.call(d,e)}}},getIdentityAttributes:function(a){return this.identifier?[this.identifier]:null},_handleQueuedFetches:function(){if(0<this._queuedFetches.length){for(var a=0;a<this._queuedFetches.length;a++){var c=
this._queuedFetches[a],d=c.filter,b=c.args;d?d(b,this._arrayOfAllItems):this.fetchItemByIdentity(c.args)}this._queuedFetches=[]}}});p.extend(d,c);return d})},"dojo/data/util/filter":function(){define(["../../_base/lang"],function(p){var d={};p.setObject("dojo.data.util.filter",d);d.patternToRegExp=function(d,l){for(var h="^",c=null,a=0;a<d.length;a++)switch(c=d.charAt(a),c){case "\\":h+=c;a++;h+=d.charAt(a);break;case "*":h+=".*";break;case "?":h+=".";break;case "$":case "^":case "/":case "+":case ".":case "|":case "(":case ")":case "{":case "}":case "[":case "]":h+=
"\\";default:h+=c}h+="$";return l?new RegExp(h,"mi"):new RegExp(h,"m")};return d})},"dojo/data/util/simpleFetch":function(){define(["../../_base/lang","../../_base/kernel","./sorter"],function(p,d,m){var l={};p.setObject("dojo.data.util.simpleFetch",l);l.errorHandler=function(h,c){c.onError&&c.onError.call(c.scope||d.global,h,c)};l.fetchHandler=function(h,c){var a=c.abort||null,f=!1,k=c.start?c.start:0,b=c.count&&Infinity!==c.count?k+c.count:h.length;c.abort=function(){f=!0;a&&a.call(c)};var e=c.scope||
d.global;c.store||(c.store=this);c.onBegin&&c.onBegin.call(e,h.length,c);c.sort&&h.sort(m.createSortFunction(c.sort,this));if(c.onItem)for(var n=k;n<h.length&&n<b;++n){var g=h[n];f||c.onItem.call(e,g,c)}c.onComplete&&!f&&(n=null,c.onItem||(n=h.slice(k,b)),c.onComplete.call(e,n,c))};l.fetch=function(d){d=d||{};d.store||(d.store=this);this._fetchItems(d,p.hitch(this,"fetchHandler"),p.hitch(this,"errorHandler"));return d};return l})},"dojo/data/util/sorter":function(){define(["../../_base/lang"],function(p){var d=
{};p.setObject("dojo.data.util.sorter",d);d.basicComparator=function(d,l){var h=-1;null===d&&(d=void 0);null===l&&(l=void 0);if(d==l)h=0;else if(d>l||null==d)h=1;return h};d.createSortFunction=function(m,l){function h(a,b,c,e){return function(d,f){d=e.getValue(d,a);f=e.getValue(f,a);return b*c(d,f)}}for(var c=[],a,f=l.comparatorMap,k=d.basicComparator,b=0;b<m.length;b++){a=m[b];var e=a.attribute;if(e){a=a.descending?-1:1;var n=k;f&&("string"!==typeof e&&"toString"in e&&(e=e.toString()),n=f[e]||k);
c.push(h(e,a,n,l))}}return function(a,b){for(var e=0;e<c.length;){var d=c[e++](a,b);if(0!==d)return d}return 0}};return d})},"*noref":1}});
define("esri/layers/CSVLayer","dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../arcgis/csv ./FeatureLayer ../geometry/Extent ../tasks/FeatureSet".split(" "),function(p,d,m,l,h,c,a,f,k){d=d(a,{declaredClass:"esri.layers.CSVLayer",_preventInit:!0,_fieldTypeMap:{Date:"esriFieldTypeDate",Number:"esriFieldTypeDouble",String:"esriFieldTypeString"},constructor:function(a,c){this.url=a;c=m.mixin({},c);this.columnDelimiter=c.columnDelimiter;this.latitudeFieldName=c.latitudeFieldName;
this.longitudeFieldName=c.longitudeFieldName;a=c.layerDefinition;a||(a={fields:c.fields||[],geometryType:"esriGeometryPoint",copyrightText:c.copyright},c.fields&&p.forEach(c.fields,function(a){a.type=this._fieldTypeMap[a.type||"String"];a.alias||(a.alias=a.name)},this));this._buildCsvFcParam={url:this.url,columnDelimiter:this.columnDelimiter,layerDefinition:a,outFields:c.outFields};this.latitudeFieldName&&this.longitudeFieldName&&(this._buildCsvFcParam.locationInfo={locationType:"coordinates",latitudeFieldName:this.latitudeFieldName,
longitudeFieldName:this.longitudeFieldName});this._projectFeatures=m.hitch(this,this._projectFeatures);this._addFeatures=m.hitch(this,this._addFeatures);this._initCSVLayer(c)},refresh:function(){this._fireUpdateStart();this.applyEdits(null,null,this.graphics);this._loadFeatures()},_isWebGLCompatible:function(){return!1},_setMap:function(a){var b=this.inherited(arguments);this._fireUpdateStart();this._projectFeatures(this._csvFC).then(this._addFeatures).otherwise(this._errorHandler);this._csvFC=null;
return b},_initCSVLayer:function(a){var b=this;c.buildCSVFeatureCollection(this._buildCsvFcParam).then(function(c){b._csvFC=c;var d=c.layerDefinition;d.extent=b._getFCExtent(c);a.outFields||(a.outFields=["*"]);a.timeInfo&&(d.timeInfo=a.timeInfo);b._initFeatureLayer({layerDefinition:d},a)}).otherwise(this._errorHandler)},_loadFeatures:function(){c.buildCSVFeatureCollection(this._buildCsvFcParam).then(this._projectFeatures).then(this._addFeatures).otherwise(this._errorHandler)},_projectFeatures:function(a){return c.projectFeatureCollection(a,
this._map.spatialReference)},_addFeatures:function(a){a=new k(a.featureSet);this.applyEdits(a.features,null,null);this._fireUpdateEnd()},_getFCExtent:function(a){var b;if(a&&a.featureSet&&a.featureSet.features){a=a.featureSet.features;var c=a.length;if(1<c){var d=a[0].geometry;b=new f(d.x,d.y,d.x,d.y);for(--c;0<c;c--)d=a[c].geometry,b.xmin=Math.min(b.xmin,d.x),b.ymin=Math.min(b.ymin,d.y),b.xmax=Math.max(b.xmax,d.x),b.ymax=Math.max(b.ymax,d.y);0>=b.getWidth()&&0>=b.getHeight()&&(b=null)}}return b}});
l("extend-esri")&&m.setObject("layers.CSVLayer",d,h);return d});