// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder",["./utils","dojo/i18n!esri/nls/jsapi"],function(e,h){function m(b){Object.keys(b).forEach(function(d){var a=b[d];void 0!==a&&null!==a||delete b[d]})}h=h.geoenrichment.dijit.ReportPlayer.ReportPlayer;var f={NUMBER:"n/",createFieldInfoFromCalculator:function(b,d,a){if(!b)return null;d=a&&a.format;var f=a&&a.autoformatCurrency,k=a&&a.additionalText,h=a&&a.calculatorName,l=a&&a.defaultDistanceUnits;
a={comparisonIndex:a&&a.comparisonIndex};a.alias=b.getDescriptionWithType()||b.getAliasWithType();var c=b.variable;a.hasVariable=!0;a.variableID=c.id;a.fullName=c.fullName;a.fieldCategory=c.fieldCategory;a.vintage=c.vintage;a.type=c.type;var g=b.getToggleGroup&&b.getToggleGroup();a.statefulName=g?g.value:"n/"+c.fullName;g=b.getCalcType().charAt(0);a.name=e.name.createFieldNameFromVariable(c,g);d?e.format.setFieldInfoFormat(a,d):(a.decimals=b.getDecimals(),a.showCurrency=!(!f||"n"!==g||!c.units||"CURRENCY"!==
c.units.toUpperCase()),a.showPercent=!a.showCurrency&&("p"===g||"n"===g&&c.units&&"PCT"===c.units.toUpperCase()),a.useThousandsSeparator=!0);"string"===typeof k&&(a.additionalText=k);c.isWebMap?(a.isWebMap=!0,a.webMapFieldName=c.fieldName,a.webMapField=c.field,a.webMapId=c.webMapId,!d&&c.field&&c.field.format&&(a.decimals=c.field.format.places,a.useThousandsSeparator=!1!==c.field.format.digitSeparator)):c.customDataCollection?(a.isCustomDataCollection=!0,a.customDataCollectionId=c.customDataCollection.id,
a.customDataCollectionUrl=c.customDataCollection.url,a.customDataCollectionPortalUrl=c.customDataCollection.portalUrl):c.isSiteAttribute?(a.isSiteAttribute=!0,a.attribute=c.attribute,!d&&0<c.attribute.places&&(a.decimals=c.attribute.places)):c.isDataLayerAttribute&&(a.isDataLayerAttribute=!0,a.layerID=c.layerID,a.layerUrl=c.layerUrl,a.layerName=c.layerName,a.attribute=c.attribute,a.type=c.attribute.type,!d&&0<c.attribute.decimals&&(a.decimals=c.attribute.decimals),"DISTANCE"===c.attribute.name&&(a.units=
c.attribute.units||l||"esriMiles"));a.usedFields=c.usedFields;a.expressionText=c.expressionText;e.name.provideQualifiedFieldInfoTemplateName(a,h);m(a);return a},createFieldInfoFromScript:function(b,d,a){d=a&&a.format;var f=a&&a.additionalText,k=a&&a.calculatorName;b=b||{};b.name=b.name||e.name.DEFAULT_SCRIPT_NAME;b.alias=b.alias||h.scriptNameDefault;b.decimals=Number(b.decimals)||0;a={comparisonIndex:a&&a.comparisonIndex};a.name=e.name.createFieldNameFromScript(b);e.name.provideQualifiedFieldInfoTemplateName(a,
k);a.script=b;d?e.format.setFieldInfoFormat(a,d):(a.decimals=Number(b.decimals),a.showCurrency=!1,a.showPercent=!1,a.useThousandsSeparator=!0);"string"===typeof f&&(a.additionalText=f);m(a);return a},createFieldInfoFromChart:function(b){return{isChart:!0,chartJson:b}},createFieldInfoFromImage:function(b,d){return{isImage:!0,imageJson:b,triggerJson:d}},createFieldInfoFromShape:function(b){return{isShape:!0,shapeJson:b}},createFieldInfoFromSection:function(b){return{isReportSection:!0,sectionJson:b}},
createFieldInfoFromInfographic:function(b){return{isInfographic:!0,infographicJson:b}},createFieldInfoFromMissingVariable:function(b){return{isMissing:!0,variable:b,alias:b.alias}}},l=/^\[\w+\]$/,n=/\[\w+\]/;f.createFieldInfoFromLabel=function(b,d){if("string"!==typeof b)return null;b=b.trim();var a=l.test(b);if(!d||a){if(!a)return null;b=b.replace(/\[|\]/g,"").toUpperCase();return f.createFieldInfoFromSpecialFieldName(e.fields.uiToTemplate(b))}return n.test(b)?(b=e.richText.collectFieldInfosFromRenderedXMLString(b))&&
e.richText.createFieldInfoFromRichText(b.xmlString,b.fieldInfos,b.specialFieldInfos):null};f.createFieldInfoFromSpecialFieldName=function(b,d){if("string"!==typeof b)return null;var a;b=b.substr(b.indexOf(".")+1);b=b.toUpperCase();"CURRDATE"===b?a={name:e.fields.DATE_FIELD_NAME,alias:e.fields.DATE_FIELD_ALIAS,format:d||e.fields.DATE_FIELD_DEFAULT_FORMAT}:"SITENOTE"===b?a={name:e.fields.SITENOTE_FIELD_NAME,alias:e.fields.SITENOTE_FIELD_ALIAS}:"SITENOTES"===b&&(a={name:e.fields.SITENOTES_FIELD_NAME,
alias:e.fields.SITENOTES_FIELD_ALIAS});if(a)return a;(d=e.fields.templateToUIHeader(b))?a={name:e.fields.qualifyTemplateHeaderName(b),alias:d}:(d=e.fields.templateToUIReportVar(b))&&(a={name:d,alias:d});return a};var p=/_P$/i;f.isFieldInfoInPercentState=function(b){return b&&b.statefulName&&("p"===b.statefulName.charAt(0)||p.test(b.statefulName))};return f});