// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/ReportContainerPagination.html":'\x3cdiv class\x3d"esriGEReportPlayer_reportContainerPagination"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"infographicPageDiv"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"pageNavigatorDiv" class\x3d"reportContainerPagination_pageNavigatorDiv"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"emptyPlaceholder" class\x3d"reportContainerPagination_emptyPlaceholder"\x3e${nls.infographicEmpty}\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/reportContainerPagination/ReportContainerPagination","dojo/_base/declare dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/PageNavigator esri/dijit/geoenrichment/utils/DomUtil ../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ../themes/ReportThemes dojo/text!../templates/ReportContainerPagination.html dojo/i18n!esri/nls/jsapi".split(" "),function(e,f,p,q,r,g,h,k,
c,l,m,n,d){d=d.geoenrichment.dijit.ReportPlayer.ReportPlayer;return e([g,h],{templateString:n,nls:d,viewModel:null,theme:null,parentWidget:null,scaleSectionsToFit:!1,maxBulletsLimit:10,documentOptions:null,infographicPage:null,pageNavigator:null,postCreate:function(){var a=this;this.inherited(arguments);this.infographicPage=this.viewModel.layoutBuilder.createElement("infographicPage",{viewModel:this.viewModel,theme:this.theme,parentWidget:this,keepPagePosition:!1,renderBackgroundImage:!0,scaleSectionsToFit:this.scaleSectionsToFit,
onResized:function(b){a.onResized(b)},onPageIndexChanged:function(b){a.pageNavigator.setCurrentPageIndex(b)}},this.infographicPageDiv);this.own(this.infographicPage);this.pageNavigator=(new k({showArrows:!1,getNumPages:function(){return a.infographicPage.getNumItems()},onPageChanged:function(b){a.showSlideAt(b)}})).placeAt(this.pageNavigatorDiv);this.own(this.pageNavigator);this._setEmptyState(!1)},resize:function(a,b){this.infographicPage.resize(a,b)},notifyShown:function(){this._pendingJson?(this.fromJson(this._pendingJson),
!this._pendingJson&&this.onPendingDataApplied()):this.infographicPage.notifyShown()},getCurrentSlideIndex:function(){return this.infographicPage.getCurrentPageIndex()},showSlideAt:function(a){this.infographicPage.setCurrentPageIndex(a)},showNextSlide:function(){this.infographicPage.showNextPage()},showPreviousSlide:function(){this.infographicPage.showPreviousPage()},_pendingJson:null,fromJson:function(a){if(this._canApplyJson()){this._pendingJson=null;this.documentOptions=a.documentOptions;this.theme=
this.infographicPage.theme=a.theme&&a.theme.id!==m.GRAPHIC?a.theme:null;a=l.collectSectionJsons(a,{backgroundForeground:!1});this._setEmptyState(!a.length);var b=a.length>this.maxBulletsLimit;f[b?"add":"remove"](this.domNode,"hasCustomPaginationBullets");c[b?"show":"hide"](this.pageNavigatorDiv);return this.infographicPage.setItems(a).then(function(){this.pageNavigator.reset()}.bind(this))}this._pendingJson=a},_canApplyJson:function(){return c.isNodeInLayout(this.domNode)},_setEmptyState:function(a){c.hide([this.infographicPageDiv,
this.emptyPlaceholder,this.reportBackgroundDiv]);c.show(a?this.emptyPlaceholder:[this.infographicPageDiv,this.reportBackgroundDiv])},onResized:function(a){},onPendingDataApplied:function(){}})});