// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/sorting/GridSortUtil","dojo/on dojo/dom-class dojo/dom-construct dojo/dom-style dojo/touch ./_RowStyler ../GridDataUtil ../GridQueryUtil ../GridLayoutCalculator ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoRenderer esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/ObjectUtil".split(" "),function(q,h,r,m,t,k,u,n,w,x,l,p){var b={},v=/^(\d+|\d+[.,]\d+)%$/;b.isGridSortable=function(a){return!a.allowSorting||
a.isEmptyTable()||3>a.store.data.length||!a.viewModel.dynamicReportInfo?!1:!0};b.updateSorting=function(a,e){if(b.isGridSortable(a)){var c=b._collectHeaderRowInfo(a);c&&b._makeSortable(a,c);e&&b._applySortInfo(a,c)}};b._collectHeaderRowInfo=function(a){for(var b=a.store.data.length-2,c,f,d=0;d<b;d++){var g=n.queryCells(a,{rowIndex:d});if(g&&g.length===a.columns.length){c=g;f=d;break}}if(c)for(d=f+1;d<a.store.data.length;d++){if(g=n.queryCells(a,{rowIndex:d}),!g||g.length!==a.columns.length)return null}else return null;
return{cells:c,headerRowIndex:f}};b._makeSortable=function(a,e){e.cells.forEach(function(a){h.add(a.domNode,"esriGEClickable");q(a.contentBlock,t.press,function(c){b._checkCanSortOnHeaderClick(c)&&b._toggleSortForCell(a,e)});var c=r.create("div",{"class":"sortArrow"},a.domNode);m.set(c,"top",(a.getHeight()-9)/2+"px");var d=a.getFullStyle();m.set(c,d&&"left"===d.horizontalAlign?"right":"left","5px");a._sortArrow=c});b._updateArrows(a,e)};b._checkCanSortOnHeaderClick=function(a){return a&&a.path.some(function(a){return"A"===
a.nodeName})?!1:!0};b._updateArrows=function(a,b){b.cells.forEach(function(c){var b=c._sortArrow;h.remove(b,"sortArrowUp");h.remove(b,"sortArrowDown");l.hide(b);a._sortInfo&&a._sortInfo.field===c.column.field&&("asc"===a._sortInfo.order?(h.add(b,"sortArrowUp"),l.show(b)):"desc"===a._sortInfo.order&&(h.add(b,"sortArrowDown"),l.show(b)))})};b._applySortInfo=function(a,e){b._updateArrows(a,e);if(a._sortInfo){if(a._sortInfo.order){for(var c=[],f=a._sortInfo.originalData.slice(),d=0;d<e.headerRowIndex+
1;d++)c.push(f.shift());e=k.getStyleInfo(f,a.columns);var g=a._sortInfo.field;f.sort(function(b,c){function e(a){var b=u.getNumericDataValue(a,g);if(void 0!==b)return b;a=a[g];return"string"===typeof a?(b=v.test(a)?p.parseNumber(a.replace("%","")):p.parseNumber(a),isNaN(b)?a:b):a}b=e(b);var d=e(c);c="desc"===a._sortInfo.order;"number"===typeof b||"number"===typeof d?(b=Number(b),d=Number(d),b=b>d?1:b<d?-1:0):(b=String(b),d=String(d),b=b.localeCompare(d));return c?-b:b});e&&k.setAlternatingColors(f,
a.columns,e);a.store.data=c.concat(f)}else a.store.data=a._sortInfo.originalData,k.resetStyling(a._sortInfo.originalData,a.columns);a.refresh({applyCurrentSorting:!1})}};b._toggleSortForCell=function(a,e){var c=a.parentGrid,f=c._sortInfo&&c._sortInfo.field===a.column.field?c._sortInfo.order:null;c._sortInfo={field:a.column.field,order:null,originalData:c._sortInfo?c._sortInfo.originalData:c.store.data.slice()};f?"desc"===f?c._sortInfo.order="asc":"asc"===f&&(c._sortInfo.order=null):c._sortInfo.order=
"desc";b._applySortInfo(c,e);c.onSortingChanged(b.getSorting(c))};b.getSorting=function(a){return a._sortInfo&&{field:a._sortInfo.field,order:a._sortInfo.order}};b.setSorting=function(a,e){if(b.isGridSortable(a)&&e){var c=b._collectHeaderRowInfo(a);c&&(a._sortInfo={field:e.field,order:e.order,originalData:a._sortInfo?a._sortInfo.originalData:a.store.data.slice()},b._applySortInfo(a,c))}};return b});