// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/MapBuilder","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when dojo/dom-construct dojo/dom-geometry esri/arcgis/utils esri/graphicsUtils ./layers/MapContentBuilder ./legend/LegendBuilder ./MapLoadTracker ./StaticMap ./WebMapsUtil ./Popup ../../../dataProvider/supportClasses/AreaDataUtil esri/dijit/geoenrichment/utils/ImageUtil esri/dijit/geoenrichment/utils/UrlUtil".split(" "),function(h,n,l,k,p,q,r,t,u,v,w,x,m,y,z,A,B){h=
h(null,{_mapInfos:null,_mapDivId:0,_mapImageInfos:null,renderMapsFromCalculators:!1,constructor:function(c){n.mixin(this,c);this.reset()},setArcgisUrl:function(c){c&&(r.arcgisUrl=B.combine(c,"/sharing/rest/content/items"))},reset:function(){this._mapInfos={};this._mapImageInfos=null},collectAreaMaps:function(c){var b=[];c=c||0;var a=this._mapInfos[c],e;for(e in a){var f=a[e],d=f.node;if(d.parentNode){var g=q.position(d);b.push({areaIndex:c,node:d,x:g.x,y:g.y,position:-1,map:f.map,legend:f.legend,
itemId:f.itemId})}}b.sort(function(a,b){return a.x-b.x});b.sort(function(a,b){return a.y-b.y});b.forEach(function(a,b){a.position=b});return b},collectAllAreasMaps:function(){var c=[],b;for(b in this._mapInfos)c=c.concat(this.collectAreaMaps(b));return c},setFallbackMapImageInfos:function(c){c?(this._mapImageInfos={},c.forEach(function(b){var a=b.areaIndex||0;(this._mapImageInfos[a]=this._mapImageInfos[a]||{})[b.itemId]=b},this)):this._mapImageInfos=null},createMap:function(c,b){b.areaIndex=b.areaIndex||
0;return k(this._doCreateMap(c,b),function(a){return b.waitForLoad?k(w.waitForLoad(a.map),function(){return a}):a})},_doCreateMap:function(c,b){var a=this;if(this.renderMapsFromCalculators&&b.calculatorFieldName){var e=z.getAreaDataValue({fieldName:b.calculatorFieldName,fieldData:b.fieldData});if(e)return this._createStaticMap({url:A.base64DataToDataURL(e)},c)}return k(m.getItem(b.webMapId),function(f){if(!f)return(new l).reject(Error("Can't load an item or the item is incorrect."));var d=new l;try{a._createMapFromItem(f,
c,b).then(d.resolve,d.reject)}catch(g){d.reject(g),console.log(g)}return d.promise}).otherwise(this._createFallbackStaticMap.bind(this,b,c))},_createMapFromItem:function(c,b,a){var e=this;return m.createMap(c,b,{extent:a.extent||t.graphicsExtent(a.features).expand(a.expandFactor||1.5),sliderPosition:!1===a.sliderPosition?"none":a.sliderPosition||"top-right",defaultBasemapId:a.defaultBasemapId,additionalLayerInfos:a.additionalLayerInfos,infoWindow:new y({},p.create("div"))}).then(function(c){var d=
c&&c.map;return d?k(u.addLayersToMap(d,{areaName:a.areaName,features:a.features,locatorPointsControllers:a.locatorPointsControllers,fieldData:a.fieldData,geClient:a.geClient,countryID:a.countryID,additionalLayerInfos:a.additionalLayerInfos,calculatorFieldName:a.calculatorFieldName}),function(){void 0===b.__mapDivId&&(b.__mapDivId=e._mapDivId++);var c={node:b,map:d,itemId:a.webMapId,legend:null};v.createLegend(d,b,a.legendController,{onCreated:function(a){c.legend=a},onDestroyed:function(){delete c.legend}});
return(e._mapInfos[a.areaIndex]=e._mapInfos[a.areaIndex]||{})[b.__mapDivId]=c}):(new l).reject(Error("Can't create a map."))})},_createFallbackStaticMap:function(c,b){return this._createStaticMap(this._mapImageInfos&&this._mapImageInfos[c.areaIndex]&&this._mapImageInfos[c.areaIndex][c.webMapId],b)},_createStaticMap:function(c,b){var a=c&&new x(c,b);return a&&a.load().then(function(){return a.loaded?a:null})}});h.EXPAND_FACTOR=1.5;return h});