// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/WebMapsUtil","dojo/_base/lang dojo/Deferred dojo/_base/Deferred dojo/when esri/kernel esri/IdentityManager esri/arcgis/utils esri/geometry/Extent esri/request esri/dijit/geoenrichment/utils/UrlUtil".split(" "),function(g,v,r,l,t,w,m,p,u,n){var f={};n.isPageRunOnWebService()||(t.id.getCredential=function(){var a=new r;a.reject(Error("Can't get credentials"));return a});var q={_itemsCache:{},_siCache:{},loadItem:function(a){this._itemsCache[a]||
(this._itemsCache[a]=m.getItem(a));return l(this._itemsCache[a],function(a){return a&&g.clone(a)})},loadServiceInfo:function(a,c){this._siCache[a]||(this._siCache[a]=c({url:a,content:{f:"json"}}));return this._siCache[a]}};f.getItem=function(a){return q.loadItem(a)};f.isWebMapType=function(a){return a&&"Web Map"===a.type};f.createMap=function(a,c,b){b=b||{};if(a&&a.item)return f.isWebMapType(a.item)&&b.additionalLayerInfos&&f._addAdditionalLayerInfosToOperationalLayers(a.itemData.operationalLayers,
b.additionalLayerInfos),l(!f.isWebMapType(a.item)&&f.createItemDataForNonWebMapItem(a,{defaultBasemapId:b.defaultBasemapId,additionalLayerInfos:b.additionalLayerInfos}),function(){return m.createMap(a,c,{usePopupManager:!0,mapOptions:{extent:b.extent,sliderPosition:b.sliderPosition,infoWindow:b.infoWindow}})})};f.createItemDataForNonWebMapItem=function(a,c){function b(){d.url=function(a){["FeatureServer","MapServer","ImageServer"].some(function(e){if(-1!==a.indexOf(e))return a=a.substr(0,a.lastIndexOf(e)+
e.length),!0});return a}(d.url);var a=c.requestFunc||u;n.registerCORS(d.url);return q.loadServiceInfo(d.url,a).then(function(a){return l(function(a,e){a.extent||(e=e.initialExtent||e.fullExtent||e.extent,!e||e instanceof p||(e=new p(e)),a.extent=e)}(d,a),function(){return a})})}function h(e){a.itemData={baseMap:null,operationalLayers:e};c.additionalLayerInfos&&f._addAdditionalLayerInfosToOperationalLayers(e,c.additionalLayerInfos);return l(f.provideDefaultBaseMapForItemData(a.itemData,c),function(){return a})}
c=c||{};var d=a.item,k=a.itemData;if("Feature Service"===d.type)return b().then(function(a){for(var e=[],b=0;b<a.layers.length;b++){var c=a.layers[b],f=c.id;e.unshift({url:d.url+"/"+f,capabilities:a.capabilities||"Query",id:"featureServiceLayer_"+f,visibility:c.defaultVisibility,mode:1,title:c.title,description:c.description})}return h(e)});if("Map Service"===d.type)return b().then(function(a){a=[g.mixin({url:d.url,id:"mapServiceLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("Image Service"===
d.type)return b().then(function(a){a=[g.mixin({url:d.url,id:"imageServiceLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("Vector Tile Service"===d.type)return b().then(function(a){a=[g.mixin({url:d.url,id:"vectorTileServiceLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WMSServer"===d.type)return b().then(function(a){a=[g.mixin({url:d.url,id:"wmsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WMTS"===d.type)return b().then(function(a){a=
[g.mixin({url:d.url,id:"wmtsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WFS"===d.type)return b().then(function(a){a=[g.mixin({url:d.url,id:"wfsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("KML"===d.type){n.registerCORS(d.url);var m=[g.mixin({url:d.url,id:"kmlLayer01",visibility:!0,opacity:1,title:"KML Layer",type:"KML"},k)];return h(m)}};f.provideDefaultBaseMapForItemData=function(a,c){c=c||{};if(!a.baseMap)return l(function(){var a={title:"My basemap",
baseMapLayers:[{id:"basemapLayer01",opacity:c.hideBasemap?0:1,visibility:!c.hideBasemap,url:"http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer"}]};return c.defaultBasemapId?f.getItem(c.defaultBasemapId).then(function(b){return b&&b.itemData&&b.itemData.baseMap||a}):a}(),function(b){a.baseMap=b;return a})};f._addAdditionalLayerInfosToOperationalLayers=function(a,c){c.forEach(function(b,c){a.push({url:b.url,id:"additionalLayer"+c,visibility:!0,opacity:1})})};return f});