// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/_SerializationSupport","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when dojo/promise/all ./supportClasses/AnalysisAreaJsonUtil ./supportClasses/AreasPreprocessor ./supportClasses/ReportDataProcessor ./supportClasses/attachments/AttributesUtil ./supportClasses/attachments/NotesUtil ../core/supportClasses/templateJsonUtils/TemplateJsonSerializer ../core/conversion/PortalToEditorConverter ../core/themes/ThemeLibrary ../core/infographics/dataDrilling/EnrichUtil ../core/infographics/utils/InfographicJsonUtil".split(" "),
function(r,k,t,e,d,l,x,y,f,m,n,z,A,u,p){var q={getAttachmentsStoreJson:function(a){return a?d([a.getAttachments(),a.getAttributes(),a.getNotes()]).then(function(a){var c=a[0]||[],b=a[1]||[],h=a[2]||[];return d(c.map(function(a){return d([a.getThumbnail(),a.getAttachmentUrl()]).then(function(c){a.__thumbnail=c[0];a.__url=c[1]})})).then(function(){return{attachments:c.map(function(a){var c=a.__thumbnail,b=a.__url;delete a.__thumbnail;delete a.__url;return{description:a.description,thumbnail:c,url:b}}),
attributes:b.map(function(a){return f.attributeToJson(a)}),notes:h.map(function(a){return m.noteToJson(a)})}})}):null},getAttachmentsStoreFromJson:function(a){if(!a)return null;var b=a.attributes||[],b=b.map(f.attributeFromJson),c=a.notes||[],c=c.map(m.noteFromJson);return{getAttachments:function(){return a.attachments?a.attachments.map(function(a){return{description:a.description,getThumbnail:function(){return a.thumbnail},getAttachmentUrl:function(){return a.url}}}):[]},getAttributes:function(){return b},
getNotes:function(){return c}}}};return r(null,{reportDataToJson:function(a,b){b=b||{};return e(b.allowDataDrilling&&this._serializeDataDrilling(a),function(){return e(q.getAttachmentsStoreJson(a.attachmentsStore),function(c){var d;d=!1!==b.forceFixedDataMode?{portalUrl:a.config.portalUrl}:k.mixin({},a.config);var h=a.isClassic,v=a.reportType,e=a.reportTitle,w=n.serialize(a.templateJson),f={},g;for(g in a.reportObject)a.reportObject[g]&&"object"!==typeof a.reportObject[g]&&(f[g]=a.reportObject[g]);
c={isClassic:h,reportType:v,reportTitle:e,templateJson:w,reportObject:f,fieldData:a.fieldData,analysisAreas:l.areasToJson(a.analysisAreas),infographicOptions:a.infographicOptions&&a.infographicOptions.toJson(),attachmentsStore:c,config:d,mapImageInfos:b.mapImageInfos};console.log("_SerializationSupport.js \x3d\x3e reportDataJson");console.log(c);return c})})},_serializeDataDrilling:function(a){var b=u.getEnrichInfosForTemplateJson(a.infographicOptions.countryID,a.templateJson),c=[];c.push(this.enrichFieldData(b,
k.mixin({analysisAreas:a.analysisAreas,fieldData:a.fieldData},a.config)));c.push(this._enrichInfographicVariables(a,b));return d(c)},_enrichInfographicVariables:function(a,b){var c=a.infographicOptions;return e(c.getOptions().getItems(c.countryID),function(){var e=[];b.forEach(function(b){b.isInfographic&&b.variables&&a.analysisAreas.forEach(function(a,d){c.setCurrentAnalysisAreaIndex(d);var f=new t;a=c.createGeoenrichment();a.onDone=function(){f.resolve()};a.country=c.countryID;a.setGeoLevels(p.getSubLevels(b),
p.getHighestLevel(b));a.setVariables(b.variables);a.setStudyArea(c.studyArea);e.push(f.promise)})});return d(e)})},reportDataFromJson:function(a){var b=a.fieldData;b.featureData&&(b.areaData=b.featureData.map(function(a){return{mainCalculator:{data:a}}}),delete b.featureData);return{isClassic:a.isClassic,reportType:a.reportType,reportTitle:a.reportTitle,templateJson:n.deserialize(a.templateJson),reportObject:a.reportObject,fieldData:b,analysisAreas:l.areasFromJson(a.analysisAreas),infographicOptions:a.infographicOptions&&
this._infographicOptionsProvider.getInfographicOptionsFromJson(a.infographicOptions),attachmentsStore:a.attachmentsStore&&q.getAttachmentsStoreFromJson(a.attachmentsStore),config:a.config||{},mapImageInfos:a.mapImageInfos}}})});