// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.25/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/Gauge","dojo/_base/declare dojo/_base/lang dojo/dom-style dojox/gfx dojox/gfx/matrix ./Donut ./animation/_GaugeAnimation ./supportClasses/GaugeLabelPlacement".split(" "),function(u,v,p,q,r,w,x,m){var t={getLabelInfo:function(c,a,h,f,e,b,k){var l=(void 0!==k?k:c[0].tooltip.valueLabel)+(a.series.isPercentState?"%":""),d=(a.series.donutHolePercent||0)/100*h*1.5;a.series.donutMainLabelPosition===m.INSIDE&&a.series.donutShowIcons&&(d/=
2);var g={series:v.mixin({},a.series)};g.series.font=a.series.donutMainLabelFont||g.series.font;g.series.fontColor=a.series.donutMainLabelFontColorFromConditionalStyling?c[0].fill:a.series.donutMainLabelFontColor||g.series.fontColor;c=function(){if(a.series.donutMainLabelFontSize)return a.series.donutMainLabelFontSize;if(a.series.donutMainLabelPosition===m.OUTSIDE)return 30;g.series.font=g.series.font.replace(/\s\w*px/," 30px");var c=q._base._getTextBox(l,{font:g.series.font});return Math.min(100,
Math.max(30,30*d/Math.max(c.w,c.h)))}();g.series.font=g.series.font.replace(/\s\w*px/," "+c+"px");k=q._base._getTextBox(l,{font:g.series.font});var n;a.series.donutMainLabelPosition===m.OUTSIDE&&(b=r._degToRad(b),e=b+2*e*Math.PI,e=a.series.donutShowArrowIndicator?e:(b+e)/2,b=k.w*Math.cos(e),n=k.h*Math.sin(e),n={labelX:f.cx+h*Math.cos(e)-k.w/2+.8*b,labelY:f.cy+h*Math.sin(e)+k.h/3+.8*n,pushX:b,pushY:n});return{text:l,fontSize:c,labelBox:k,labelT:g,maxLabelSize:d,outsideInfo:n}}},y={renderLabel:function(c,
a,h,f,e,b,k,l){var d=function(g,d){var l;g=t.getLabelInfo(c,a,h,e,g,k,d);a.series.donutMainLabelPosition===m.OUTSIDE?d=b.renderLabel(f,g.outsideInfo.labelX,g.outsideInfo.labelY,g.text,g.labelT,!0,"left"):(d=e.cx-g.labelBox.w/2,l=e.cy,50!==a.series.donutArcPercent&&(l+=g.labelBox.h/3),a.series.donutShowIcons&&(l-=g.maxLabelSize/1.5),d=b.renderLabel(f,d,l,g.text,g.labelT,!0,"left"));d&&"underline"===a.series.donutMainLabelTextDecoration&&(p.set(d,"textDecoration","underline"),p.set(d,"textDecorationColor",
g.labelT.series.fontColor));return{labelInfo:g,element:d}};l.push({isLabel:!0,func:d});return d}},z={renderArrow:function(c,a,h,f,e,b){var k=function(b){b=r._degToRad(e)+2*b*Math.PI;var d=[];d.push({x:f.cx+5*Math.cos(b+Math.PI/2),y:f.cy+5*Math.sin(b+Math.PI/2)});d.push({x:f.cx+5*Math.cos(b+Math.PI),y:f.cy+5*Math.sin(b+Math.PI)});d.push({x:f.cx+5*Math.cos(b-Math.PI/2),y:f.cy+5*Math.sin(b-Math.PI/2)});d.push({x:f.cx+h*Math.cos(b),y:f.cy+h*Math.sin(b)});return{shape:c.createPath().moveTo(d[0].x,d[0].y).lineTo(d[1].x,
d[1].y).lineTo(d[2].x,d[2].y).lineTo(d[3].x,d[3].y).lineTo(d[0].x,d[0].y).setStroke(a.series.donutArrowIndicatorLineColor).setFill(a.series.donutArrowIndicatorFillColor)}};b.push({isArrow:!0,func:k});return k}};return u([w,x],{startAngleOffset:-90,_getLabelInfo:function(c,a,h,f,e){return t.getLabelInfo(c,a,h,f,this._getSliceValueAt(e,0,a),this._getStartAngle(a))},_preprocessParams:function(c,a,h,f,e,b,k){c=this._getLabelInfo(c,a,h,b,k);a.series.donutMainLabelPosition===m.OUTSIDE&&(a=c.outsideInfo.pushX/
2,c=c.outsideInfo.pushY/2,k=h,h=Math.min(f-Math.abs(a),e-Math.abs(c))-5,h=Math.max(h,k/2),b.cx-=a,b.cy-=c,this._lastRenderResults.chartShiftX=-a,this._lastRenderResults.chartShiftY=-c);return{circle:b,r:h}},_renderAdditionalElements:function(c,a,h,f,e,b){this._lastRenderResults.ryMultiplier=this._getRYMultiplier(a);this._renderGaugeDataLabel(c,a,h,f,e,b);this._renderGaugeArrowIndicator(c,a,h,f,e,b)},_gaugeLabelElement:null,_renderGaugeDataLabel:function(c,a,h,f,e,b){a.series.donutMainLabelPosition!==
m.NONE&&(c=y.renderLabel(c,a,h,f,e,this,this._getStartAngle(a),this._animationInfos)(this._getSliceValueAt(b,0,a)),this._gaugeLabelElement=c.element,a.series.donutMainLabelPosition===m.INSIDE&&(this._lastRenderResults.maxIconSize=c.labelInfo.maxLabelSize,this._lastRenderResults.chartIconOffset=c.labelInfo.maxLabelSize/1.25))},_renderGaugeArrowIndicator:function(c,a,h,f,e,b){a.series.donutShowArrowIndicator&&z.renderArrow(f,a,h,e,this._getStartAngle(a),this._animationInfos)(this._getSliceValueAt(b,
0,a))}})});